// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class Activity {
        /// <summary>
        /// The update
        /// </summary>
        [JsonProperty("update")]
        public UpdateInfo Update { get; set; }

        /// <summary>
        /// The deployment data
        /// </summary>
        [JsonProperty("deployment")]
        public DeploymentWithRelatedUpdates Deployment { get; set; }
    }
}
