// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class AgentSignupRequest {
        /// <summary>
        /// An ID identifying the challenge issued by GET /api/agents/signup/challenge.
        /// </summary>
        [JsonProperty("challengeID")]
        public string ChallengeID { get; set; }

        /// <summary>
        /// Output of the proof-of-work computation over the challengeData returned by GET /api/agents/signup/challenge.
        /// </summary>
        [JsonProperty("challengeResult")]
        public string ChallengeResult { get; set; }
    }
}
