// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class AngularGridGetRowsRequest {
        /// <summary>
        /// The start row
        /// </summary>
        [JsonProperty("startRow")]
        public long StartRow { get; set; }

        /// <summary>
        /// The end row
        /// </summary>
        [JsonProperty("endRow")]
        public long EndRow { get; set; }

        /// <summary>
        /// List of row group cols
        /// </summary>
        [JsonProperty("rowGroupCols")]
        public System.Collections.Generic.List<AngularGridColumn> RowGroupCols { get; set; }

        /// <summary>
        /// List of value cols
        /// </summary>
        [JsonProperty("valueCols")]
        public System.Collections.Generic.List<AngularGridColumn> ValueCols { get; set; }

        /// <summary>
        /// List of group keys
        /// </summary>
        [JsonProperty("groupKeys")]
        public System.Collections.Generic.List<string> GroupKeys { get; set; }

        /// <summary>
        /// The filter model
        /// </summary>
        [JsonProperty("filterModel")]
        public AngularGridAdvancedFilterModel FilterModel { get; set; }

        /// <summary>
        /// List of sort model
        /// </summary>
        [JsonProperty("sortModel")]
        public System.Collections.Generic.List<AngularGridSortModelItem> SortModel { get; set; }
    }
}
