// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class AppCreateStackRequest {
        /// <summary>
        /// The name of the stack being created.
        /// </summary>
        [JsonProperty("stackName")]
        public string StackName { get; set; }

        /// <summary>
        /// An optional set of tags to apply to the stack.
        /// </summary>
        [JsonProperty("tags")]
        public System.Collections.Generic.Dictionary<string, string> Tags { get; set; }

        /// <summary>
        /// An optional set of teams to assign to the stack.
        /// </summary>
        [JsonProperty("teams")]
        public System.Collections.Generic.List<string> Teams { get; set; }

        /// <summary>
        /// An optional state to initialize the stack with.
        /// </summary>
        [JsonProperty("state")]
        public AppUntypedDeployment State { get; set; }

        /// <summary>
        /// The configuration for the new stack.
        /// </summary>
        [JsonProperty("config")]
        public AppStackConfig Config { get; set; }
    }
}
