// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class AppCreatePolicyPackResponse {
        /// <summary>
        /// The version number
        /// </summary>
        [JsonProperty("version")]
        public long Version { get; set; }

        /// <summary>
        /// The upload URI
        /// </summary>
        [JsonProperty("uploadURI")]
        public string UploadURI { get; set; }

        /// <summary>
        /// RequiredHeaders represents headers that the CLI must set in order for the upload to succeed.
        /// </summary>
        [JsonProperty("requiredHeaders")]
        public System.Collections.Generic.Dictionary<string, string> RequiredHeaders { get; set; }
    }
}
