// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Pulumi.Cloud.Sdk.Models {
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AppDiffKind {
        /// <summary>
        /// DiffAdd indicates that the property was added.
        /// </summary>
        [EnumMember(Value = "add")]
        DiffAdd,

        /// <summary>
        /// DiffAddReplace indicates that the property was added and requires that the resource be replaced.
        /// </summary>
        [EnumMember(Value = "add-replace")]
        DiffAddReplace,

        /// <summary>
        /// DiffDelete indicates that the property was deleted.
        /// </summary>
        [EnumMember(Value = "delete")]
        DiffDelete,

        /// <summary>
        /// DiffDeleteReplace indicates that the property was deleted and requires that the resource be replaced.
        /// </summary>
        [EnumMember(Value = "delete-replace")]
        DiffDeleteReplace,

        /// <summary>
        /// DiffUpdate indicates that the property was updated.
        /// </summary>
        [EnumMember(Value = "update")]
        DiffUpdate,

        /// <summary>
        /// DiffUpdateReplace indicates that the property was updated and requires that the resource be replaced.
        /// </summary>
        [EnumMember(Value = "update-replace")]
        DiffUpdateReplace,
    }
}
