// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Pulumi.Cloud.Sdk.Models {
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AppOpType {
        /// <summary>
        /// OpSame indicates no change was made.
        /// </summary>
        [EnumMember(Value = "same")]
        OpSame,

        /// <summary>
        /// OpCreate indicates a new resource was created.
        /// </summary>
        [EnumMember(Value = "create")]
        OpCreate,

        /// <summary>
        /// OpUpdate indicates an existing resource was updated.
        /// </summary>
        [EnumMember(Value = "update")]
        OpUpdate,

        /// <summary>
        /// OpDelete indicates an existing resource was deleted.
        /// </summary>
        [EnumMember(Value = "delete")]
        OpDelete,

        /// <summary>
        /// OpReplace indicates an existing resource was replaced with a new one.
        /// </summary>
        [EnumMember(Value = "replace")]
        OpReplace,

        /// <summary>
        /// OpCreateReplacement indicates a new resource was created for a replacement.
        /// </summary>
        [EnumMember(Value = "create-replacement")]
        OpCreateReplacement,

        /// <summary>
        /// OpDeleteReplaced indicates an existing resource was deleted after replacement.
        /// </summary>
        [EnumMember(Value = "delete-replaced")]
        OpDeleteReplaced,

        /// <summary>
        /// OpRead indicates reading an existing resource.
        /// </summary>
        [EnumMember(Value = "read")]
        OpRead,

        /// <summary>
        /// OpReadReplacement indicates reading an existing resource for a replacement.
        /// </summary>
        [EnumMember(Value = "read-replacement")]
        OpReadReplacement,

        /// <summary>
        /// OpRefresh indicates refreshing an existing resource.
        /// </summary>
        [EnumMember(Value = "refresh")]
        OpRefresh,

        /// <summary>
        /// OpReadDiscard indicates removing a resource that was read.
        /// </summary>
        [EnumMember(Value = "discard")]
        OpReadDiscard,

        /// <summary>
        /// OpDiscardReplaced indicates discarding a read resource that was replaced.
        /// </summary>
        [EnumMember(Value = "discard-replaced")]
        OpDiscardReplaced,

        /// <summary>
        /// OpRemovePendingReplace indicates removing a pending replace resource.
        /// </summary>
        [EnumMember(Value = "remove-pending-replace")]
        OpRemovePendingReplace,

        /// <summary>
        /// OpImport indicates importing an existing resource.
        /// </summary>
        [EnumMember(Value = "import")]
        OpImport,

        /// <summary>
        /// OpImportReplacement indicates replacement of an existing resource with an imported resource.
        /// </summary>
        [EnumMember(Value = "import-replacement")]
        OpImportReplacement,
    }
}
