// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class AppParameterizationDescriptorV1 {
        /// <summary>
        /// Name is the name of the parameterized package.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// Version is the version of the parameterized package.
        /// </summary>
        [JsonProperty("version")]
        public string Version { get; set; }

        /// <summary>
        /// Value is the parameter value of the package.
        /// </summary>
        [JsonProperty("value")]
        public System.Collections.Generic.List<byte[]> Value { get; set; }
    }
}
