// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class AppPreludeEvent {
        /// <summary>
        /// Config contains the keys and values for the update. Encrypted configuration values may be blinded.
        /// </summary>
        [JsonProperty("config")]
        public System.Collections.Generic.Dictionary<string, string> Config { get; set; }
    }
}
