// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class AppRenewUpdateLeaseResponse {
        /// <summary>
        /// The renewed token.
        /// </summary>
        [JsonProperty("token")]
        public string Token { get; set; }

        /// <summary>
        /// TokenExpiration is a UNIX timestamp by which the token will expire.
        /// </summary>
        [JsonProperty("tokenExpiration")]
        public long TokenExpiration { get; set; }
    }
}
