// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class BitBucketAccessStatusResponse {
        /// <summary>
        /// Whether the current user has a valid BitBucket OAuth token.
        /// </summary>
        [JsonProperty("hasUserToken")]
        public bool HasUserToken { get; set; }

        /// <summary>
        /// List of BitBucket workspaces available to the user for integration.
        /// </summary>
        [JsonProperty("availableWorkspaces")]
        public System.Collections.Generic.List<BitBucketWorkspace> AvailableWorkspaces { get; set; }
    }
}
