// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    [JsonSubTypeName("description_updated")]
    public class ChangeRequestDescriptionUpdatedEvent : ChangeRequestEvent {
        /// <summary>
        /// The previous description before the update
        /// </summary>
        [JsonProperty("previousDescription")]
        public string PreviousDescription { get; set; }

        /// <summary>
        /// The new description after the update
        /// </summary>
        [JsonProperty("newDescription")]
        public string NewDescription { get; set; }
    }
}
