// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    [JsonSubTypeName("approved_by_user")]
    public class ChangeRequestApprovedEvent : ChangeRequestEvent {
    }
}
