// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class CopilotRequest {
        /// <summary>
        /// Optional query string (rarely used for direct skill calls)
        /// </summary>
        [JsonProperty("query")]
        public string Query { get; set; }

        /// <summary>
        /// Client state wrappers leading to organization details
        /// </summary>
        [JsonProperty("state")]
        public CopilotState State { get; set; }

        /// <summary>
        /// Skill invocation with parameters
        /// </summary>
        [JsonProperty("directSkillCall")]
        public CopilotDirectSkillCall DirectSkillCall { get; set; }
    }
}
