// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class DiscoveredProject {
        /// <summary>
        /// The organization name.
        /// </summary>
        [JsonProperty("orgName")]
        public string OrgName { get; set; }

        /// <summary>
        /// The discovered project name.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// The discovered stacks belonging to this project.
        /// </summary>
        [JsonProperty("stacks")]
        public System.Collections.Generic.List<DiscoveredStack> Stacks { get; set; }
    }
}
