// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class EnvironmentResponse : EscEnvironment {
        /// <summary>
        /// The list of diagnostics produced during environment evaluation.
        /// </summary>
        [JsonProperty("diagnostics")]
        public System.Collections.Generic.List<EnvironmentDiagnostic> Diagnostics { get; set; }

        /// <summary>
        /// A summary of the functions used in the environment.
        /// </summary>
        [JsonProperty("environmentFunctionSummary")]
        public EnvironmentFunctionSummary EnvironmentFunctionSummary { get; set; }
    }
}
