// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class EnvironmentRevision {
        /// <summary>
        /// A monotonically increasing integer identifying this revision.
        /// </summary>
        [JsonProperty("number")]
        public long Number { get; set; }

        /// <summary>
        /// The timestamp when the revision was created.
        /// </summary>
        [JsonProperty("created")]
        public DateTimeOffset Created { get; set; }

        /// <summary>
        /// The login name of the user who created the revision.
        /// </summary>
        [JsonProperty("creatorLogin")]
        public string CreatorLogin { get; set; }

        /// <summary>
        /// The display name of the user who created the revision.
        /// </summary>
        [JsonProperty("creatorName")]
        public string CreatorName { get; set; }

        /// <summary>
        /// The tags associated with this revision.
        /// </summary>
        [JsonProperty("tags")]
        public System.Collections.Generic.List<string> Tags { get; set; }

        /// <summary>
        /// Information about the retraction, if this revision has been retracted.
        /// </summary>
        [JsonProperty("retracted")]
        public EnvironmentRevisionRetracted Retracted { get; set; }

        /// <summary>
        /// The change request that produced this revision, if any.
        /// </summary>
        [JsonProperty("sourceChangeRequest")]
        public EnvironmentRevisionChangeRequest SourceChangeRequest { get; set; }
    }
}
