// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class EscAccessExpr {
        /// <summary>
        /// The receiver to access.
        /// </summary>
        [JsonProperty("receiver")]
        public EscRange Receiver { get; set; }

        /// <summary>
        /// The accessors to evaluate.
        /// </summary>
        [JsonProperty("accessors")]
        public System.Collections.Generic.List<EscAccessor> Accessors { get; set; }
    }
}
