// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class EscPos {
        /// <summary>
        /// Line is the source code line where this position points. Lines are counted starting at 1 and incremented for each newline character encountered.
        /// </summary>
        [JsonProperty("line")]
        public long Line { get; set; }

        /// <summary>
        /// Column is the source code column where this position points. Columns are counted in visual cells starting at 1, and are incremented roughly per grapheme cluster encountered.
        /// </summary>
        [JsonProperty("column")]
        public long Column { get; set; }

        /// <summary>
        /// Byte is the byte offset into the file where the indicated position begins.
        /// </summary>
        [JsonProperty("byte")]
        public long Byte { get; set; }
    }
}
