// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class GetOrgTemplatesResponse {
        /// <summary>
        /// Map of template source names to their available templates
        /// </summary>
        [JsonProperty("templates")]
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<PulumiTemplateRemote>> Templates { get; set; }

        /// <summary>
        /// Whether the organization has any templates configured
        /// </summary>
        [JsonProperty("orgHasTemplates")]
        public bool OrgHasTemplates { get; set; }

        /// <summary>
        /// Whether there was an access error retrieving templates
        /// </summary>
        [JsonProperty("hasAccessError")]
        public bool HasAccessError { get; set; }

        /// <summary>
        /// Whether there was an upstream error retrieving templates
        /// </summary>
        [JsonProperty("hasUpstreamError")]
        public bool HasUpstreamError { get; set; }

        /// <summary>
        /// Diagnostic messages from template retrieval
        /// </summary>
        [JsonProperty("diagnostics")]
        public System.Collections.Generic.List<string> Diagnostics { get; set; }
    }
}
