// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class GetOrgTemplateSourcesResponse {
        /// <summary>
        /// The list of template sources
        /// </summary>
        [JsonProperty("sources")]
        public System.Collections.Generic.List<TemplateSource> Sources { get; set; }
    }
}
