// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class GetPackageExamplesResponse {
        /// <summary>
        /// Resolved semantic version.
        /// </summary>
        [JsonProperty("version")]
        public string Version { get; set; }

        /// <summary>
        /// Path to the package navigation endpoint.
        /// </summary>
        [JsonProperty("navUrl")]
        public string NavUrl { get; set; }

        /// <summary>
        /// Resolved snippet language.
        /// </summary>
        [JsonProperty("language")]
        public string Language { get; set; }

        /// <summary>
        /// Examples sorted by type token, then by position within each type token. Capped at 'limit'.
        /// </summary>
        [JsonProperty("examples")]
        public System.Collections.Generic.List<RegistryExample> Examples { get; set; }

        /// <summary>
        /// Total examples matching the query before 'limit' was applied.
        /// </summary>
        [JsonProperty("totalCount")]
        public long TotalCount { get; set; }
    }
}
