// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class GetStackResourceResponse {
        /// <summary>
        /// The resource information
        /// </summary>
        [JsonProperty("resource")]
        public ResourceInfo Resource { get; set; }

        /// <summary>
        /// The cloud region where the resource is deployed
        /// </summary>
        [JsonProperty("region")]
        public string Region { get; set; }

        /// <summary>
        /// The update version number
        /// </summary>
        [JsonProperty("version")]
        public long Version { get; set; }
    }
}
