// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class GetTemplateConfigurationResponse {
        /// <summary>
        /// The template destination configuration
        /// </summary>
        [JsonProperty("destination")]
        public TemplateDestination Destination { get; set; }
    }
}
