// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class GraphSchemaEdgeType {
        /// <summary>
        /// The edge type name, usable in traverse[].edgeTypes.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// The node type at the edge's source.
        /// </summary>
        [JsonProperty("from")]
        public GraphNodeType From { get; set; }

        /// <summary>
        /// The node type at the edge's destination.
        /// </summary>
        [JsonProperty("to")]
        public GraphNodeType To { get; set; }

        /// <summary>
        /// What the presence of this edge asserts about the two nodes it connects, and which end is which.
        /// </summary>
        [JsonProperty("asserts")]
        public string Asserts { get; set; }

        /// <summary>
        /// Whether this edge type is walked in exactly one hop. A traverse step naming one must leave depth unset or set depth.max to 1.
        /// </summary>
        [JsonProperty("singleHop")]
        public bool SingleHop { get; set; }

        /// <summary>
        /// The traversal directions this edge type can be walked in, listed in the order 'in', 'out', 'both'. A traverse step naming a direction absent from this list is rejected.
        /// </summary>
        [JsonProperty("directions")]
        public System.Collections.Generic.List<GraphTraverseDirection> Directions { get; set; }
    }
}
