// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Pulumi.Cloud.Sdk.Models {
    public enum InsightsAccountPermission : long {
        /// <summary>
        /// InsightsAccountPermissionNone provides no access.
        /// </summary>
        None = 0,

        /// <summary>
        /// InsightsAccountPermissionRead provides read-only access.
        /// </summary>
        Read = 1,

        /// <summary>
        /// InsightsAccountPermissionWrite provides read/write access to an account.
        /// </summary>
        Write = 2,

        /// <summary>
        /// InsightsAccountPermissionAdmin provides admin-level access to the account.
        /// </summary>
        Admin = 3,
    }
}
