// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Pulumi.Cloud.Sdk.Models {
    [JsonConverter(typeof(StringEnumConverter))]
    public enum InsightsAccountProvider {
        /// <summary>
        /// Amazon Web Services provider.
        /// </summary>
        [EnumMember(Value = "aws")]
        Aws,

        /// <summary>
        /// Google Cloud Platform provider.
        /// </summary>
        [EnumMember(Value = "gcp")]
        Gcp,

        /// <summary>
        /// Azure Native provider.
        /// </summary>
        [EnumMember(Value = "azure-native")]
        AzureNative,

        /// <summary>
        /// Oracle Cloud Infrastructure provider.
        /// </summary>
        [EnumMember(Value = "oci")]
        Oci,

        /// <summary>
        /// Kubernetes provider.
        /// </summary>
        [EnumMember(Value = "kubernetes")]
        Kubernetes,
    }
}
