// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class ListOrganizationInvitesResponse {
        /// <summary>
        /// The list of pending organization invites
        /// </summary>
        [JsonProperty("invites")]
        public System.Collections.Generic.List<PendingOrganizationInvite> Invites { get; set; }
    }
}
