// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class ListDeploymentResponseV2 {
        /// <summary>
        /// The list of deployment snapshots
        /// </summary>
        [JsonProperty("deployments")]
        public System.Collections.Generic.List<ListDeploymentSnapshot> Deployments { get; set; }

        /// <summary>
        /// The number of items per page
        /// </summary>
        [JsonProperty("itemsPerPage")]
        public long ItemsPerPage { get; set; }

        /// <summary>
        /// The total number of deployments
        /// </summary>
        [JsonProperty("total")]
        public long Total { get; set; }
    }
}
