// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class ListAgentTaskEventsResponse {
        /// <summary>
        /// Events contains the list of events for this page.
        /// </summary>
        [JsonProperty("events")]
        public System.Collections.Generic.List<AgentConsoleEvent> Events { get; set; }

        /// <summary>
        /// ContinuationToken can be used to fetch the next page of results. If null, there are no more results available.
        /// </summary>
        [JsonProperty("continuationToken")]
        public string ContinuationToken { get; set; }
    }
}
