// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class ListResourcesWithReferencesRequest {
        /// <summary>
        /// The resource identifiers to look up
        /// </summary>
        [JsonProperty("resourceIdentifiers")]
        public System.Collections.Generic.List<InsightsResourceIdentifier> ResourceIdentifiers { get; set; }

        /// <summary>
        /// The depth of references to traverse
        /// </summary>
        [JsonProperty("depth")]
        public long Depth { get; set; }
    }
}
