// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class ListDeploymentResponse {
        /// <summary>
        /// Unique identifier for this deployment.
        /// </summary>
        [JsonProperty("id")]
        public string ID { get; set; }

        /// <summary>
        /// Created defines when the Deployment was created.
        /// </summary>
        [JsonProperty("created")]
        public string Created { get; set; }

        /// <summary>
        /// Created defines when the corresponding WorkflowRun was modified.
        /// </summary>
        [JsonProperty("modified")]
        public string Modified { get; set; }

        /// <summary>
        /// Status is the current status of the workflow runID.
        /// </summary>
        [JsonProperty("status")]
        public JobStatus Status { get; set; }

        /// <summary>
        /// Version is the ordinal ID for the stack
        /// </summary>
        [JsonProperty("version")]
        public long Version { get; set; }

        /// <summary>
        /// RequestedBy contains the user information about the user who created the Deployment
        /// </summary>
        [JsonProperty("requestedBy")]
        public UserInfo RequestedBy { get; set; }
    }
}
