// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class ListPolicyIssuesResponse {
        /// <summary>
        /// The list of policy issues
        /// </summary>
        [JsonProperty("policyIssues")]
        public System.Collections.Generic.List<PolicyIssue> PolicyIssues { get; set; }

        /// <summary>
        /// Grouped data for policy issue aggregation
        /// </summary>
        [JsonProperty("groupData")]
        public System.Collections.Generic.List<System.Collections.Generic.Dictionary<string, JToken>> GroupData { get; set; }

        /// <summary>
        /// The total number of policy issue rows
        /// </summary>
        [JsonProperty("rowCount")]
        public long? RowCount { get; set; }
    }
}
