// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class OperationContextOptionsRequest {
        /// <summary>
        /// Whether to skip the default dependency installation step.
        /// </summary>
        [JsonProperty("skipInstallDependencies")]
        public bool SkipInstallDependencies { get; set; }

        /// <summary>
        /// Whether to skip queued intermediate deployments.
        /// </summary>
        [JsonProperty("skipIntermediateDeployments")]
        public bool SkipIntermediateDeployments { get; set; }

        /// <summary>
        /// The shell to use when running commands.
        /// </summary>
        [JsonProperty("shell")]
        public string Shell { get; set; }

        /// <summary>
        /// Whether the stack should be deleted after it is destroyed.
        /// </summary>
        [JsonProperty("deleteAfterDestroy")]
        public bool DeleteAfterDestroy { get; set; }

        /// <summary>
        /// Whether a detect-drift operation should be followed by a remediate-drift step if drift is detected.
        /// </summary>
        [JsonProperty("remediateIfDriftDetected")]
        public bool RemediateIfDriftDetected { get; set; }
    }
}
