// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    [JsonSubTypeName("PermissionExpressionHasTag")]
    public class PermissionExpressionHasTag : PermissionBooleanExpressionUnary {
        /// <summary>
        /// The context expression to check for the tag.
        /// </summary>
        [JsonProperty("context")]
        public PermissionContextExpression Context { get; set; }

        /// <summary>
        /// The tag key to check for.
        /// </summary>
        [JsonProperty("key")]
        public string Key { get; set; }
    }
}
