// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class PublishTemplateVersionCompleteRequest {
        /// <summary>
        /// The identifier of the publish operation to complete.
        /// </summary>
        [JsonProperty("operationID")]
        public string OperationID { get; set; }
    }
}
