// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class RegistryDocsSupportingType {
        /// <summary>
        /// Pulumi type token of this type.
        /// </summary>
        [JsonProperty("typeToken")]
        public string TypeToken { get; set; }

        /// <summary>
        /// Display name keyed by language.
        /// </summary>
        [JsonProperty("name")]
        public System.Collections.Generic.Dictionary<string, string> Name { get; set; }

        /// <summary>
        /// 'object' or 'enum'.
        /// </summary>
        [JsonProperty("kind")]
        public string Kind { get; set; }

        /// <summary>
        /// Properties (when kind is 'object').
        /// </summary>
        [JsonProperty("properties")]
        public System.Collections.Generic.List<RegistryDocsProperty> Properties { get; set; }

        /// <summary>
        /// Enum values (when kind is 'enum').
        /// </summary>
        [JsonProperty("values")]
        public System.Collections.Generic.List<RegistryDocsEnumValue> Values { get; set; }
    }
}
