// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class ResourceInfo {
        /// <summary>
        /// The underlying resource with its properties, URN, type, and provider state.
        /// </summary>
        [JsonProperty("resource")]
        public Resource Resource { get; set; }
    }
}
