// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class ResourceMigrationAnnotation {
        /// <summary>
        /// Free-text note about this resource's migration status. May be empty when only a status override is set.
        /// </summary>
        [JsonProperty("note")]
        public string Note { get; set; }

        /// <summary>
        /// User override of the computed migration status. Only Migrated is a valid override.
        /// </summary>
        [JsonProperty("statusOverride")]
        public MigrationStatus StatusOverride { get; set; }

        /// <summary>
        /// URN of the resource this one was migrated as part of.
        /// </summary>
        [JsonProperty("linkedResourceUrn")]
        public string LinkedResourceUrn { get; set; }
    }
}
