// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Pulumi.Cloud.Sdk.Models {
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ScanSchedule {
        /// <summary>
        /// No automated scanning is configured.
        /// </summary>
        [EnumMember(Value = "none")]
        None,

        /// <summary>
        /// Scans run automatically every 12 hours.
        /// </summary>
        [EnumMember(Value = "12h")]
        TwelveHours,

        /// <summary>
        /// Scans run automatically on a daily schedule.
        /// </summary>
        [EnumMember(Value = "daily")]
        Daily,
    }
}
