// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class SecretRotationEvent {
        /// <summary>
        /// The unique identifier for this rotation event.
        /// </summary>
        [JsonProperty("id")]
        public string ID { get; set; }

        /// <summary>
        /// The ID of the environment being rotated.
        /// </summary>
        [JsonProperty("environmentId")]
        public string EnvironmentID { get; set; }

        /// <summary>
        /// The timestamp when this rotation event was created.
        /// </summary>
        [JsonProperty("created")]
        public DateTimeOffset Created { get; set; }

        /// <summary>
        /// The environment revision before the rotation.
        /// </summary>
        [JsonProperty("preRotationRevision")]
        public long PreRotationRevision { get; set; }

        /// <summary>
        /// The environment revision after the rotation, if completed.
        /// </summary>
        [JsonProperty("postRotationRevision")]
        public long? PostRotationRevision { get; set; }

        /// <summary>
        /// The ID of the user who initiated the rotation.
        /// </summary>
        [JsonProperty("userID")]
        public string UserID { get; set; }

        /// <summary>
        /// The timestamp when the rotation completed.
        /// </summary>
        [JsonProperty("completed")]
        public DateTimeOffset? Completed { get; set; }

        /// <summary>
        /// The current status of the rotation event.
        /// </summary>
        [JsonProperty("status")]
        public string Status { get; set; }

        /// <summary>
        /// The ID of the scheduled action that triggered this rotation, if any.
        /// </summary>
        [JsonProperty("scheduledActionID")]
        public string ScheduledActionID { get; set; }

        /// <summary>
        /// An error message if the rotation failed.
        /// </summary>
        [JsonProperty("errorMessage")]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// The individual secret rotations within this event.
        /// </summary>
        [JsonProperty("rotations")]
        public System.Collections.Generic.List<SecretRotation> Rotations { get; set; }
    }
}
