// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class SubmitChangeRequestRequest {
        /// <summary>
        /// Description/justification for the change request
        /// </summary>
        [JsonProperty("description")]
        public string Description { get; set; }
    }
}
