// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    [JsonConverter(typeof(PolymorphicConverter))]
    [JsonDiscriminator("entityType")]
    [JsonSubType(typeof(TargetEntity.Environment))]
    public abstract class TargetEntity {

        [JsonSubTypeName("environment")]
        public class Environment : TargetEntity {
            /// <summary>
            /// The project name
            /// </summary>
            [JsonProperty("project")]
            public string Project { get; set; }

            /// <summary>
            /// The environment name
            /// </summary>
            [JsonProperty("name")]
            public string Name { get; set; }
        }
    }
}
