// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class TemplateUploadURLs {
        /// <summary>
        /// The pre-signed URL for uploading the template archive.
        /// </summary>
        [JsonProperty("archive")]
        public string Archive { get; set; }
    }
}
