// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class TransferAllStacksRequest {
        /// <summary>
        /// The source organization to transfer stacks from. Must match the organization in the URL route.
        /// </summary>
        [JsonProperty("fromOrg")]
        public string FromOrg { get; set; }

        /// <summary>
        /// The destination organization to transfer stacks to.
        /// </summary>
        [JsonProperty("toOrg")]
        public string ToOrg { get; set; }
    }
}
