// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pulumi.Cloud.Sdk.Models {
    public class UpdateTeamInsightsAccountPermissionsRequest {
        /// <summary>
        /// Permissions the permissions that team membership grants to the account. Will overwrite any existing permissions the team grants to the account. A nil value, or a permission of "none", will remove the account from the team.
        /// </summary>
        [JsonProperty("permissions")]
        public InsightsAccountPermission? Permissions { get; set; }
    }
}
