// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.api;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.pulumi.cloud.sdk.ApiClient;
import com.pulumi.cloud.sdk.ApiRequest;
import com.pulumi.cloud.sdk.model.*;

public final class InsightsApi {
    private final ApiClient client;

    public InsightsApi(ApiClient client) {
        this.client = client;
    }

    public void acceptInsightsBilling(String orgName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling acceptInsightsBilling");
        }
        ApiRequest $request = new ApiRequest("PUT", "/api/preview/insights/{orgName}/insightstrial/accept");
        $request.pathParam("orgName", orgName);
        this.client.call($request);
    }

    public BulkCreateInsightsAccountsResponse bulkCreateAccounts(String orgName, BulkCreateInsightsAccountsRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling bulkCreateAccounts");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling bulkCreateAccounts");
        }
        ApiRequest $request = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts");
        $request.pathParam("orgName", orgName);
        $request.body(request);
        $request.consumes("application/json");
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<BulkCreateInsightsAccountsResponse>() {});
    }

    public void cancelScan(String orgName, String accountName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling cancelScan");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling cancelScan");
        }
        ApiRequest $request = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/scan/cancel");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        this.client.call($request);
    }

    public void createAccount(String orgName, String accountName, CreateInsightsAccountRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling createAccount");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling createAccount");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling createAccount");
        }
        ApiRequest $request = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.body(request);
        $request.consumes("application/json");
        this.client.call($request);
    }

    public void deleteAccount(String orgName, String accountName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling deleteAccount");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling deleteAccount");
        }
        ApiRequest $request = new ApiRequest("DELETE", "/api/preview/insights/{orgName}/accounts/{accountName}");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        this.client.call($request);
    }

    public void deleteResourceMigrationAnnotation(String orgName, String projectName, String stackName, String resourceUrn) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling deleteResourceMigrationAnnotation");
        }
        if (projectName == null) {
            throw new IllegalArgumentException("Missing required parameter 'projectName' when calling deleteResourceMigrationAnnotation");
        }
        if (stackName == null) {
            throw new IllegalArgumentException("Missing required parameter 'stackName' when calling deleteResourceMigrationAnnotation");
        }
        if (resourceUrn == null) {
            throw new IllegalArgumentException("Missing required parameter 'resourceUrn' when calling deleteResourceMigrationAnnotation");
        }
        ApiRequest $request = new ApiRequest("DELETE", "/api/preview/insights/{orgName}/discovered-stacks/{projectName}/{stackName}/migration");
        $request.pathParam("orgName", orgName);
        $request.pathParam("projectName", projectName);
        $request.pathParam("stackName", stackName);
        $request.queryParam("resourceUrn", resourceUrn);
        this.client.call($request);
    }

    public InsightsImportCodeResponse generateImportCode(String orgName, InsightsImportCodeRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling generateImportCode");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling generateImportCode");
        }
        ApiRequest $request = new ApiRequest("POST", "/api/preview/insights/{orgName}/import/code/generate");
        $request.pathParam("orgName", orgName);
        $request.body(request);
        $request.consumes("application/json");
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<InsightsImportCodeResponse>() {});
    }

    public GetDiscoveredProjectResponse getDiscoveredProject(String orgName, String projectName, String continuationToken) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling getDiscoveredProject");
        }
        if (projectName == null) {
            throw new IllegalArgumentException("Missing required parameter 'projectName' when calling getDiscoveredProject");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/discovered-stacks/{projectName}");
        $request.pathParam("orgName", orgName);
        $request.pathParam("projectName", projectName);
        $request.queryParam("continuationToken", continuationToken);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<GetDiscoveredProjectResponse>() {});
    }

    public GetDiscoveredStackResponse getDiscoveredStack(String orgName, String projectName, String stackName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling getDiscoveredStack");
        }
        if (projectName == null) {
            throw new IllegalArgumentException("Missing required parameter 'projectName' when calling getDiscoveredStack");
        }
        if (stackName == null) {
            throw new IllegalArgumentException("Missing required parameter 'stackName' when calling getDiscoveredStack");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/discovered-stacks/{projectName}/{stackName}");
        $request.pathParam("orgName", orgName);
        $request.pathParam("projectName", projectName);
        $request.pathParam("stackName", stackName);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<GetDiscoveredStackResponse>() {});
    }

    public GraphSchemaResponse getGraphQuerySchema() {
        ApiRequest $request = new ApiRequest("GET", "/api/insights/graph/schema");
        $request.produces("application/json");
        $request.produces("text/markdown");
        return this.client.call($request, new TypeReference<GraphSchemaResponse>() {});
    }

    public GraphSchemaResponse getGraphSchema(String orgName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling getGraphSchema");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/insights/{orgName}/graph/schema");
        $request.pathParam("orgName", orgName);
        $request.produces("application/json");
        $request.produces("text/markdown");
        return this.client.call($request, new TypeReference<GraphSchemaResponse>() {});
    }

    public GetInsightAccountTagsResponse getInsightAccountTags(String orgName, String accountName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling getInsightAccountTags");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling getInsightAccountTags");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/tags");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<GetInsightAccountTagsResponse>() {});
    }

    public TrialUsageSummary getInsightsTrialSummary(String orgName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling getInsightsTrialSummary");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/insightstrial/summary");
        $request.pathParam("orgName", orgName);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<TrialUsageSummary>() {});
    }

    public ScanStatus getScan(String orgName, String accountName, String scanId) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling getScan");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling getScan");
        }
        if (scanId == null) {
            throw new IllegalArgumentException("Missing required parameter 'scanId' when calling getScan");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/scans/{scanId}");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.pathParam("scanId", scanId);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ScanStatus>() {});
    }

    public DeploymentLogsBase getScanLogs(String orgName, String accountName, String scanId, String continuationToken, Long count, Long job, Long offset, Long step) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling getScanLogs");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling getScanLogs");
        }
        if (scanId == null) {
            throw new IllegalArgumentException("Missing required parameter 'scanId' when calling getScanLogs");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/scans/{scanId}/logs");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.pathParam("scanId", scanId);
        $request.queryParam("continuationToken", continuationToken);
        $request.queryParam("count", count);
        $request.queryParam("job", job);
        $request.queryParam("offset", offset);
        $request.queryParam("step", step);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<DeploymentLogsBase>() {});
    }

    public ListDiscoveredStackResourcesResponse getStackMigration(String orgName, String projectName, String stackName, String compareTo) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling getStackMigration");
        }
        if (projectName == null) {
            throw new IllegalArgumentException("Missing required parameter 'projectName' when calling getStackMigration");
        }
        if (stackName == null) {
            throw new IllegalArgumentException("Missing required parameter 'stackName' when calling getStackMigration");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/stacks/{projectName}/{stackName}/migration");
        $request.pathParam("orgName", orgName);
        $request.pathParam("projectName", projectName);
        $request.pathParam("stackName", stackName);
        $request.queryParam("compareTo", compareTo);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ListDiscoveredStackResourcesResponse>() {});
    }

    public GetResourceCountSummaryResponse getUsageSummaryInsightsScans(String orgName, UsageSummaryTimeUnit granularity, Long lookbackDays, Long lookbackStart) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling getUsageSummaryInsightsScans");
        }
        if (granularity == null) {
            throw new IllegalArgumentException("Missing required parameter 'granularity' when calling getUsageSummaryInsightsScans");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/orgs/{orgName}/insights-scans/summary");
        $request.pathParam("orgName", orgName);
        $request.queryParam("granularity", granularity);
        $request.queryParam("lookbackDays", lookbackDays);
        $request.queryParam("lookbackStart", lookbackStart);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<GetResourceCountSummaryResponse>() {});
    }

    public GraphQueryResponse graphQuery(String orgName, GraphQueryRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling graphQuery");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling graphQuery");
        }
        ApiRequest $request = new ApiRequest("POST", "/api/insights/{orgName}/graph/query");
        $request.pathParam("orgName", orgName);
        $request.body(request);
        $request.consumes("application/json");
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<GraphQueryResponse>() {});
    }

    public void headAccount(String orgName, String accountName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling headAccount");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling headAccount");
        }
        ApiRequest $request = new ApiRequest("HEAD", "/api/preview/insights/{orgName}/accounts/{accountName}");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        this.client.call($request);
    }

    public ListInsightsAccountsResponse listAccounts(String orgName, String continuationToken, Long count, String parent, String roleID) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling listAccounts");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts");
        $request.pathParam("orgName", orgName);
        $request.queryParam("continuationToken", continuationToken);
        $request.queryParam("count", count);
        $request.queryParam("parent", parent);
        $request.queryParam("roleID", roleID);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ListInsightsAccountsResponse>() {});
    }

    public ListDiscoveredStackResourcesResponse listDiscoveredStackResources(String orgName, String projectName, String stackName, String compareTo) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling listDiscoveredStackResources");
        }
        if (projectName == null) {
            throw new IllegalArgumentException("Missing required parameter 'projectName' when calling listDiscoveredStackResources");
        }
        if (stackName == null) {
            throw new IllegalArgumentException("Missing required parameter 'stackName' when calling listDiscoveredStackResources");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/discovered-stacks/{projectName}/{stackName}/resources");
        $request.pathParam("orgName", orgName);
        $request.pathParam("projectName", projectName);
        $request.pathParam("stackName", stackName);
        $request.queryParam("compareTo", compareTo);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ListDiscoveredStackResourcesResponse>() {});
    }

    public ListTeamsByInsightsAccountResponse listInsightsAccountTeams(String orgName, String accountName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling listInsightsAccountTeams");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling listInsightsAccountTeams");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/teams");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ListTeamsByInsightsAccountResponse>() {});
    }

    public ListPolicyPacksForInsightsAccountResponse listPolicyPacksForAccount(String orgName, String accountName, String continuationToken) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling listPolicyPacksForAccount");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling listPolicyPacksForAccount");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/policy/packs");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.queryParam("continuationToken", continuationToken);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ListPolicyPacksForInsightsAccountResponse>() {});
    }

    public ListInsightsResourceStackEdgesResponse listResourceStackEdges(String orgName, String accountName, String resourceTypeAndId) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling listResourceStackEdges");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling listResourceStackEdges");
        }
        if (resourceTypeAndId == null) {
            throw new IllegalArgumentException("Missing required parameter 'resourceTypeAndId' when calling listResourceStackEdges");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/stack_edges");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.pathParam("resourceTypeAndId", resourceTypeAndId);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ListInsightsResourceStackEdgesResponse>() {});
    }

    public ListInsightsResourceVersionEdgesResponse listResourceVersionEdges(String orgName, String accountName, String resourceTypeAndId, String continuationToken, Long count) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling listResourceVersionEdges");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling listResourceVersionEdges");
        }
        if (resourceTypeAndId == null) {
            throw new IllegalArgumentException("Missing required parameter 'resourceTypeAndId' when calling listResourceVersionEdges");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/edges");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.pathParam("resourceTypeAndId", resourceTypeAndId);
        $request.queryParam("continuationToken", continuationToken);
        $request.queryParam("count", count);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ListInsightsResourceVersionEdgesResponse>() {});
    }

    public ListInsightsResourceVersionEdgesResponse listResourceVersionEdges_versions(String orgName, String accountName, String resourceTypeAndId, Long resourceVersion, String continuationToken, Long count) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling listResourceVersionEdges_versions");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling listResourceVersionEdges_versions");
        }
        if (resourceTypeAndId == null) {
            throw new IllegalArgumentException("Missing required parameter 'resourceTypeAndId' when calling listResourceVersionEdges_versions");
        }
        if (resourceVersion == null) {
            throw new IllegalArgumentException("Missing required parameter 'resourceVersion' when calling listResourceVersionEdges_versions");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/versions/{resourceVersion}/edges");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.pathParam("resourceTypeAndId", resourceTypeAndId);
        $request.pathParam("resourceVersion", resourceVersion);
        $request.queryParam("continuationToken", continuationToken);
        $request.queryParam("count", count);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ListInsightsResourceVersionEdgesResponse>() {});
    }

    public ListInsightsResourceVersionsResponse listResourceVersions(String orgName, String accountName, String resourceTypeAndId, String continuationToken, Long count) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling listResourceVersions");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling listResourceVersions");
        }
        if (resourceTypeAndId == null) {
            throw new IllegalArgumentException("Missing required parameter 'resourceTypeAndId' when calling listResourceVersions");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/versions");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.pathParam("resourceTypeAndId", resourceTypeAndId);
        $request.queryParam("continuationToken", continuationToken);
        $request.queryParam("count", count);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ListInsightsResourceVersionsResponse>() {});
    }

    public List<InsightsResourceWithReferences> listResourcesWithReferences(String orgName, String accountName, ListResourcesWithReferencesRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling listResourcesWithReferences");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling listResourcesWithReferences");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling listResourcesWithReferences");
        }
        ApiRequest $request = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/references");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.body(request);
        $request.consumes("application/json");
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<List<InsightsResourceWithReferences>>() {});
    }

    public ListScanStatusResponse listScanStatus(String orgName, String accountName, String continuationToken, Long pageSize) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling listScanStatus");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling listScanStatus");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/scans");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.queryParam("continuationToken", continuationToken);
        $request.queryParam("pageSize", pageSize);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ListScanStatusResponse>() {});
    }

    public void pauseScheduledScans(String orgName, String accountName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling pauseScheduledScans");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling pauseScheduledScans");
        }
        ApiRequest $request = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/scan/pause");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        this.client.call($request);
    }

    public ReadInsightsAccountResponse readAccount(String orgName, String accountName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling readAccount");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling readAccount");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ReadInsightsAccountResponse>() {});
    }

    public InsightsResourceWithVersion readResource(String orgName, String accountName, String resourceTypeAndId) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling readResource");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling readResource");
        }
        if (resourceTypeAndId == null) {
            throw new IllegalArgumentException("Missing required parameter 'resourceTypeAndId' when calling readResource");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.pathParam("resourceTypeAndId", resourceTypeAndId);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<InsightsResourceWithVersion>() {});
    }

    public InsightsResourceWithReferences readResourceWithReferences(String orgName, String accountName, String resourceTypeAndId) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling readResourceWithReferences");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling readResourceWithReferences");
        }
        if (resourceTypeAndId == null) {
            throw new IllegalArgumentException("Missing required parameter 'resourceTypeAndId' when calling readResourceWithReferences");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/references");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.pathParam("resourceTypeAndId", resourceTypeAndId);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<InsightsResourceWithReferences>() {});
    }

    public InsightsResourceWithVersion readResource_versions(String orgName, String accountName, String resourceTypeAndId, String resourceVersion) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling readResource_versions");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling readResource_versions");
        }
        if (resourceTypeAndId == null) {
            throw new IllegalArgumentException("Missing required parameter 'resourceTypeAndId' when calling readResource_versions");
        }
        if (resourceVersion == null) {
            throw new IllegalArgumentException("Missing required parameter 'resourceVersion' when calling readResource_versions");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/versions/{resourceVersion}");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.pathParam("resourceTypeAndId", resourceTypeAndId);
        $request.pathParam("resourceVersion", resourceVersion);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<InsightsResourceWithVersion>() {});
    }

    public ScanStatusResponse readScanStatus(String orgName, String accountName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling readScanStatus");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling readScanStatus");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/scan");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ScanStatusResponse>() {});
    }

    public ScheduledInsightsScanSettingsResponse readScheduledScanSettings(String orgName, String accountName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling readScheduledScanSettings");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling readScheduledScanSettings");
        }
        ApiRequest $request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/scan/settings");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ScheduledInsightsScanSettingsResponse>() {});
    }

    public UserInfo reassignAccountOwnership(String orgName, String accountName, UserInfo request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling reassignAccountOwnership");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling reassignAccountOwnership");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling reassignAccountOwnership");
        }
        ApiRequest $request = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/ownership");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.body(request);
        $request.consumes("application/json");
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<UserInfo>() {});
    }

    public void resumeScheduledScans(String orgName, String accountName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling resumeScheduledScans");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling resumeScheduledScans");
        }
        ApiRequest $request = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/scan/resume");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        this.client.call($request);
    }

    public WorkflowRun scanAccount(String orgName, String accountName, ScanInsightsAccountRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling scanAccount");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling scanAccount");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling scanAccount");
        }
        ApiRequest $request = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/scan");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.body(request);
        $request.consumes("application/json");
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<WorkflowRun>() {});
    }

    public ListOrganizationProjectsResponsev3 searchStacks(String orgName, AngularGridGetRowsRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling searchStacks");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling searchStacks");
        }
        ApiRequest $request = new ApiRequest("POST", "/api/console/orgs/{orgName}/stacks/search");
        $request.pathParam("orgName", orgName);
        $request.body(request);
        $request.consumes("application/json");
        $request.produces("application/json");
        return this.client.call($request, new TypeReference<ListOrganizationProjectsResponsev3>() {});
    }

    public void setInsightAccountTags(String orgName, String accountName, SetInsightAccountTagsRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling setInsightAccountTags");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling setInsightAccountTags");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling setInsightAccountTags");
        }
        ApiRequest $request = new ApiRequest("PUT", "/api/preview/insights/{orgName}/accounts/{accountName}/tags");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.body(request);
        $request.consumes("application/json");
        this.client.call($request);
    }

    public void terminateInsightsTrial(String orgName) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling terminateInsightsTrial");
        }
        ApiRequest $request = new ApiRequest("PUT", "/api/preview/insights/{orgName}/insightstrial/deny");
        $request.pathParam("orgName", orgName);
        this.client.call($request);
    }

    public void updateAccount(String orgName, String accountName, UpdateInsightsAccountRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling updateAccount");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling updateAccount");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling updateAccount");
        }
        ApiRequest $request = new ApiRequest("PATCH", "/api/preview/insights/{orgName}/accounts/{accountName}");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.body(request);
        $request.consumes("application/json");
        this.client.call($request);
    }

    public void updateResourceVersionPolicyResults(String orgName, String accountName, String resourceTypeAndId, String resourceVersion, UpdateInsightsResourceVersionPolicyResultsRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling updateResourceVersionPolicyResults");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling updateResourceVersionPolicyResults");
        }
        if (resourceTypeAndId == null) {
            throw new IllegalArgumentException("Missing required parameter 'resourceTypeAndId' when calling updateResourceVersionPolicyResults");
        }
        if (resourceVersion == null) {
            throw new IllegalArgumentException("Missing required parameter 'resourceVersion' when calling updateResourceVersionPolicyResults");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling updateResourceVersionPolicyResults");
        }
        ApiRequest $request = new ApiRequest("PUT", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/versions/{resourceVersion}/policy/results");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.pathParam("resourceTypeAndId", resourceTypeAndId);
        $request.pathParam("resourceVersion", resourceVersion);
        $request.body(request);
        $request.consumes("application/json");
        this.client.call($request);
    }

    public void updateScheduledScanSettings(String orgName, String accountName, ScheduledInsightsScanSettingsRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling updateScheduledScanSettings");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling updateScheduledScanSettings");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling updateScheduledScanSettings");
        }
        ApiRequest $request = new ApiRequest("PUT", "/api/preview/insights/{orgName}/accounts/{accountName}/scan/settings");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.body(request);
        $request.consumes("application/json");
        this.client.call($request);
    }

    public void updateStackPolicyResults(String orgName, String projectName, String stackName, Long version, UpdateStackPolicyResultsRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling updateStackPolicyResults");
        }
        if (projectName == null) {
            throw new IllegalArgumentException("Missing required parameter 'projectName' when calling updateStackPolicyResults");
        }
        if (stackName == null) {
            throw new IllegalArgumentException("Missing required parameter 'stackName' when calling updateStackPolicyResults");
        }
        if (version == null) {
            throw new IllegalArgumentException("Missing required parameter 'version' when calling updateStackPolicyResults");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling updateStackPolicyResults");
        }
        ApiRequest $request = new ApiRequest("PUT", "/api/preview/insights/{orgName}/policy/stacks/{projectName}/{stackName}/updates/{version}/results");
        $request.pathParam("orgName", orgName);
        $request.pathParam("projectName", projectName);
        $request.pathParam("stackName", stackName);
        $request.pathParam("version", version);
        $request.body(request);
        $request.consumes("application/json");
        this.client.call($request);
    }

    public void updateTeamInsightsAccountPermissions(String orgName, String accountName, String teamName, UpdateTeamInsightsAccountPermissionsRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling updateTeamInsightsAccountPermissions");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling updateTeamInsightsAccountPermissions");
        }
        if (teamName == null) {
            throw new IllegalArgumentException("Missing required parameter 'teamName' when calling updateTeamInsightsAccountPermissions");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling updateTeamInsightsAccountPermissions");
        }
        ApiRequest $request = new ApiRequest("PATCH", "/api/preview/insights/{orgName}/accounts/{accountName}/teams/{teamName}");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.pathParam("teamName", teamName);
        $request.body(request);
        $request.consumes("application/json");
        this.client.call($request);
    }

    public void upsertResourceMigrationAnnotation(String orgName, String projectName, String stackName, UpsertResourceMigrationAnnotationRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling upsertResourceMigrationAnnotation");
        }
        if (projectName == null) {
            throw new IllegalArgumentException("Missing required parameter 'projectName' when calling upsertResourceMigrationAnnotation");
        }
        if (stackName == null) {
            throw new IllegalArgumentException("Missing required parameter 'stackName' when calling upsertResourceMigrationAnnotation");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling upsertResourceMigrationAnnotation");
        }
        ApiRequest $request = new ApiRequest("PUT", "/api/preview/insights/{orgName}/discovered-stacks/{projectName}/{stackName}/migration");
        $request.pathParam("orgName", orgName);
        $request.pathParam("projectName", projectName);
        $request.pathParam("stackName", stackName);
        $request.body(request);
        $request.consumes("application/json");
        this.client.call($request);
    }

    public void upsertResources(String orgName, String accountName, UpsertInsightsResourcesRequest request) {
        if (orgName == null) {
            throw new IllegalArgumentException("Missing required parameter 'orgName' when calling upsertResources");
        }
        if (accountName == null) {
            throw new IllegalArgumentException("Missing required parameter 'accountName' when calling upsertResources");
        }
        if (request == null) {
            throw new IllegalArgumentException("Missing required parameter 'request' when calling upsertResources");
        }
        ApiRequest $request = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/resources");
        $request.pathParam("orgName", orgName);
        $request.pathParam("accountName", accountName);
        $request.body(request);
        $request.consumes("application/json");
        this.client.call($request);
    }
}
