# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class AgentSignupRequest(PulumiAutoModelEncoder):
    """
    :var challenge_i_d: str - declared
    :var challenge_result: str - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'challenge_i_d': 'str',
        'challenge_result': 'str',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'challenge_i_d': 'challengeID',
        'challenge_result': 'challengeResult',
    }

    FIELDS_challenge_i_d = 'challengeID'
    FIELDS_challenge_result = 'challengeResult'

    _challenge_i_d: 'str'
    _challenge_result: 'str'

    def __init__(
        self,
        challenge_i_d: 'str',
        challenge_result: 'str',
    ) -> None:
        super().__init__()

        self.challenge_i_d = challenge_i_d
        self.challenge_result = challenge_result

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, AgentSignupRequest):
            self._challenge_i_d = source._challenge_i_d
            self._challenge_result = source._challenge_result

    @property
    def challenge_i_d(self) -> 'str':
        return self._challenge_i_d

    @challenge_i_d.setter
    def challenge_i_d(self, challenge_i_d: 'str'):
        if challenge_i_d is None:
            raise ValueError("Invalid value for `challenge_i_d`, must not be `None`")

        self._challenge_i_d = challenge_i_d

    @property
    def challenge_result(self) -> 'str':
        return self._challenge_result

    @challenge_result.setter
    def challenge_result(self, challenge_result: 'str'):
        if challenge_result is None:
            raise ValueError("Invalid value for `challenge_result`, must not be `None`")

        self._challenge_result = challenge_result

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, AgentSignupRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
