# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class AngularGridAdvancedFilterModel(PulumiAutoModelEncoder):
    """
    :var type: str - declared
    :var conditions: list[AngularGridFilterModel] - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'type': 'str',
        'conditions': 'list[AngularGridFilterModel]',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'type': 'type',
        'conditions': 'conditions',
    }

    FIELDS_type = 'type'
    FIELDS_conditions = 'conditions'

    _type: 'str'
    _conditions: 'list[AngularGridFilterModel]'

    def __init__(
        self,
        type: 'str',
        conditions: 'list[AngularGridFilterModel]',
    ) -> None:
        super().__init__()

        self.type = type
        self.conditions = conditions

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, AngularGridAdvancedFilterModel):
            self._type = source._type
            self._conditions = source._conditions

    @property
    def type(self) -> 'str':
        return self._type

    @type.setter
    def type(self, type: 'str'):
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def conditions(self) -> 'list[AngularGridFilterModel]':
        return self._conditions

    @conditions.setter
    def conditions(self, conditions: 'list[AngularGridFilterModel]'):
        if conditions is None:
            raise ValueError("Invalid value for `conditions`, must not be `None`")

        self._conditions = conditions

    @property
    def conditions__autoinit(self) -> 'list[AngularGridFilterModel]':
        """Return ``conditions``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._conditions``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``conditions__safederef`` when you only want to read a default without mutating self.
        """
        if self._conditions is None:
            self._conditions = self.conditions__safederef

        return self._conditions

    @property
    def conditions__safederef(self) -> 'list[AngularGridFilterModel]':
        """Return ``conditions``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``conditions`` stays unset and each
        call returns a new default. Use ``conditions__autoinit`` to persist the default on
        first access.
        """
        if self._conditions is None:
            return []

        return self._conditions

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, AngularGridAdvancedFilterModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
