# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class AppDeploymentV3(PulumiAutoModelEncoder):
    """
    :var manifest: AppManifestV1 - declared
    :var secrets_providers: AppSecretsProvidersV1 - declared
    :var resources: list[AppResourceV3] - declared
    :var pending_operations: list[AppOperationV2] - declared
    :var metadata: AppSnapshotMetadataV1 - declared
    :var snippets: list[AppSnippetV1] - declared
    :var extensions: dict[str, AppExtension] - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'manifest': 'AppManifestV1',
        'secrets_providers': 'AppSecretsProvidersV1',
        'resources': 'list[AppResourceV3]',
        'pending_operations': 'list[AppOperationV2]',
        'metadata': 'AppSnapshotMetadataV1',
        'snippets': 'list[AppSnippetV1]',
        'extensions': 'dict[str, AppExtension]',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'manifest': 'manifest',
        'secrets_providers': 'secrets_providers',
        'resources': 'resources',
        'pending_operations': 'pending_operations',
        'metadata': 'metadata',
        'snippets': 'snippets',
        'extensions': 'extensions',
    }

    FIELDS_manifest = 'manifest'
    FIELDS_secrets_providers = 'secrets_providers'
    FIELDS_resources = 'resources'
    FIELDS_pending_operations = 'pending_operations'
    FIELDS_metadata = 'metadata'
    FIELDS_snippets = 'snippets'
    FIELDS_extensions = 'extensions'

    _manifest: 'AppManifestV1'
    _secrets_providers: 'AppSecretsProvidersV1'
    _resources: 'list[AppResourceV3]'
    _pending_operations: 'list[AppOperationV2]'
    _metadata: 'AppSnapshotMetadataV1'
    _snippets: 'list[AppSnippetV1]'
    _extensions: 'dict[str, AppExtension]'

    def __init__(
        self,
        manifest: 'AppManifestV1',
        secrets_providers: 'AppSecretsProvidersV1' = None,
        resources: 'list[AppResourceV3]' = None,
        pending_operations: 'list[AppOperationV2]' = None,
        metadata: 'AppSnapshotMetadataV1' = None,
        snippets: 'list[AppSnippetV1]' = None,
        extensions: 'dict[str, AppExtension]' = None,
    ) -> None:
        super().__init__()

        self.manifest = manifest
        self.secrets_providers = secrets_providers
        self.resources = resources
        self.pending_operations = pending_operations
        self.metadata = metadata
        self.snippets = snippets
        self.extensions = extensions

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, AppDeploymentV3):
            self._manifest = source._manifest
            self._secrets_providers = source._secrets_providers
            self._resources = source._resources
            self._pending_operations = source._pending_operations
            self._metadata = source._metadata
            self._snippets = source._snippets
            self._extensions = source._extensions

    @property
    def manifest(self) -> 'AppManifestV1':
        return self._manifest

    @manifest.setter
    def manifest(self, manifest: 'AppManifestV1'):
        if manifest is None:
            raise ValueError("Invalid value for `manifest`, must not be `None`")

        self._manifest = manifest

    @property
    def manifest__autoinit(self) -> 'AppManifestV1':
        """Return ``manifest``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._manifest``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``manifest__safederef`` when you only want to read a default without mutating self.
        """
        if self._manifest is None:
            self._manifest = self.manifest__safederef

        return self._manifest

    @property
    def manifest__safederef(self) -> 'AppManifestV1':
        """Return ``manifest``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``manifest`` stays unset and each
        call returns a new default. Use ``manifest__autoinit`` to persist the default on
        first access.
        """
        if self._manifest is None:
            from .. import models
            return models.AppManifestV1._new_empty()

        return self._manifest

    @property
    def secrets_providers(self) -> 'AppSecretsProvidersV1':
        return self._secrets_providers

    @secrets_providers.setter
    def secrets_providers(self, secrets_providers: 'AppSecretsProvidersV1'):
        self._secrets_providers = secrets_providers

    @property
    def secrets_providers__autoinit(self) -> 'AppSecretsProvidersV1':
        """Return ``secrets_providers``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._secrets_providers``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``secrets_providers__safederef`` when you only want to read a default without mutating self.
        """
        if self._secrets_providers is None:
            self._secrets_providers = self.secrets_providers__safederef

        return self._secrets_providers

    @property
    def secrets_providers__safederef(self) -> 'AppSecretsProvidersV1':
        """Return ``secrets_providers``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``secrets_providers`` stays unset and each
        call returns a new default. Use ``secrets_providers__autoinit`` to persist the default on
        first access.
        """
        if self._secrets_providers is None:
            from .. import models
            return models.AppSecretsProvidersV1._new_empty()

        return self._secrets_providers

    @property
    def resources(self) -> 'list[AppResourceV3]':
        return self._resources

    @resources.setter
    def resources(self, resources: 'list[AppResourceV3]'):
        self._resources = resources

    @property
    def resources__autoinit(self) -> 'list[AppResourceV3]':
        """Return ``resources``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._resources``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``resources__safederef`` when you only want to read a default without mutating self.
        """
        if self._resources is None:
            self._resources = self.resources__safederef

        return self._resources

    @property
    def resources__safederef(self) -> 'list[AppResourceV3]':
        """Return ``resources``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``resources`` stays unset and each
        call returns a new default. Use ``resources__autoinit`` to persist the default on
        first access.
        """
        if self._resources is None:
            return []

        return self._resources

    @property
    def pending_operations(self) -> 'list[AppOperationV2]':
        return self._pending_operations

    @pending_operations.setter
    def pending_operations(self, pending_operations: 'list[AppOperationV2]'):
        self._pending_operations = pending_operations

    @property
    def pending_operations__autoinit(self) -> 'list[AppOperationV2]':
        """Return ``pending_operations``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._pending_operations``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``pending_operations__safederef`` when you only want to read a default without mutating self.
        """
        if self._pending_operations is None:
            self._pending_operations = self.pending_operations__safederef

        return self._pending_operations

    @property
    def pending_operations__safederef(self) -> 'list[AppOperationV2]':
        """Return ``pending_operations``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``pending_operations`` stays unset and each
        call returns a new default. Use ``pending_operations__autoinit`` to persist the default on
        first access.
        """
        if self._pending_operations is None:
            return []

        return self._pending_operations

    @property
    def metadata(self) -> 'AppSnapshotMetadataV1':
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: 'AppSnapshotMetadataV1'):
        self._metadata = metadata

    @property
    def metadata__autoinit(self) -> 'AppSnapshotMetadataV1':
        """Return ``metadata``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._metadata``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``metadata__safederef`` when you only want to read a default without mutating self.
        """
        if self._metadata is None:
            self._metadata = self.metadata__safederef

        return self._metadata

    @property
    def metadata__safederef(self) -> 'AppSnapshotMetadataV1':
        """Return ``metadata``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``metadata`` stays unset and each
        call returns a new default. Use ``metadata__autoinit`` to persist the default on
        first access.
        """
        if self._metadata is None:
            from .. import models
            return models.AppSnapshotMetadataV1._new_empty()

        return self._metadata

    @property
    def snippets(self) -> 'list[AppSnippetV1]':
        return self._snippets

    @snippets.setter
    def snippets(self, snippets: 'list[AppSnippetV1]'):
        self._snippets = snippets

    @property
    def snippets__autoinit(self) -> 'list[AppSnippetV1]':
        """Return ``snippets``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._snippets``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``snippets__safederef`` when you only want to read a default without mutating self.
        """
        if self._snippets is None:
            self._snippets = self.snippets__safederef

        return self._snippets

    @property
    def snippets__safederef(self) -> 'list[AppSnippetV1]':
        """Return ``snippets``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``snippets`` stays unset and each
        call returns a new default. Use ``snippets__autoinit`` to persist the default on
        first access.
        """
        if self._snippets is None:
            return []

        return self._snippets

    @property
    def extensions(self) -> 'dict[str, AppExtension]':
        return self._extensions

    @extensions.setter
    def extensions(self, extensions: 'dict[str, AppExtension]'):
        self._extensions = extensions

    @property
    def extensions__autoinit(self) -> 'dict[str, AppExtension]':
        """Return ``extensions``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._extensions``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``extensions__safederef`` when you only want to read a default without mutating self.
        """
        if self._extensions is None:
            self._extensions = self.extensions__safederef

        return self._extensions

    @property
    def extensions__safederef(self) -> 'dict[str, AppExtension]':
        """Return ``extensions``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``extensions`` stays unset and each
        call returns a new default. Use ``extensions__autoinit`` to persist the default on
        first access.
        """
        if self._extensions is None:
            return {}

        return self._extensions

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, AppDeploymentV3):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
