# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class AppAppendUpdateLogEntryRequest(PulumiAutoModelEncoder):
    """
    :var kind: str - declared
    :var fields: dict[str, Any] - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'kind': 'str',
        'fields': 'dict[str, Any]',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'kind': 'kind',
        'fields': 'fields',
    }

    FIELDS_kind = 'kind'
    FIELDS_fields = 'fields'

    _kind: 'str'
    _fields: 'dict[str, Any]'

    def __init__(
        self,
        kind: 'str',
        fields: 'dict[str, Any]',
    ) -> None:
        super().__init__()

        self.kind = kind
        self.fields = fields

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, AppAppendUpdateLogEntryRequest):
            self._kind = source._kind
            self._fields = source._fields

    @property
    def kind(self) -> 'str':
        return self._kind

    @kind.setter
    def kind(self, kind: 'str'):
        if kind is None:
            raise ValueError("Invalid value for `kind`, must not be `None`")

        self._kind = kind

    @property
    def fields(self) -> 'dict[str, Any]':
        return self._fields

    @fields.setter
    def fields(self, fields: 'dict[str, Any]'):
        if fields is None:
            raise ValueError("Invalid value for `fields`, must not be `None`")

        self._fields = fields

    @property
    def fields__autoinit(self) -> 'dict[str, Any]':
        """Return ``fields``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._fields``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``fields__safederef`` when you only want to read a default without mutating self.
        """
        if self._fields is None:
            self._fields = self.fields__safederef

        return self._fields

    @property
    def fields__safederef(self) -> 'dict[str, Any]':
        """Return ``fields``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``fields`` stays unset and each
        call returns a new default. Use ``fields__autoinit`` to persist the default on
        first access.
        """
        if self._fields is None:
            return {}

        return self._fields

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, AppAppendUpdateLogEntryRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
