# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# Code generated by pulumi-codegen. DO NOT EDIT.

from typing import Any
from typing import Optional

from .._support import AutoEnumEncoder


class AppProgressType(AutoEnumEncoder):
    PluginDownload = "plugin-download"
    PluginInstall = "plugin-install"

    @staticmethod
    def keys() -> list['AppProgressType']:
        return [
            AppProgressType.PluginDownload,
            AppProgressType.PluginInstall
        ]

    @staticmethod
    def values() -> list[str]:
        return [
            AppProgressType.PluginDownload.value,
            AppProgressType.PluginInstall.value
        ]

    @staticmethod
    def parse(value: Any, /, *, default: 'AppProgressType' = None) -> Optional['AppProgressType']:
        for e in AppProgressType.__members__.values():
            if e.value == value:
                return e

        return default
