# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class AppUpdateMetadata(PulumiAutoModelEncoder):
    """
    :var message: str - declared
    :var environment: dict[str, str] - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'message': 'str',
        'environment': 'dict[str, str]',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'message': 'message',
        'environment': 'environment',
    }

    FIELDS_message = 'message'
    FIELDS_environment = 'environment'

    _message: 'str'
    _environment: 'dict[str, str]'

    def __init__(
        self,
        message: 'str',
        environment: 'dict[str, str]',
    ) -> None:
        super().__init__()

        self.message = message
        self.environment = environment

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, AppUpdateMetadata):
            self._message = source._message
            self._environment = source._environment

    @property
    def message(self) -> 'str':
        return self._message

    @message.setter
    def message(self, message: 'str'):
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")

        self._message = message

    @property
    def environment(self) -> 'dict[str, str]':
        return self._environment

    @environment.setter
    def environment(self, environment: 'dict[str, str]'):
        if environment is None:
            raise ValueError("Invalid value for `environment`, must not be `None`")

        self._environment = environment

    @property
    def environment__autoinit(self) -> 'dict[str, str]':
        """Return ``environment``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._environment``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``environment__safederef`` when you only want to read a default without mutating self.
        """
        if self._environment is None:
            self._environment = self.environment__safederef

        return self._environment

    @property
    def environment__safederef(self) -> 'dict[str, str]':
        """Return ``environment``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``environment`` stays unset and each
        call returns a new default. Use ``environment__autoinit`` to persist the default on
        first access.
        """
        if self._environment is None:
            return {}

        return self._environment

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, AppUpdateMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
