# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class AuditLogsExportS3Config(PulumiAutoModelEncoder):
    """
    :var s3_bucket_name: str - declared
    :var s3_path_prefix: str - declared
    :var iam_role_arn: str - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        's3_bucket_name': 'str',
        's3_path_prefix': 'str',
        'iam_role_arn': 'str',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        's3_bucket_name': 's3BucketName',
        's3_path_prefix': 's3PathPrefix',
        'iam_role_arn': 'iamRoleArn',
    }

    FIELDS_s3_bucket_name = 's3BucketName'
    FIELDS_s3_path_prefix = 's3PathPrefix'
    FIELDS_iam_role_arn = 'iamRoleArn'

    _s3_bucket_name: 'str'
    _s3_path_prefix: 'str'
    _iam_role_arn: 'str'

    def __init__(
        self,
        s3_bucket_name: 'str',
        iam_role_arn: 'str',
        s3_path_prefix: 'str' = None,
    ) -> None:
        super().__init__()

        self.s3_bucket_name = s3_bucket_name
        self.s3_path_prefix = s3_path_prefix
        self.iam_role_arn = iam_role_arn

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, AuditLogsExportS3Config):
            self._s3_bucket_name = source._s3_bucket_name
            self._s3_path_prefix = source._s3_path_prefix
            self._iam_role_arn = source._iam_role_arn

    @property
    def s3_bucket_name(self) -> 'str':
        return self._s3_bucket_name

    @s3_bucket_name.setter
    def s3_bucket_name(self, s3_bucket_name: 'str'):
        if s3_bucket_name is None:
            raise ValueError("Invalid value for `s3_bucket_name`, must not be `None`")

        self._s3_bucket_name = s3_bucket_name

    @property
    def s3_path_prefix(self) -> 'str':
        return self._s3_path_prefix

    @s3_path_prefix.setter
    def s3_path_prefix(self, s3_path_prefix: 'str'):
        self._s3_path_prefix = s3_path_prefix

    @property
    def iam_role_arn(self) -> 'str':
        return self._iam_role_arn

    @iam_role_arn.setter
    def iam_role_arn(self, iam_role_arn: 'str'):
        if iam_role_arn is None:
            raise ValueError("Invalid value for `iam_role_arn`, must not be `None`")

        self._iam_role_arn = iam_role_arn

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, AuditLogsExportS3Config):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
