# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# Code generated by pulumi-codegen. DO NOT EDIT.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class AzureEnvironmentInfo(PulumiAutoModelEncoder):
    """
    :var subscription_id: str - declared
    :var role_id: str - declared
    :var project_name: str - declared
    :var environment_name: str - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'subscription_id': 'str',
        'role_id': 'str',
        'project_name': 'str',
        'environment_name': 'str',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'subscription_id': 'subscriptionID',
        'role_id': 'roleID',
        'project_name': 'projectName',
        'environment_name': 'environmentName',
    }

    FIELDS_subscription_id = 'subscriptionID'
    FIELDS_role_id = 'roleID'
    FIELDS_project_name = 'projectName'
    FIELDS_environment_name = 'environmentName'

    _subscription_id: 'str'
    _role_id: 'str'
    _project_name: 'str'
    _environment_name: 'str'

    def __init__(
        self,
        subscription_id: 'str',
        role_id: 'str',
        project_name: 'str',
        environment_name: 'str',
    ) -> None:
        super().__init__()

        self.subscription_id = subscription_id
        self.role_id = role_id
        self.project_name = project_name
        self.environment_name = environment_name

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, AzureEnvironmentInfo):
            self._subscription_id = source._subscription_id
            self._role_id = source._role_id
            self._project_name = source._project_name
            self._environment_name = source._environment_name

    @property
    def subscription_id(self) -> 'str':
        return self._subscription_id

    @subscription_id.setter
    def subscription_id(self, subscription_id: 'str'):
        if subscription_id is None:
            raise ValueError("Invalid value for `subscription_id`, must not be `None`")

        self._subscription_id = subscription_id

    @property
    def role_id(self) -> 'str':
        return self._role_id

    @role_id.setter
    def role_id(self, role_id: 'str'):
        if role_id is None:
            raise ValueError("Invalid value for `role_id`, must not be `None`")

        self._role_id = role_id

    @property
    def project_name(self) -> 'str':
        return self._project_name

    @project_name.setter
    def project_name(self, project_name: 'str'):
        if project_name is None:
            raise ValueError("Invalid value for `project_name`, must not be `None`")

        self._project_name = project_name

    @property
    def environment_name(self) -> 'str':
        return self._environment_name

    @environment_name.setter
    def environment_name(self, environment_name: 'str'):
        if environment_name is None:
            raise ValueError("Invalid value for `environment_name`, must not be `None`")

        self._environment_name = environment_name

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, AzureEnvironmentInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
