# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class BitBucketWorkspace(PulumiAutoModelEncoder):
    """
    :var uuid: str - declared
    :var name: str - declared
    :var slug: str - declared
    :var avatar_url: str - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'uuid': 'str',
        'name': 'str',
        'slug': 'str',
        'avatar_url': 'str',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'uuid': 'uuid',
        'name': 'name',
        'slug': 'slug',
        'avatar_url': 'avatarUrl',
    }

    FIELDS_uuid = 'uuid'
    FIELDS_name = 'name'
    FIELDS_slug = 'slug'
    FIELDS_avatar_url = 'avatarUrl'

    _uuid: 'str'
    _name: 'str'
    _slug: 'str'
    _avatar_url: 'str'

    def __init__(
        self,
        uuid: 'str',
        name: 'str',
        slug: 'str',
        avatar_url: 'str' = None,
    ) -> None:
        super().__init__()

        self.uuid = uuid
        self.name = name
        self.slug = slug
        self.avatar_url = avatar_url

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, BitBucketWorkspace):
            self._uuid = source._uuid
            self._name = source._name
            self._slug = source._slug
            self._avatar_url = source._avatar_url

    @property
    def uuid(self) -> 'str':
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: 'str'):
        if uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")

        self._uuid = uuid

    @property
    def name(self) -> 'str':
        return self._name

    @name.setter
    def name(self, name: 'str'):
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def slug(self) -> 'str':
        return self._slug

    @slug.setter
    def slug(self, slug: 'str'):
        if slug is None:
            raise ValueError("Invalid value for `slug`, must not be `None`")

        self._slug = slug

    @property
    def avatar_url(self) -> 'str':
        return self._avatar_url

    @avatar_url.setter
    def avatar_url(self, avatar_url: 'str'):
        self._avatar_url = avatar_url

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, BitBucketWorkspace):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
