# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class CompleteOAuthRequest(PulumiAutoModelEncoder):
    """
    :var provider: CloudSetupProvider - declared
    :var session_i_d: str - declared
    :var code: str - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'provider': 'CloudSetupProvider',
        'session_i_d': 'str',
        'code': 'str',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'provider': 'provider',
        'session_i_d': 'sessionID',
        'code': 'code',
    }

    FIELDS_provider = 'provider'
    FIELDS_session_i_d = 'sessionID'
    FIELDS_code = 'code'

    _provider: 'CloudSetupProvider'
    _session_i_d: 'str'
    _code: 'str'

    def __init__(
        self,
        provider: 'CloudSetupProvider',
        session_i_d: 'str',
        code: 'str',
    ) -> None:
        super().__init__()

        self.provider = provider
        self.session_i_d = session_i_d
        self.code = code

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, CompleteOAuthRequest):
            self._provider = source._provider
            self._session_i_d = source._session_i_d
            self._code = source._code

    @property
    def provider(self) -> 'CloudSetupProvider':
        return self._provider

    @provider.setter
    def provider(self, provider: 'CloudSetupProvider'):
        if provider is None:
            raise ValueError("Invalid value for `provider`, must not be `None`")

        self._provider = provider

    @property
    def provider__autoinit(self) -> 'CloudSetupProvider':
        """Return ``provider``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._provider``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``provider__safederef`` when you only want to read a default without mutating self.
        """
        if self._provider is None:
            self._provider = self.provider__safederef

        return self._provider

    @property
    def provider__safederef(self) -> 'CloudSetupProvider':
        """Return ``provider``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``provider`` stays unset and each
        call returns a new default. Use ``provider__autoinit`` to persist the default on
        first access.
        """
        if self._provider is None:
            from .. import models
            return models.CloudSetupProvider._new_empty()

        return self._provider

    @property
    def session_i_d(self) -> 'str':
        return self._session_i_d

    @session_i_d.setter
    def session_i_d(self, session_i_d: 'str'):
        if session_i_d is None:
            raise ValueError("Invalid value for `session_i_d`, must not be `None`")

        self._session_i_d = session_i_d

    @property
    def code(self) -> 'str':
        return self._code

    @code.setter
    def code(self, code: 'str'):
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, CompleteOAuthRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
