# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class CreatePulumiTeamRequest(PulumiAutoModelEncoder):
    """
    :var name: str - declared
    :var display_name: str - declared
    :var description: str - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'name': 'str',
        'display_name': 'str',
        'description': 'str',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'name': 'name',
        'display_name': 'displayName',
        'description': 'description',
    }

    FIELDS_name = 'name'
    FIELDS_display_name = 'displayName'
    FIELDS_description = 'description'

    _name: 'str'
    _display_name: 'str'
    _description: 'str'

    def __init__(
        self,
        name: 'str',
        display_name: 'str',
        description: 'str',
    ) -> None:
        super().__init__()

        self.name = name
        self.display_name = display_name
        self.description = description

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, CreatePulumiTeamRequest):
            self._name = source._name
            self._display_name = source._display_name
            self._description = source._description

    @property
    def name(self) -> 'str':
        return self._name

    @name.setter
    def name(self, name: 'str'):
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def display_name(self) -> 'str':
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: 'str'):
        if display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")

        self._display_name = display_name

    @property
    def description(self) -> 'str':
        return self._description

    @description.setter
    def description(self, description: 'str'):
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")

        self._description = description

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, CreatePulumiTeamRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
