# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class CreateScheduledDeploymentRequest(PulumiAutoModelEncoder):
    """
    :var schedule_cron: str - declared
    :var schedule_once: datetime - declared
    :var request: CreateDeploymentRequest - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'schedule_cron': 'str',
        'schedule_once': 'datetime',
        'request': 'CreateDeploymentRequest',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'schedule_cron': 'scheduleCron',
        'schedule_once': 'scheduleOnce',
        'request': 'request',
    }

    FIELDS_schedule_cron = 'scheduleCron'
    FIELDS_schedule_once = 'scheduleOnce'
    FIELDS_request = 'request'

    _schedule_cron: 'str'
    _schedule_once: 'datetime'
    _request: 'CreateDeploymentRequest'

    def __init__(
        self,
        schedule_cron: 'str' = None,
        schedule_once: 'datetime' = None,
        request: 'CreateDeploymentRequest' = None,
    ) -> None:
        super().__init__()

        self.schedule_cron = schedule_cron
        self.schedule_once = schedule_once
        self.request = request

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, CreateScheduledDeploymentRequest):
            self._schedule_cron = source._schedule_cron
            self._schedule_once = source._schedule_once
            self._request = source._request

    @property
    def schedule_cron(self) -> 'str':
        return self._schedule_cron

    @schedule_cron.setter
    def schedule_cron(self, schedule_cron: 'str'):
        self._schedule_cron = schedule_cron

    @property
    def schedule_once(self) -> 'datetime':
        return self._schedule_once

    @schedule_once.setter
    def schedule_once(self, schedule_once: 'datetime'):
        self._schedule_once = schedule_once

    @property
    def request(self) -> 'CreateDeploymentRequest':
        return self._request

    @request.setter
    def request(self, request: 'CreateDeploymentRequest'):
        self._request = request

    @property
    def request__autoinit(self) -> 'CreateDeploymentRequest':
        """Return ``request``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._request``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``request__safederef`` when you only want to read a default without mutating self.
        """
        if self._request is None:
            self._request = self.request__safederef

        return self._request

    @property
    def request__safederef(self) -> 'CreateDeploymentRequest':
        """Return ``request``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``request`` stays unset and each
        call returns a new default. Use ``request__autoinit`` to persist the default on
        first access.
        """
        if self._request is None:
            from .. import models
            return models.CreateDeploymentRequest._new_empty()

        return self._request

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, CreateScheduledDeploymentRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
