# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class DeletedStack(PulumiAutoModelEncoder):
    """
    :var id: str - declared
    :var program_id: str - declared
    :var project_name: str - declared
    :var stack_name: str - declared
    :var version: int - declared
    :var deleted_at: int - declared
    :var last_update: UpdateSummary - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'id': 'str',
        'program_id': 'str',
        'project_name': 'str',
        'stack_name': 'str',
        'version': 'int',
        'deleted_at': 'int',
        'last_update': 'UpdateSummary',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'id': 'id',
        'program_id': 'programId',
        'project_name': 'projectName',
        'stack_name': 'stackName',
        'version': 'version',
        'deleted_at': 'deletedAt',
        'last_update': 'lastUpdate',
    }

    FIELDS_id = 'id'
    FIELDS_program_id = 'programId'
    FIELDS_project_name = 'projectName'
    FIELDS_stack_name = 'stackName'
    FIELDS_version = 'version'
    FIELDS_deleted_at = 'deletedAt'
    FIELDS_last_update = 'lastUpdate'

    _id: 'str'
    _program_id: 'str'
    _project_name: 'str'
    _stack_name: 'str'
    _version: 'int'
    _deleted_at: 'int'
    _last_update: 'UpdateSummary'

    def __init__(
        self,
        id: 'str',
        program_id: 'str',
        project_name: 'str',
        stack_name: 'str',
        version: 'int',
        deleted_at: 'int',
        last_update: 'UpdateSummary',
    ) -> None:
        super().__init__()

        self.id = id
        self.program_id = program_id
        self.project_name = project_name
        self.stack_name = stack_name
        self.version = version
        self.deleted_at = deleted_at
        self.last_update = last_update

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, DeletedStack):
            self._id = source._id
            self._program_id = source._program_id
            self._project_name = source._project_name
            self._stack_name = source._stack_name
            self._version = source._version
            self._deleted_at = source._deleted_at
            self._last_update = source._last_update

    @property
    def id(self) -> 'str':
        return self._id

    @id.setter
    def id(self, id: 'str'):
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def program_id(self) -> 'str':
        return self._program_id

    @program_id.setter
    def program_id(self, program_id: 'str'):
        if program_id is None:
            raise ValueError("Invalid value for `program_id`, must not be `None`")

        self._program_id = program_id

    @property
    def project_name(self) -> 'str':
        return self._project_name

    @project_name.setter
    def project_name(self, project_name: 'str'):
        if project_name is None:
            raise ValueError("Invalid value for `project_name`, must not be `None`")

        self._project_name = project_name

    @property
    def stack_name(self) -> 'str':
        return self._stack_name

    @stack_name.setter
    def stack_name(self, stack_name: 'str'):
        if stack_name is None:
            raise ValueError("Invalid value for `stack_name`, must not be `None`")

        self._stack_name = stack_name

    @property
    def version(self) -> 'int':
        return self._version

    @version.setter
    def version(self, version: 'int'):
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")

        self._version = version

    @property
    def deleted_at(self) -> 'int':
        return self._deleted_at

    @deleted_at.setter
    def deleted_at(self, deleted_at: 'int'):
        if deleted_at is None:
            raise ValueError("Invalid value for `deleted_at`, must not be `None`")

        self._deleted_at = deleted_at

    @property
    def last_update(self) -> 'UpdateSummary':
        return self._last_update

    @last_update.setter
    def last_update(self, last_update: 'UpdateSummary'):
        if last_update is None:
            raise ValueError("Invalid value for `last_update`, must not be `None`")

        self._last_update = last_update

    @property
    def last_update__autoinit(self) -> 'UpdateSummary':
        """Return ``last_update``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._last_update``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``last_update__safederef`` when you only want to read a default without mutating self.
        """
        if self._last_update is None:
            self._last_update = self.last_update__safederef

        return self._last_update

    @property
    def last_update__safederef(self) -> 'UpdateSummary':
        """Return ``last_update``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``last_update`` stays unset and each
        call returns a new default. Use ``last_update__autoinit`` to persist the default on
        first access.
        """
        if self._last_update is None:
            from .. import models
            return models.UpdateSummary._new_empty()

        return self._last_update

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, DeletedStack):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
