# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class EnvironmentTag(PulumiAutoModelEncoder):
    """
    :var name: str - declared
    :var value: str - declared
    :var created: datetime - declared
    :var modified: datetime - declared
    :var editor_login: str - declared
    :var editor_name: str - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'name': 'str',
        'value': 'str',
        'created': 'datetime',
        'modified': 'datetime',
        'editor_login': 'str',
        'editor_name': 'str',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'name': 'name',
        'value': 'value',
        'created': 'created',
        'modified': 'modified',
        'editor_login': 'editorLogin',
        'editor_name': 'editorName',
    }

    FIELDS_name = 'name'
    FIELDS_value = 'value'
    FIELDS_created = 'created'
    FIELDS_modified = 'modified'
    FIELDS_editor_login = 'editorLogin'
    FIELDS_editor_name = 'editorName'

    _name: 'str'
    _value: 'str'
    _created: 'datetime'
    _modified: 'datetime'
    _editor_login: 'str'
    _editor_name: 'str'

    def __init__(
        self,
        name: 'str',
        value: 'str',
        created: 'datetime',
        modified: 'datetime',
        editor_login: 'str',
        editor_name: 'str',
    ) -> None:
        super().__init__()

        self.name = name
        self.value = value
        self.created = created
        self.modified = modified
        self.editor_login = editor_login
        self.editor_name = editor_name

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, EnvironmentTag):
            self._name = source._name
            self._value = source._value
            self._created = source._created
            self._modified = source._modified
            self._editor_login = source._editor_login
            self._editor_name = source._editor_name

    @property
    def name(self) -> 'str':
        return self._name

    @name.setter
    def name(self, name: 'str'):
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def value(self) -> 'str':
        return self._value

    @value.setter
    def value(self, value: 'str'):
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")

        self._value = value

    @property
    def created(self) -> 'datetime':
        return self._created

    @created.setter
    def created(self, created: 'datetime'):
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")

        self._created = created

    @property
    def modified(self) -> 'datetime':
        return self._modified

    @modified.setter
    def modified(self, modified: 'datetime'):
        if modified is None:
            raise ValueError("Invalid value for `modified`, must not be `None`")

        self._modified = modified

    @property
    def editor_login(self) -> 'str':
        return self._editor_login

    @editor_login.setter
    def editor_login(self, editor_login: 'str'):
        if editor_login is None:
            raise ValueError("Invalid value for `editor_login`, must not be `None`")

        self._editor_login = editor_login

    @property
    def editor_name(self) -> 'str':
        return self._editor_name

    @editor_name.setter
    def editor_name(self, editor_name: 'str'):
        if editor_name is None:
            raise ValueError("Invalid value for `editor_name`, must not be `None`")

        self._editor_name = editor_name

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, EnvironmentTag):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
