# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class ExecutorSettingsRequest(PulumiAutoModelEncoder):
    """
    :var executor_image: DockerImageRequest - declared
    :var executor_root_path: str - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'executor_image': 'DockerImageRequest',
        'executor_root_path': 'str',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'executor_image': 'executorImage',
        'executor_root_path': 'executorRootPath',
    }

    FIELDS_executor_image = 'executorImage'
    FIELDS_executor_root_path = 'executorRootPath'

    _executor_image: 'DockerImageRequest'
    _executor_root_path: 'str'

    def __init__(
        self,
        executor_image: 'DockerImageRequest' = None,
        executor_root_path: 'str' = None,
    ) -> None:
        super().__init__()

        self.executor_image = executor_image
        self.executor_root_path = executor_root_path

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, ExecutorSettingsRequest):
            self._executor_image = source._executor_image
            self._executor_root_path = source._executor_root_path

    @property
    def executor_image(self) -> 'DockerImageRequest':
        return self._executor_image

    @executor_image.setter
    def executor_image(self, executor_image: 'DockerImageRequest'):
        self._executor_image = executor_image

    @property
    def executor_image__autoinit(self) -> 'DockerImageRequest':
        """Return ``executor_image``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._executor_image``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``executor_image__safederef`` when you only want to read a default without mutating self.
        """
        if self._executor_image is None:
            self._executor_image = self.executor_image__safederef

        return self._executor_image

    @property
    def executor_image__safederef(self) -> 'DockerImageRequest':
        """Return ``executor_image``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``executor_image`` stays unset and each
        call returns a new default. Use ``executor_image__autoinit`` to persist the default on
        first access.
        """
        if self._executor_image is None:
            from .. import models
            return models.DockerImageRequest._new_empty()

        return self._executor_image

    @property
    def executor_root_path(self) -> 'str':
        return self._executor_root_path

    @executor_root_path.setter
    def executor_root_path(self, executor_root_path: 'str'):
        self._executor_root_path = executor_root_path

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, ExecutorSettingsRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
