# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class GetPackageNavModule(PulumiAutoModelEncoder):
    """
    :var name: str - declared
    :var resources: list[GetPackageNavItem] - declared
    :var functions: list[GetPackageNavItem] - declared
    :var resources_total: int - declared
    :var functions_total: int - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'name': 'str',
        'resources': 'list[GetPackageNavItem]',
        'functions': 'list[GetPackageNavItem]',
        'resources_total': 'int',
        'functions_total': 'int',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'name': 'name',
        'resources': 'resources',
        'functions': 'functions',
        'resources_total': 'resourcesTotal',
        'functions_total': 'functionsTotal',
    }

    FIELDS_name = 'name'
    FIELDS_resources = 'resources'
    FIELDS_functions = 'functions'
    FIELDS_resources_total = 'resourcesTotal'
    FIELDS_functions_total = 'functionsTotal'

    _name: 'str'
    _resources: 'list[GetPackageNavItem]'
    _functions: 'list[GetPackageNavItem]'
    _resources_total: 'int'
    _functions_total: 'int'

    def __init__(
        self,
        name: 'str',
        resources_total: 'int',
        functions_total: 'int',
        resources: 'list[GetPackageNavItem]' = None,
        functions: 'list[GetPackageNavItem]' = None,
    ) -> None:
        super().__init__()

        self.name = name
        self.resources = resources
        self.functions = functions
        self.resources_total = resources_total
        self.functions_total = functions_total

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, GetPackageNavModule):
            self._name = source._name
            self._resources = source._resources
            self._functions = source._functions
            self._resources_total = source._resources_total
            self._functions_total = source._functions_total

    @property
    def name(self) -> 'str':
        return self._name

    @name.setter
    def name(self, name: 'str'):
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def resources(self) -> 'list[GetPackageNavItem]':
        return self._resources

    @resources.setter
    def resources(self, resources: 'list[GetPackageNavItem]'):
        self._resources = resources

    @property
    def resources__autoinit(self) -> 'list[GetPackageNavItem]':
        """Return ``resources``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._resources``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``resources__safederef`` when you only want to read a default without mutating self.
        """
        if self._resources is None:
            self._resources = self.resources__safederef

        return self._resources

    @property
    def resources__safederef(self) -> 'list[GetPackageNavItem]':
        """Return ``resources``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``resources`` stays unset and each
        call returns a new default. Use ``resources__autoinit`` to persist the default on
        first access.
        """
        if self._resources is None:
            return []

        return self._resources

    @property
    def functions(self) -> 'list[GetPackageNavItem]':
        return self._functions

    @functions.setter
    def functions(self, functions: 'list[GetPackageNavItem]'):
        self._functions = functions

    @property
    def functions__autoinit(self) -> 'list[GetPackageNavItem]':
        """Return ``functions``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._functions``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``functions__safederef`` when you only want to read a default without mutating self.
        """
        if self._functions is None:
            self._functions = self.functions__safederef

        return self._functions

    @property
    def functions__safederef(self) -> 'list[GetPackageNavItem]':
        """Return ``functions``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``functions`` stays unset and each
        call returns a new default. Use ``functions__autoinit`` to persist the default on
        first access.
        """
        if self._functions is None:
            return []

        return self._functions

    @property
    def resources_total(self) -> 'int':
        return self._resources_total

    @resources_total.setter
    def resources_total(self, resources_total: 'int'):
        if resources_total is None:
            raise ValueError("Invalid value for `resources_total`, must not be `None`")

        self._resources_total = resources_total

    @property
    def functions_total(self) -> 'int':
        return self._functions_total

    @functions_total.setter
    def functions_total(self, functions_total: 'int'):
        if functions_total is None:
            raise ValueError("Invalid value for `functions_total`, must not be `None`")

        self._functions_total = functions_total

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, GetPackageNavModule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
