# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class GitLabAppOrganization(PulumiAutoModelEncoder):
    """
    :var id: int - declared
    :var name: str - declared
    :var avatar_u_r_l: str - declared
    :var has_required_permissions: bool - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'id': 'int',
        'name': 'str',
        'avatar_u_r_l': 'str',
        'has_required_permissions': 'bool',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'id': 'id',
        'name': 'name',
        'avatar_u_r_l': 'avatarURL',
        'has_required_permissions': 'hasRequiredPermissions',
    }

    FIELDS_id = 'id'
    FIELDS_name = 'name'
    FIELDS_avatar_u_r_l = 'avatarURL'
    FIELDS_has_required_permissions = 'hasRequiredPermissions'

    _id: 'int'
    _name: 'str'
    _avatar_u_r_l: 'str'
    _has_required_permissions: 'bool'

    def __init__(
        self,
        id: 'int',
        name: 'str',
        avatar_u_r_l: 'str',
        has_required_permissions: 'bool',
    ) -> None:
        super().__init__()

        self.id = id
        self.name = name
        self.avatar_u_r_l = avatar_u_r_l
        self.has_required_permissions = has_required_permissions

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, GitLabAppOrganization):
            self._id = source._id
            self._name = source._name
            self._avatar_u_r_l = source._avatar_u_r_l
            self._has_required_permissions = source._has_required_permissions

    @property
    def id(self) -> 'int':
        return self._id

    @id.setter
    def id(self, id: 'int'):
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def name(self) -> 'str':
        return self._name

    @name.setter
    def name(self, name: 'str'):
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def avatar_u_r_l(self) -> 'str':
        return self._avatar_u_r_l

    @avatar_u_r_l.setter
    def avatar_u_r_l(self, avatar_u_r_l: 'str'):
        if avatar_u_r_l is None:
            raise ValueError("Invalid value for `avatar_u_r_l`, must not be `None`")

        self._avatar_u_r_l = avatar_u_r_l

    @property
    def has_required_permissions(self) -> 'bool':
        return self._has_required_permissions

    @has_required_permissions.setter
    def has_required_permissions(self, has_required_permissions: 'bool'):
        if has_required_permissions is None:
            raise ValueError("Invalid value for `has_required_permissions`, must not be `None`")

        self._has_required_permissions = has_required_permissions

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, GitLabAppOrganization):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
