# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class GitHubAppPermissionRequirement(PulumiAutoModelEncoder):
    """
    :var name: str - declared
    :var required: GitHubAppPermissionLevel - declared
    :var actual: GitHubAppPermissionLevel - declared
    :var reason: str - declared
    :var is_sufficient: bool - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'name': 'str',
        'required': 'GitHubAppPermissionLevel',
        'actual': 'GitHubAppPermissionLevel',
        'reason': 'str',
        'is_sufficient': 'bool',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'name': 'name',
        'required': 'required',
        'actual': 'actual',
        'reason': 'reason',
        'is_sufficient': 'isSufficient',
    }

    FIELDS_name = 'name'
    FIELDS_required = 'required'
    FIELDS_actual = 'actual'
    FIELDS_reason = 'reason'
    FIELDS_is_sufficient = 'isSufficient'

    _name: 'str'
    _required: 'GitHubAppPermissionLevel'
    _actual: 'GitHubAppPermissionLevel'
    _reason: 'str'
    _is_sufficient: 'bool'

    def __init__(
        self,
        name: 'str',
        required: 'GitHubAppPermissionLevel',
        actual: 'GitHubAppPermissionLevel',
        reason: 'str',
        is_sufficient: 'bool',
    ) -> None:
        super().__init__()

        self.name = name
        self.required = required
        self.actual = actual
        self.reason = reason
        self.is_sufficient = is_sufficient

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, GitHubAppPermissionRequirement):
            self._name = source._name
            self._required = source._required
            self._actual = source._actual
            self._reason = source._reason
            self._is_sufficient = source._is_sufficient

    @property
    def name(self) -> 'str':
        return self._name

    @name.setter
    def name(self, name: 'str'):
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def required(self) -> 'GitHubAppPermissionLevel':
        return self._required

    @required.setter
    def required(self, required: 'GitHubAppPermissionLevel'):
        if required is None:
            raise ValueError("Invalid value for `required`, must not be `None`")

        self._required = required

    @property
    def actual(self) -> 'GitHubAppPermissionLevel':
        return self._actual

    @actual.setter
    def actual(self, actual: 'GitHubAppPermissionLevel'):
        if actual is None:
            raise ValueError("Invalid value for `actual`, must not be `None`")

        self._actual = actual

    @property
    def reason(self) -> 'str':
        return self._reason

    @reason.setter
    def reason(self, reason: 'str'):
        if reason is None:
            raise ValueError("Invalid value for `reason`, must not be `None`")

        self._reason = reason

    @property
    def is_sufficient(self) -> 'bool':
        return self._is_sufficient

    @is_sufficient.setter
    def is_sufficient(self, is_sufficient: 'bool'):
        if is_sufficient is None:
            raise ValueError("Invalid value for `is_sufficient`, must not be `None`")

        self._is_sufficient = is_sufficient

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, GitHubAppPermissionRequirement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
