# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class GraphQueryScope(PulumiAutoModelEncoder):
    """
    :var accounts: list[str] - declared
    :var stacks: list[str] - declared
    :var include_discovered: bool - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'accounts': 'list[str]',
        'stacks': 'list[str]',
        'include_discovered': 'bool',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'accounts': 'accounts',
        'stacks': 'stacks',
        'include_discovered': 'includeDiscovered',
    }

    FIELDS_accounts = 'accounts'
    FIELDS_stacks = 'stacks'
    FIELDS_include_discovered = 'includeDiscovered'

    _accounts: 'list[str]'
    _stacks: 'list[str]'
    _include_discovered: 'bool'

    def __init__(
        self,
        accounts: 'list[str]' = None,
        stacks: 'list[str]' = None,
        include_discovered: 'bool' = False,
    ) -> None:
        super().__init__()

        self.accounts = accounts
        self.stacks = stacks
        self.include_discovered = include_discovered

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, GraphQueryScope):
            self._accounts = source._accounts
            self._stacks = source._stacks
            self._include_discovered = source._include_discovered

    @property
    def accounts(self) -> 'list[str]':
        return self._accounts

    @accounts.setter
    def accounts(self, accounts: 'list[str]'):
        self._accounts = accounts

    @property
    def accounts__autoinit(self) -> 'list[str]':
        """Return ``accounts``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._accounts``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``accounts__safederef`` when you only want to read a default without mutating self.
        """
        if self._accounts is None:
            self._accounts = self.accounts__safederef

        return self._accounts

    @property
    def accounts__safederef(self) -> 'list[str]':
        """Return ``accounts``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``accounts`` stays unset and each
        call returns a new default. Use ``accounts__autoinit`` to persist the default on
        first access.
        """
        if self._accounts is None:
            return []

        return self._accounts

    @property
    def stacks(self) -> 'list[str]':
        return self._stacks

    @stacks.setter
    def stacks(self, stacks: 'list[str]'):
        self._stacks = stacks

    @property
    def stacks__autoinit(self) -> 'list[str]':
        """Return ``stacks``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._stacks``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``stacks__safederef`` when you only want to read a default without mutating self.
        """
        if self._stacks is None:
            self._stacks = self.stacks__safederef

        return self._stacks

    @property
    def stacks__safederef(self) -> 'list[str]':
        """Return ``stacks``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``stacks`` stays unset and each
        call returns a new default. Use ``stacks__autoinit`` to persist the default on
        first access.
        """
        if self._stacks is None:
            return []

        return self._stacks

    @property
    def include_discovered(self) -> 'bool':
        return self._include_discovered

    @include_discovered.setter
    def include_discovered(self, include_discovered: 'bool'):
        self._include_discovered = include_discovered

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, GraphQueryScope):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
