# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class GraphSchemaLimits(PulumiAutoModelEncoder):
    """
    :var max_depth: int - declared
    :var max_traverse_steps: int - declared
    :var max_scope_accounts: int - declared
    :var max_scope_stacks: int - declared
    :var max_group_by_fields: int - declared
    :var max_anchor_nodes: int - declared
    :var max_fanout: int - declared
    :var max_nodes: int - declared
    :var max_paths: int - declared
    :var max_recorded_crossings: int - declared
    :var max_page_size: int - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'max_depth': 'int',
        'max_traverse_steps': 'int',
        'max_scope_accounts': 'int',
        'max_scope_stacks': 'int',
        'max_group_by_fields': 'int',
        'max_anchor_nodes': 'int',
        'max_fanout': 'int',
        'max_nodes': 'int',
        'max_paths': 'int',
        'max_recorded_crossings': 'int',
        'max_page_size': 'int',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'max_depth': 'maxDepth',
        'max_traverse_steps': 'maxTraverseSteps',
        'max_scope_accounts': 'maxScopeAccounts',
        'max_scope_stacks': 'maxScopeStacks',
        'max_group_by_fields': 'maxGroupByFields',
        'max_anchor_nodes': 'maxAnchorNodes',
        'max_fanout': 'maxFanout',
        'max_nodes': 'maxNodes',
        'max_paths': 'maxPaths',
        'max_recorded_crossings': 'maxRecordedCrossings',
        'max_page_size': 'maxPageSize',
    }

    FIELDS_max_depth = 'maxDepth'
    FIELDS_max_traverse_steps = 'maxTraverseSteps'
    FIELDS_max_scope_accounts = 'maxScopeAccounts'
    FIELDS_max_scope_stacks = 'maxScopeStacks'
    FIELDS_max_group_by_fields = 'maxGroupByFields'
    FIELDS_max_anchor_nodes = 'maxAnchorNodes'
    FIELDS_max_fanout = 'maxFanout'
    FIELDS_max_nodes = 'maxNodes'
    FIELDS_max_paths = 'maxPaths'
    FIELDS_max_recorded_crossings = 'maxRecordedCrossings'
    FIELDS_max_page_size = 'maxPageSize'

    _max_depth: 'int'
    _max_traverse_steps: 'int'
    _max_scope_accounts: 'int'
    _max_scope_stacks: 'int'
    _max_group_by_fields: 'int'
    _max_anchor_nodes: 'int'
    _max_fanout: 'int'
    _max_nodes: 'int'
    _max_paths: 'int'
    _max_recorded_crossings: 'int'
    _max_page_size: 'int'

    def __init__(
        self,
        max_depth: 'int',
        max_traverse_steps: 'int',
        max_scope_accounts: 'int',
        max_scope_stacks: 'int',
        max_group_by_fields: 'int',
        max_anchor_nodes: 'int',
        max_fanout: 'int',
        max_nodes: 'int',
        max_paths: 'int',
        max_recorded_crossings: 'int',
        max_page_size: 'int',
    ) -> None:
        super().__init__()

        self.max_depth = max_depth
        self.max_traverse_steps = max_traverse_steps
        self.max_scope_accounts = max_scope_accounts
        self.max_scope_stacks = max_scope_stacks
        self.max_group_by_fields = max_group_by_fields
        self.max_anchor_nodes = max_anchor_nodes
        self.max_fanout = max_fanout
        self.max_nodes = max_nodes
        self.max_paths = max_paths
        self.max_recorded_crossings = max_recorded_crossings
        self.max_page_size = max_page_size

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, GraphSchemaLimits):
            self._max_depth = source._max_depth
            self._max_traverse_steps = source._max_traverse_steps
            self._max_scope_accounts = source._max_scope_accounts
            self._max_scope_stacks = source._max_scope_stacks
            self._max_group_by_fields = source._max_group_by_fields
            self._max_anchor_nodes = source._max_anchor_nodes
            self._max_fanout = source._max_fanout
            self._max_nodes = source._max_nodes
            self._max_paths = source._max_paths
            self._max_recorded_crossings = source._max_recorded_crossings
            self._max_page_size = source._max_page_size

    @property
    def max_depth(self) -> 'int':
        return self._max_depth

    @max_depth.setter
    def max_depth(self, max_depth: 'int'):
        if max_depth is None:
            raise ValueError("Invalid value for `max_depth`, must not be `None`")

        self._max_depth = max_depth

    @property
    def max_traverse_steps(self) -> 'int':
        return self._max_traverse_steps

    @max_traverse_steps.setter
    def max_traverse_steps(self, max_traverse_steps: 'int'):
        if max_traverse_steps is None:
            raise ValueError("Invalid value for `max_traverse_steps`, must not be `None`")

        self._max_traverse_steps = max_traverse_steps

    @property
    def max_scope_accounts(self) -> 'int':
        return self._max_scope_accounts

    @max_scope_accounts.setter
    def max_scope_accounts(self, max_scope_accounts: 'int'):
        if max_scope_accounts is None:
            raise ValueError("Invalid value for `max_scope_accounts`, must not be `None`")

        self._max_scope_accounts = max_scope_accounts

    @property
    def max_scope_stacks(self) -> 'int':
        return self._max_scope_stacks

    @max_scope_stacks.setter
    def max_scope_stacks(self, max_scope_stacks: 'int'):
        if max_scope_stacks is None:
            raise ValueError("Invalid value for `max_scope_stacks`, must not be `None`")

        self._max_scope_stacks = max_scope_stacks

    @property
    def max_group_by_fields(self) -> 'int':
        return self._max_group_by_fields

    @max_group_by_fields.setter
    def max_group_by_fields(self, max_group_by_fields: 'int'):
        if max_group_by_fields is None:
            raise ValueError("Invalid value for `max_group_by_fields`, must not be `None`")

        self._max_group_by_fields = max_group_by_fields

    @property
    def max_anchor_nodes(self) -> 'int':
        return self._max_anchor_nodes

    @max_anchor_nodes.setter
    def max_anchor_nodes(self, max_anchor_nodes: 'int'):
        if max_anchor_nodes is None:
            raise ValueError("Invalid value for `max_anchor_nodes`, must not be `None`")

        self._max_anchor_nodes = max_anchor_nodes

    @property
    def max_fanout(self) -> 'int':
        return self._max_fanout

    @max_fanout.setter
    def max_fanout(self, max_fanout: 'int'):
        if max_fanout is None:
            raise ValueError("Invalid value for `max_fanout`, must not be `None`")

        self._max_fanout = max_fanout

    @property
    def max_nodes(self) -> 'int':
        return self._max_nodes

    @max_nodes.setter
    def max_nodes(self, max_nodes: 'int'):
        if max_nodes is None:
            raise ValueError("Invalid value for `max_nodes`, must not be `None`")

        self._max_nodes = max_nodes

    @property
    def max_paths(self) -> 'int':
        return self._max_paths

    @max_paths.setter
    def max_paths(self, max_paths: 'int'):
        if max_paths is None:
            raise ValueError("Invalid value for `max_paths`, must not be `None`")

        self._max_paths = max_paths

    @property
    def max_recorded_crossings(self) -> 'int':
        return self._max_recorded_crossings

    @max_recorded_crossings.setter
    def max_recorded_crossings(self, max_recorded_crossings: 'int'):
        if max_recorded_crossings is None:
            raise ValueError("Invalid value for `max_recorded_crossings`, must not be `None`")

        self._max_recorded_crossings = max_recorded_crossings

    @property
    def max_page_size(self) -> 'int':
        return self._max_page_size

    @max_page_size.setter
    def max_page_size(self, max_page_size: 'int'):
        if max_page_size is None:
            raise ValueError("Invalid value for `max_page_size`, must not be `None`")

        self._max_page_size = max_page_size

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, GraphSchemaLimits):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
