# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

from typing import Any
from typing import Optional

from .._support import AutoEnumEncoder


class IdentityProvider(AutoEnumEncoder):
    AzureDevOps = "dev.azure.com"
    Bitbucket = "bitbucket.org"
    GitHub = "github.com"
    GitLab = "gitlab.com"
    Google = "google.com"
    Pulumi = "Pulumi"
    SAML = "SAML"

    @staticmethod
    def keys() -> list['IdentityProvider']:
        return [
            IdentityProvider.AzureDevOps,
            IdentityProvider.Bitbucket,
            IdentityProvider.GitHub,
            IdentityProvider.GitLab,
            IdentityProvider.Google,
            IdentityProvider.Pulumi,
            IdentityProvider.SAML
        ]

    @staticmethod
    def values() -> list[str]:
        return [
            IdentityProvider.AzureDevOps.value,
            IdentityProvider.Bitbucket.value,
            IdentityProvider.GitHub.value,
            IdentityProvider.GitLab.value,
            IdentityProvider.Google.value,
            IdentityProvider.Pulumi.value,
            IdentityProvider.SAML.value
        ]

    @staticmethod
    def parse(value: Any, /, *, default: 'IdentityProvider' = None) -> Optional['IdentityProvider']:
        for e in IdentityProvider.__members__.values():
            if e.value == value:
                return e

        return default
