# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class InsightsResourceIdentifier(PulumiAutoModelEncoder):
    """
    :var account: str - declared
    :var type: str - declared
    :var id: str - declared
    :var version: int - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'account': 'str',
        'type': 'str',
        'id': 'str',
        'version': 'int',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'account': 'account',
        'type': 'type',
        'id': 'id',
        'version': 'version',
    }

    FIELDS_account = 'account'
    FIELDS_type = 'type'
    FIELDS_id = 'id'
    FIELDS_version = 'version'

    _account: 'str'
    _type: 'str'
    _id: 'str'
    _version: 'int'

    def __init__(
        self,
        account: 'str',
        type: 'str',
        id: 'str',
        version: 'int' = 0,
    ) -> None:
        super().__init__()

        self.account = account
        self.type = type
        self.id = id
        self.version = version

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, InsightsResourceIdentifier):
            self._account = source._account
            self._type = source._type
            self._id = source._id
            self._version = source._version

    @property
    def account(self) -> 'str':
        return self._account

    @account.setter
    def account(self, account: 'str'):
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")

        self._account = account

    @property
    def type(self) -> 'str':
        return self._type

    @type.setter
    def type(self, type: 'str'):
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def id(self) -> 'str':
        return self._id

    @id.setter
    def id(self, id: 'str'):
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def version(self) -> 'int':
        return self._version

    @version.setter
    def version(self, version: 'int'):
        self._version = version

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, InsightsResourceIdentifier):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
