# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

from typing import Any
from typing import Optional

from .._support import AutoEnumEncoder


class InsightsAccountPermission(AutoEnumEncoder):
    None_ = 0
    Read = 1
    Write = 2
    Admin = 3

    @staticmethod
    def keys() -> list['InsightsAccountPermission']:
        return [
            InsightsAccountPermission.None_,
            InsightsAccountPermission.Read,
            InsightsAccountPermission.Write,
            InsightsAccountPermission.Admin
        ]

    @staticmethod
    def values() -> list[int]:
        return [
            InsightsAccountPermission.None_.value,
            InsightsAccountPermission.Read.value,
            InsightsAccountPermission.Write.value,
            InsightsAccountPermission.Admin.value
        ]

    @staticmethod
    def parse(value: Any, /, *, default: 'InsightsAccountPermission' = None) -> Optional['InsightsAccountPermission']:
        for e in InsightsAccountPermission.__members__.values():
            if e.value == value:
                return e

        return default
