# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class ListVCSIntegrationSummariesResponse(PulumiAutoModelEncoder):
    """
    :var integrations: list[VCSIntegrationSummary] - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'integrations': 'list[VCSIntegrationSummary]',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'integrations': 'integrations',
    }

    FIELDS_integrations = 'integrations'

    _integrations: 'list[VCSIntegrationSummary]'

    def __init__(
        self,
        integrations: 'list[VCSIntegrationSummary]',
    ) -> None:
        super().__init__()

        self.integrations = integrations

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, ListVCSIntegrationSummariesResponse):
            self._integrations = source._integrations

    @property
    def integrations(self) -> 'list[VCSIntegrationSummary]':
        return self._integrations

    @integrations.setter
    def integrations(self, integrations: 'list[VCSIntegrationSummary]'):
        if integrations is None:
            raise ValueError("Invalid value for `integrations`, must not be `None`")

        self._integrations = integrations

    @property
    def integrations__autoinit(self) -> 'list[VCSIntegrationSummary]':
        """Return ``integrations``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._integrations``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``integrations__safederef`` when you only want to read a default without mutating self.
        """
        if self._integrations is None:
            self._integrations = self.integrations__safederef

        return self._integrations

    @property
    def integrations__safederef(self) -> 'list[VCSIntegrationSummary]':
        """Return ``integrations``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``integrations`` stays unset and each
        call returns a new default. Use ``integrations__autoinit`` to persist the default on
        first access.
        """
        if self._integrations is None:
            return []

        return self._integrations

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, ListVCSIntegrationSummariesResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
