# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class ListRotatorsResponse(PulumiAutoModelEncoder):
    """
    :var rotators: list[str] - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'rotators': 'list[str]',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'rotators': 'rotators',
    }

    FIELDS_rotators = 'rotators'

    _rotators: 'list[str]'

    def __init__(
        self,
        rotators: 'list[str]',
    ) -> None:
        super().__init__()

        self.rotators = rotators

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, ListRotatorsResponse):
            self._rotators = source._rotators

    @property
    def rotators(self) -> 'list[str]':
        return self._rotators

    @rotators.setter
    def rotators(self, rotators: 'list[str]'):
        if rotators is None:
            raise ValueError("Invalid value for `rotators`, must not be `None`")

        self._rotators = rotators

    @property
    def rotators__autoinit(self) -> 'list[str]':
        """Return ``rotators``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._rotators``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``rotators__safederef`` when you only want to read a default without mutating self.
        """
        if self._rotators is None:
            self._rotators = self.rotators__safederef

        return self._rotators

    @property
    def rotators__safederef(self) -> 'list[str]':
        """Return ``rotators``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``rotators`` stays unset and each
        call returns a new default. Use ``rotators__autoinit`` to persist the default on
        first access.
        """
        if self._rotators is None:
            return []

        return self._rotators

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, ListRotatorsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
