# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class ListChangeGatesResponse(PulumiAutoModelEncoder):
    """
    :var gates: list[ChangeGate] - declared
    :var continuation_token: str - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'gates': 'list[ChangeGate]',
        'continuation_token': 'str',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'gates': 'gates',
        'continuation_token': 'continuationToken',
    }

    FIELDS_gates = 'gates'
    FIELDS_continuation_token = 'continuationToken'

    _gates: 'list[ChangeGate]'
    _continuation_token: 'str'

    def __init__(
        self,
        gates: 'list[ChangeGate]',
        continuation_token: 'str',
    ) -> None:
        super().__init__()

        self.gates = gates
        self.continuation_token = continuation_token

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, ListChangeGatesResponse):
            self._gates = source._gates
            self._continuation_token = source._continuation_token

    @property
    def gates(self) -> 'list[ChangeGate]':
        return self._gates

    @gates.setter
    def gates(self, gates: 'list[ChangeGate]'):
        if gates is None:
            raise ValueError("Invalid value for `gates`, must not be `None`")

        self._gates = gates

    @property
    def gates__autoinit(self) -> 'list[ChangeGate]':
        """Return ``gates``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._gates``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``gates__safederef`` when you only want to read a default without mutating self.
        """
        if self._gates is None:
            self._gates = self.gates__safederef

        return self._gates

    @property
    def gates__safederef(self) -> 'list[ChangeGate]':
        """Return ``gates``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``gates`` stays unset and each
        call returns a new default. Use ``gates__autoinit`` to persist the default on
        first access.
        """
        if self._gates is None:
            return []

        return self._gates

    @property
    def continuation_token(self) -> 'str':
        return self._continuation_token

    @continuation_token.setter
    def continuation_token(self, continuation_token: 'str'):
        if continuation_token is None:
            raise ValueError("Invalid value for `continuation_token`, must not be `None`")

        self._continuation_token = continuation_token

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, ListChangeGatesResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
