# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .permission_descriptor_ import PermissionDescriptor

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class PermissionDescriptorSelect(PermissionDescriptor):
    """
    :var selector: PermissionExpression - declared
    :var options: list[PermissionSelectvalue] - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'selector': 'PermissionExpression',
        'options': 'list[PermissionSelectvalue]',
        '__DISCRIMINATOR_VALUE__': 'str'
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'selector': 'selector',
        'options': 'options',
        '__DISCRIMINATOR_VALUE__': '__type'
    }

    __DISCRIMINATOR_VALUE__ = "PermissionDescriptorSelect"

    FIELDS_selector = 'selector'
    FIELDS_options = 'options'

    _selector: 'PermissionExpression'
    _options: 'list[PermissionSelectvalue]'

    def __init__(
        self,
        selector: 'PermissionExpression' = None,
        options: 'list[PermissionSelectvalue]' = None,
    ) -> None:
        super().__init__()

        self.selector = selector
        self.options = options

    def copy_common_fields(self, source: Any, /) -> None:
        super().copy_common_fields(source)
        if isinstance(source, PermissionDescriptorSelect):
            self._selector = source._selector
            self._options = source._options

    @property
    def selector(self) -> 'PermissionExpression':
        return self._selector

    @selector.setter
    def selector(self, selector: 'PermissionExpression'):
        self._selector = selector

    @property
    def options(self) -> 'list[PermissionSelectvalue]':
        return self._options

    @options.setter
    def options(self, options: 'list[PermissionSelectvalue]'):
        self._options = options

    @property
    def options__autoinit(self) -> 'list[PermissionSelectvalue]':
        """Return ``options``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._options``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``options__safederef`` when you only want to read a default without mutating self.
        """
        if self._options is None:
            self._options = self.options__safederef

        return self._options

    @property
    def options__safederef(self) -> 'list[PermissionSelectvalue]':
        """Return ``options``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``options`` stays unset and each
        call returns a new default. Use ``options__autoinit`` to persist the default on
        first access.
        """
        if self._options is None:
            return []

        return self._options

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, PermissionDescriptorSelect):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
