# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

from typing import Any
from typing import Optional

from .._support import AutoEnumEncoder


class PolicyIssueKind(AutoEnumEncoder):
    Audit = "audit"
    Preventative = "preventative"

    @staticmethod
    def keys() -> list['PolicyIssueKind']:
        return [
            PolicyIssueKind.Audit,
            PolicyIssueKind.Preventative
        ]

    @staticmethod
    def values() -> list[str]:
        return [
            PolicyIssueKind.Audit.value,
            PolicyIssueKind.Preventative.value
        ]

    @staticmethod
    def parse(value: Any, /, *, default: 'PolicyIssueKind' = None) -> Optional['PolicyIssueKind']:
        for e in PolicyIssueKind.__members__.values():
            if e.value == value:
                return e

        return default
