# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class PolicyComplianceRow(PulumiAutoModelEncoder):
    """
    :var policy_name: str - declared
    :var severity: AppPolicySeverity - declared
    :var failing_resources: int - declared
    :var governed_resources: int - declared
    :var percent_compliant: int - declared
    :var policy_pack: str - declared
    :var policy_group_name: str - declared
    :var policy_group_type: PolicyGroupMode - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'policy_name': 'str',
        'severity': 'AppPolicySeverity',
        'failing_resources': 'int',
        'governed_resources': 'int',
        'percent_compliant': 'int',
        'policy_pack': 'str',
        'policy_group_name': 'str',
        'policy_group_type': 'PolicyGroupMode',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'policy_name': 'policyName',
        'severity': 'severity',
        'failing_resources': 'failingResources',
        'governed_resources': 'governedResources',
        'percent_compliant': 'percentCompliant',
        'policy_pack': 'policyPack',
        'policy_group_name': 'policyGroupName',
        'policy_group_type': 'policyGroupType',
    }

    FIELDS_policy_name = 'policyName'
    FIELDS_severity = 'severity'
    FIELDS_failing_resources = 'failingResources'
    FIELDS_governed_resources = 'governedResources'
    FIELDS_percent_compliant = 'percentCompliant'
    FIELDS_policy_pack = 'policyPack'
    FIELDS_policy_group_name = 'policyGroupName'
    FIELDS_policy_group_type = 'policyGroupType'

    _policy_name: 'str'
    _severity: 'AppPolicySeverity'
    _failing_resources: 'int'
    _governed_resources: 'int'
    _percent_compliant: 'int'
    _policy_pack: 'str'
    _policy_group_name: 'str'
    _policy_group_type: 'PolicyGroupMode'

    def __init__(
        self,
        policy_name: 'str',
        severity: 'AppPolicySeverity',
        failing_resources: 'int',
        governed_resources: 'int',
        percent_compliant: 'int',
        policy_pack: 'str',
        policy_group_name: 'str',
        policy_group_type: 'PolicyGroupMode',
    ) -> None:
        super().__init__()

        self.policy_name = policy_name
        self.severity = severity
        self.failing_resources = failing_resources
        self.governed_resources = governed_resources
        self.percent_compliant = percent_compliant
        self.policy_pack = policy_pack
        self.policy_group_name = policy_group_name
        self.policy_group_type = policy_group_type

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, PolicyComplianceRow):
            self._policy_name = source._policy_name
            self._severity = source._severity
            self._failing_resources = source._failing_resources
            self._governed_resources = source._governed_resources
            self._percent_compliant = source._percent_compliant
            self._policy_pack = source._policy_pack
            self._policy_group_name = source._policy_group_name
            self._policy_group_type = source._policy_group_type

    @property
    def policy_name(self) -> 'str':
        return self._policy_name

    @policy_name.setter
    def policy_name(self, policy_name: 'str'):
        if policy_name is None:
            raise ValueError("Invalid value for `policy_name`, must not be `None`")

        self._policy_name = policy_name

    @property
    def severity(self) -> 'AppPolicySeverity':
        return self._severity

    @severity.setter
    def severity(self, severity: 'AppPolicySeverity'):
        if severity is None:
            raise ValueError("Invalid value for `severity`, must not be `None`")

        self._severity = severity

    @property
    def failing_resources(self) -> 'int':
        return self._failing_resources

    @failing_resources.setter
    def failing_resources(self, failing_resources: 'int'):
        if failing_resources is None:
            raise ValueError("Invalid value for `failing_resources`, must not be `None`")

        self._failing_resources = failing_resources

    @property
    def governed_resources(self) -> 'int':
        return self._governed_resources

    @governed_resources.setter
    def governed_resources(self, governed_resources: 'int'):
        if governed_resources is None:
            raise ValueError("Invalid value for `governed_resources`, must not be `None`")

        self._governed_resources = governed_resources

    @property
    def percent_compliant(self) -> 'int':
        return self._percent_compliant

    @percent_compliant.setter
    def percent_compliant(self, percent_compliant: 'int'):
        if percent_compliant is None:
            raise ValueError("Invalid value for `percent_compliant`, must not be `None`")

        self._percent_compliant = percent_compliant

    @property
    def policy_pack(self) -> 'str':
        return self._policy_pack

    @policy_pack.setter
    def policy_pack(self, policy_pack: 'str'):
        if policy_pack is None:
            raise ValueError("Invalid value for `policy_pack`, must not be `None`")

        self._policy_pack = policy_pack

    @property
    def policy_group_name(self) -> 'str':
        return self._policy_group_name

    @policy_group_name.setter
    def policy_group_name(self, policy_group_name: 'str'):
        if policy_group_name is None:
            raise ValueError("Invalid value for `policy_group_name`, must not be `None`")

        self._policy_group_name = policy_group_name

    @property
    def policy_group_type(self) -> 'PolicyGroupMode':
        return self._policy_group_type

    @policy_group_type.setter
    def policy_group_type(self, policy_group_type: 'PolicyGroupMode'):
        if policy_group_type is None:
            raise ValueError("Invalid value for `policy_group_type`, must not be `None`")

        self._policy_group_type = policy_group_type

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, PolicyComplianceRow):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
