# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class RemoveCustomVCSRepositoryRequest(PulumiAutoModelEncoder):
    """
    :var name: str - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'name': 'str',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'name': 'name',
    }

    FIELDS_name = 'name'

    _name: 'str'

    def __init__(
        self,
        name: 'str',
    ) -> None:
        super().__init__()

        self.name = name

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, RemoveCustomVCSRepositoryRequest):
            self._name = source._name

    @property
    def name(self) -> 'str':
        return self._name

    @name.setter
    def name(self, name: 'str'):
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, RemoveCustomVCSRepositoryRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
