# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class ServiceMember(PulumiAutoModelEncoder):
    """
    :var type: str - declared
    :var name: str - declared
    :var avatar_url: str - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'type': 'str',
        'name': 'str',
        'avatar_url': 'str',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'type': 'type',
        'name': 'name',
        'avatar_url': 'avatarUrl',
    }

    FIELDS_type = 'type'
    FIELDS_name = 'name'
    FIELDS_avatar_url = 'avatarUrl'

    _type: 'str'
    _name: 'str'
    _avatar_url: 'str'

    def __init__(
        self,
        type: 'str',
        name: 'str',
        avatar_url: 'str',
    ) -> None:
        super().__init__()

        self.type = type
        self.name = name
        self.avatar_url = avatar_url

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, ServiceMember):
            self._type = source._type
            self._name = source._name
            self._avatar_url = source._avatar_url

    @property
    def type(self) -> 'str':
        return self._type

    @type.setter
    def type(self, type: 'str'):
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def name(self) -> 'str':
        return self._name

    @name.setter
    def name(self, name: 'str'):
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def avatar_url(self) -> 'str':
        return self._avatar_url

    @avatar_url.setter
    def avatar_url(self, avatar_url: 'str'):
        if avatar_url is None:
            raise ValueError("Invalid value for `avatar_url`, must not be `None`")

        self._avatar_url = avatar_url

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, ServiceMember):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
