# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class StackReference(PulumiAutoModelEncoder):
    """
    :var organization: str - declared
    :var routing_project: str - declared
    :var name: str - declared
    :var version: int - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'organization': 'str',
        'routing_project': 'str',
        'name': 'str',
        'version': 'int',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'organization': 'organization',
        'routing_project': 'routingProject',
        'name': 'name',
        'version': 'version',
    }

    FIELDS_organization = 'organization'
    FIELDS_routing_project = 'routingProject'
    FIELDS_name = 'name'
    FIELDS_version = 'version'

    _organization: 'str'
    _routing_project: 'str'
    _name: 'str'
    _version: 'int'

    def __init__(
        self,
        organization: 'str',
        routing_project: 'str',
        name: 'str',
        version: 'int',
    ) -> None:
        super().__init__()

        self.organization = organization
        self.routing_project = routing_project
        self.name = name
        self.version = version

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, StackReference):
            self._organization = source._organization
            self._routing_project = source._routing_project
            self._name = source._name
            self._version = source._version

    @property
    def organization(self) -> 'str':
        return self._organization

    @organization.setter
    def organization(self, organization: 'str'):
        if organization is None:
            raise ValueError("Invalid value for `organization`, must not be `None`")

        self._organization = organization

    @property
    def routing_project(self) -> 'str':
        return self._routing_project

    @routing_project.setter
    def routing_project(self, routing_project: 'str'):
        if routing_project is None:
            raise ValueError("Invalid value for `routing_project`, must not be `None`")

        self._routing_project = routing_project

    @property
    def name(self) -> 'str':
        return self._name

    @name.setter
    def name(self, name: 'str'):
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def version(self) -> 'int':
        return self._version

    @version.setter
    def version(self, version: 'int'):
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")

        self._version = version

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, StackReference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
