# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class TemplateSource(PulumiAutoModelEncoder):
    """
    :var id: str - declared
    :var is_valid: bool - declared
    :var error: str - declared
    :var name: str - declared
    :var source_u_r_l: str - declared
    :var destination_u_r_l: str - declared
    :var destination: TemplateDestination - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'id': 'str',
        'is_valid': 'bool',
        'error': 'str',
        'name': 'str',
        'source_u_r_l': 'str',
        'destination_u_r_l': 'str',
        'destination': 'TemplateDestination',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'id': 'id',
        'is_valid': 'isValid',
        'error': 'error',
        'name': 'name',
        'source_u_r_l': 'sourceURL',
        'destination_u_r_l': 'destinationURL',
        'destination': 'destination',
    }

    FIELDS_id = 'id'
    FIELDS_is_valid = 'isValid'
    FIELDS_error = 'error'
    FIELDS_name = 'name'
    FIELDS_source_u_r_l = 'sourceURL'
    FIELDS_destination_u_r_l = 'destinationURL'
    FIELDS_destination = 'destination'

    _id: 'str'
    _is_valid: 'bool'
    _error: 'str'
    _name: 'str'
    _source_u_r_l: 'str'
    _destination_u_r_l: 'str'
    _destination: 'TemplateDestination'

    def __init__(
        self,
        id: 'str',
        is_valid: 'bool',
        name: 'str',
        source_u_r_l: 'str',
        error: 'str' = None,
        destination_u_r_l: 'str' = None,
        destination: 'TemplateDestination' = None,
    ) -> None:
        super().__init__()

        self.id = id
        self.is_valid = is_valid
        self.error = error
        self.name = name
        self.source_u_r_l = source_u_r_l
        self.destination_u_r_l = destination_u_r_l
        self.destination = destination

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, TemplateSource):
            self._id = source._id
            self._is_valid = source._is_valid
            self._error = source._error
            self._name = source._name
            self._source_u_r_l = source._source_u_r_l
            self._destination_u_r_l = source._destination_u_r_l
            self._destination = source._destination

    @property
    def id(self) -> 'str':
        return self._id

    @id.setter
    def id(self, id: 'str'):
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def is_valid(self) -> 'bool':
        return self._is_valid

    @is_valid.setter
    def is_valid(self, is_valid: 'bool'):
        if is_valid is None:
            raise ValueError("Invalid value for `is_valid`, must not be `None`")

        self._is_valid = is_valid

    @property
    def error(self) -> 'str':
        return self._error

    @error.setter
    def error(self, error: 'str'):
        self._error = error

    @property
    def name(self) -> 'str':
        return self._name

    @name.setter
    def name(self, name: 'str'):
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def source_u_r_l(self) -> 'str':
        return self._source_u_r_l

    @source_u_r_l.setter
    def source_u_r_l(self, source_u_r_l: 'str'):
        if source_u_r_l is None:
            raise ValueError("Invalid value for `source_u_r_l`, must not be `None`")

        self._source_u_r_l = source_u_r_l

    @property
    def destination_u_r_l(self) -> 'str':
        return self._destination_u_r_l

    @destination_u_r_l.setter
    def destination_u_r_l(self, destination_u_r_l: 'str'):
        self._destination_u_r_l = destination_u_r_l

    @property
    def destination(self) -> 'TemplateDestination':
        return self._destination

    @destination.setter
    def destination(self, destination: 'TemplateDestination'):
        self._destination = destination

    @property
    def destination__autoinit(self) -> 'TemplateDestination':
        """Return ``destination``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._destination``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``destination__safederef`` when you only want to read a default without mutating self.
        """
        if self._destination is None:
            self._destination = self.destination__safederef

        return self._destination

    @property
    def destination__safederef(self) -> 'TemplateDestination':
        """Return ``destination``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``destination`` stays unset and each
        call returns a new default. Use ``destination__autoinit`` to persist the default on
        first access.
        """
        if self._destination is None:
            from .. import models
            return models.TemplateDestination._new_empty()

        return self._destination

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, TemplateSource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
