# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class VCSRepo(PulumiAutoModelEncoder):
    """
    :var id: str - declared
    :var owner: str - declared
    :var name: str - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'id': 'str',
        'owner': 'str',
        'name': 'str',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'id': 'id',
        'owner': 'owner',
        'name': 'name',
    }

    FIELDS_id = 'id'
    FIELDS_owner = 'owner'
    FIELDS_name = 'name'

    _id: 'str'
    _owner: 'str'
    _name: 'str'

    def __init__(
        self,
        id: 'str',
        owner: 'str',
        name: 'str',
    ) -> None:
        super().__init__()

        self.id = id
        self.owner = owner
        self.name = name

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, VCSRepo):
            self._id = source._id
            self._owner = source._owner
            self._name = source._name

    @property
    def id(self) -> 'str':
        return self._id

    @id.setter
    def id(self, id: 'str'):
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def owner(self) -> 'str':
        return self._owner

    @owner.setter
    def owner(self, owner: 'str'):
        if owner is None:
            raise ValueError("Invalid value for `owner`, must not be `None`")

        self._owner = owner

    @property
    def name(self) -> 'str':
        return self._name

    @name.setter
    def name(self, name: 'str'):
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, VCSRepo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
