# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

from typing import Any
from typing import Optional

from .._support import AutoEnumEncoder


class VCSType(AutoEnumEncoder):
    Git = "git"
    Hg = "hg"

    @staticmethod
    def keys() -> list['VCSType']:
        return [
            VCSType.Git,
            VCSType.Hg
        ]

    @staticmethod
    def values() -> list[str]:
        return [
            VCSType.Git.value,
            VCSType.Hg.value
        ]

    @staticmethod
    def parse(value: Any, /, *, default: 'VCSType' = None) -> Optional['VCSType']:
        for e in VCSType.__members__.values():
            if e.value == value:
                return e

        return default
