# coding: utf-8

# Copyright 2016-2026, Pulumi Corporation. All rights reserved.
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# RUN 'make openapi_python' TO REFRESH.

# noinspection PyUnresolvedReferences
from datetime import datetime, date, time
# noinspection PyUnresolvedReferences
from typing import Optional, Any, Type
from .._support import PulumiAutoModelEncoder

# noinspection PyUnresolvedReferences
from . import *


# noinspection PyShadowingBuiltins,PyShadowingNames
class WorkspaceProjectTemplate(PulumiAutoModelEncoder):
    """
    :var display_name: str - declared
    :var description: str - declared
    :var quickstart: str - declared
    :var config: dict[str, AppProjectTemplateConfigValue] - declared
    :var important: bool - declared
    :var metadata: dict[str, str] - declared
    """
    __swagger_types__ = {  # The key is attribute name and the value is attribute type.
        'display_name': 'str',
        'description': 'str',
        'quickstart': 'str',
        'config': 'dict[str, AppProjectTemplateConfigValue]',
        'important': 'bool',
        'metadata': 'dict[str, str]',
    }

    __attribute_map__ = {  # The key is attribute name and the value is json key in definition.
        'display_name': 'displayName',
        'description': 'description',
        'quickstart': 'quickstart',
        'config': 'config',
        'important': 'important',
        'metadata': 'metadata',
    }

    FIELDS_display_name = 'displayName'
    FIELDS_description = 'description'
    FIELDS_quickstart = 'quickstart'
    FIELDS_config = 'config'
    FIELDS_important = 'important'
    FIELDS_metadata = 'metadata'

    _display_name: 'str'
    _description: 'str'
    _quickstart: 'str'
    _config: 'dict[str, AppProjectTemplateConfigValue]'
    _important: 'bool'
    _metadata: 'dict[str, str]'

    def __init__(
        self,
        display_name: 'str' = None,
        description: 'str' = None,
        quickstart: 'str' = None,
        config: 'dict[str, AppProjectTemplateConfigValue]' = None,
        important: 'bool' = False,
        metadata: 'dict[str, str]' = None,
    ) -> None:
        super().__init__()

        self.display_name = display_name
        self.description = description
        self.quickstart = quickstart
        self.config = config
        self.important = important
        self.metadata = metadata

    def copy_common_fields(self, source: Any, /) -> None:
        if isinstance(source, WorkspaceProjectTemplate):
            self._display_name = source._display_name
            self._description = source._description
            self._quickstart = source._quickstart
            self._config = source._config
            self._important = source._important
            self._metadata = source._metadata

    @property
    def display_name(self) -> 'str':
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: 'str'):
        self._display_name = display_name

    @property
    def description(self) -> 'str':
        return self._description

    @description.setter
    def description(self, description: 'str'):
        self._description = description

    @property
    def quickstart(self) -> 'str':
        return self._quickstart

    @quickstart.setter
    def quickstart(self, quickstart: 'str'):
        self._quickstart = quickstart

    @property
    def config(self) -> 'dict[str, AppProjectTemplateConfigValue]':
        return self._config

    @config.setter
    def config(self, config: 'dict[str, AppProjectTemplateConfigValue]'):
        self._config = config

    @property
    def config__autoinit(self) -> 'dict[str, AppProjectTemplateConfigValue]':
        """Return ``config``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._config``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``config__safederef`` when you only want to read a default without mutating self.
        """
        if self._config is None:
            self._config = self.config__safederef

        return self._config

    @property
    def config__safederef(self) -> 'dict[str, AppProjectTemplateConfigValue]':
        """Return ``config``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``config`` stays unset and each
        call returns a new default. Use ``config__autoinit`` to persist the default on
        first access.
        """
        if self._config is None:
            return {}

        return self._config

    @property
    def important(self) -> 'bool':
        return self._important

    @important.setter
    def important(self, important: 'bool'):
        self._important = important

    @property
    def metadata(self) -> 'dict[str, str]':
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: 'dict[str, str]'):
        self._metadata = metadata

    @property
    def metadata__autoinit(self) -> 'dict[str, str]':
        """Return ``metadata``, creating and storing an empty default when it is unset.

        Side effect: the created default is written back to ``self._metadata``, so it
        persists on the model and is included when the model is serialized. Prefer
        ``metadata__safederef`` when you only want to read a default without mutating self.
        """
        if self._metadata is None:
            self._metadata = self.metadata__safederef

        return self._metadata

    @property
    def metadata__safederef(self) -> 'dict[str, str]':
        """Return ``metadata``, or a freshly built empty default when it is unset.

        No side effect: the default is not stored, so ``metadata`` stays unset and each
        call returns a new default. Use ``metadata__autoinit`` to persist the default on
        first access.
        """
        if self._metadata is None:
            return {}

        return self._metadata

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, WorkspaceProjectTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        return not self == other
