// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Pulumi.Cloud.Sdk.Models;

namespace Pulumi.Cloud.Sdk.Api {
    public sealed class AI_AgentsApi {
        private readonly ApiClient client;

        public AI_AgentsApi(ApiClient client) {
            this.client = client;
        }

        public void CancelTask(string orgName, string taskID, CancelAgentTaskRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling CancelTask");
            }
            if (taskID == null) {
                throw new ArgumentNullException(nameof(taskID), "Missing required parameter 'taskID' when calling CancelTask");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling CancelTask");
            }
            var apiRequest = new ApiRequest("POST", "/api/preview/agents/{orgName}/tasks/{taskID}/cancel");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("taskID", taskID);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            this.client.Call(apiRequest);
        }

        public AgentClaimResponse Claim(string orgName, AgentClaimRequest request, bool? dryRun) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling Claim");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling Claim");
            }
            var apiRequest = new ApiRequest("POST", "/api/agents/{orgName}/claim");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.Body(request);
            apiRequest.QueryParam("dryRun", dryRun);
            apiRequest.Consumes("application/json");
            apiRequest.Produces("application/json");
            return this.client.Call<AgentClaimResponse>(apiRequest);
        }

        public AgentClaimsStatus ClaimStatus(string orgName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ClaimStatus");
            }
            var request = new ApiRequest("GET", "/api/agents/{orgName}/claim/status");
            request.PathParam("orgName", orgName);
            request.Produces("application/json");
            return this.client.Call<AgentClaimsStatus>(request);
        }

        public CreateAgentTaskResponse CreateTasks(string orgName, CreateAgentTaskRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling CreateTasks");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling CreateTasks");
            }
            var apiRequest = new ApiRequest("POST", "/api/preview/agents/{orgName}/tasks");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            apiRequest.Produces("application/json");
            return this.client.Call<CreateAgentTaskResponse>(apiRequest);
        }

        public AgentTask GetTask(string orgName, string taskID) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GetTask");
            }
            if (taskID == null) {
                throw new ArgumentNullException(nameof(taskID), "Missing required parameter 'taskID' when calling GetTask");
            }
            var request = new ApiRequest("GET", "/api/preview/agents/{orgName}/tasks/{taskID}");
            request.PathParam("orgName", orgName);
            request.PathParam("taskID", taskID);
            request.Produces("application/json");
            return this.client.Call<AgentTask>(request);
        }

        public ListAgentTaskEventsResponse GetTaskEvents(string orgName, string taskID, string continuationToken, long? pageSize) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GetTaskEvents");
            }
            if (taskID == null) {
                throw new ArgumentNullException(nameof(taskID), "Missing required parameter 'taskID' when calling GetTaskEvents");
            }
            var request = new ApiRequest("GET", "/api/preview/agents/{orgName}/tasks/{taskID}/events");
            request.PathParam("orgName", orgName);
            request.PathParam("taskID", taskID);
            request.QueryParam("continuationToken", continuationToken);
            request.QueryParam("pageSize", pageSize);
            request.Produces("application/json");
            return this.client.Call<ListAgentTaskEventsResponse>(request);
        }

        public ListAgentTasksResponse ListTasks(string orgName, string continuationToken, long? pageSize, AgentTaskSortField? sortBy, AgentTaskSortDirection? sortDirection, AgentTaskType? taskType) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ListTasks");
            }
            var request = new ApiRequest("GET", "/api/preview/agents/{orgName}/tasks");
            request.PathParam("orgName", orgName);
            request.QueryParam("continuationToken", continuationToken);
            request.QueryParam("pageSize", pageSize);
            request.QueryParam("sortBy", sortBy);
            request.QueryParam("sortDirection", sortDirection);
            request.QueryParam("taskType", taskType);
            request.Produces("application/json");
            return this.client.Call<ListAgentTasksResponse>(request);
        }

        public void RespondToTask(string orgName, string taskID, AgentRespondToTaskRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling RespondToTask");
            }
            if (taskID == null) {
                throw new ArgumentNullException(nameof(taskID), "Missing required parameter 'taskID' when calling RespondToTask");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling RespondToTask");
            }
            var apiRequest = new ApiRequest("POST", "/api/preview/agents/{orgName}/tasks/{taskID}");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("taskID", taskID);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            this.client.Call(apiRequest);
        }

        public AgentSignupResponse Signup(AgentSignupRequest request) {
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling Signup");
            }
            var apiRequest = new ApiRequest("POST", "/api/agents/signup");
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            apiRequest.Produces("application/json");
            return this.client.Call<AgentSignupResponse>(apiRequest);
        }

        public AgentSignupChallenge SignupChallenge() {
            var request = new ApiRequest("GET", "/api/agents/signup");
            request.Produces("application/json");
            return this.client.Call<AgentSignupChallenge>(request);
        }

        public AgentClaimResponse SignupValidate(string claimToken) {
            if (claimToken == null) {
                throw new ArgumentNullException(nameof(claimToken), "Missing required parameter 'claimToken' when calling SignupValidate");
            }
            var request = new ApiRequest("GET", "/api/agents/signup/validate/{claimToken}");
            request.PathParam("claimToken", claimToken);
            request.Produces("application/json");
            return this.client.Call<AgentClaimResponse>(request);
        }

        public AgentConsoleEvent StreamTaskEvents(string orgName, string taskID) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling StreamTaskEvents");
            }
            if (taskID == null) {
                throw new ArgumentNullException(nameof(taskID), "Missing required parameter 'taskID' when calling StreamTaskEvents");
            }
            var request = new ApiRequest("GET", "/api/preview/agents/{orgName}/tasks/{taskID}/events/stream");
            request.PathParam("orgName", orgName);
            request.PathParam("taskID", taskID);
            request.Produces("text/event-stream");
            return this.client.Call<AgentConsoleEvent>(request);
        }

        public AgentTask UpdateTask(string orgName, string taskID, UpdateTaskRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling UpdateTask");
            }
            if (taskID == null) {
                throw new ArgumentNullException(nameof(taskID), "Missing required parameter 'taskID' when calling UpdateTask");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling UpdateTask");
            }
            var apiRequest = new ApiRequest("PATCH", "/api/preview/agents/{orgName}/tasks/{taskID}");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("taskID", taskID);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            apiRequest.Produces("application/json");
            return this.client.Call<AgentTask>(apiRequest);
        }
    }
}
