// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_dotnet' TO REFRESH.

#nullable disable

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Pulumi.Cloud.Sdk.Models;

namespace Pulumi.Cloud.Sdk.Api {
    public sealed class InsightsApi {
        private readonly ApiClient client;

        public InsightsApi(ApiClient client) {
            this.client = client;
        }

        public void AcceptInsightsBilling(string orgName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling AcceptInsightsBilling");
            }
            var request = new ApiRequest("PUT", "/api/preview/insights/{orgName}/insightstrial/accept");
            request.PathParam("orgName", orgName);
            this.client.Call(request);
        }

        public BulkCreateInsightsAccountsResponse BulkCreateAccounts(string orgName, BulkCreateInsightsAccountsRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling BulkCreateAccounts");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling BulkCreateAccounts");
            }
            var apiRequest = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            apiRequest.Produces("application/json");
            return this.client.Call<BulkCreateInsightsAccountsResponse>(apiRequest);
        }

        public void CancelScan(string orgName, string accountName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling CancelScan");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling CancelScan");
            }
            var request = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/scan/cancel");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            this.client.Call(request);
        }

        public void CreateAccount(string orgName, string accountName, CreateInsightsAccountRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling CreateAccount");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling CreateAccount");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling CreateAccount");
            }
            var apiRequest = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("accountName", accountName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            this.client.Call(apiRequest);
        }

        public void DeleteAccount(string orgName, string accountName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling DeleteAccount");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling DeleteAccount");
            }
            var request = new ApiRequest("DELETE", "/api/preview/insights/{orgName}/accounts/{accountName}");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            this.client.Call(request);
        }

        public void DeleteResourceMigrationAnnotation(string orgName, string projectName, string stackName, string resourceUrn) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling DeleteResourceMigrationAnnotation");
            }
            if (projectName == null) {
                throw new ArgumentNullException(nameof(projectName), "Missing required parameter 'projectName' when calling DeleteResourceMigrationAnnotation");
            }
            if (stackName == null) {
                throw new ArgumentNullException(nameof(stackName), "Missing required parameter 'stackName' when calling DeleteResourceMigrationAnnotation");
            }
            if (resourceUrn == null) {
                throw new ArgumentNullException(nameof(resourceUrn), "Missing required parameter 'resourceUrn' when calling DeleteResourceMigrationAnnotation");
            }
            var request = new ApiRequest("DELETE", "/api/preview/insights/{orgName}/discovered-stacks/{projectName}/{stackName}/migration");
            request.PathParam("orgName", orgName);
            request.PathParam("projectName", projectName);
            request.PathParam("stackName", stackName);
            request.QueryParam("resourceUrn", resourceUrn);
            this.client.Call(request);
        }

        public InsightsImportCodeResponse GenerateImportCode(string orgName, InsightsImportCodeRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GenerateImportCode");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling GenerateImportCode");
            }
            var apiRequest = new ApiRequest("POST", "/api/preview/insights/{orgName}/import/code/generate");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            apiRequest.Produces("application/json");
            return this.client.Call<InsightsImportCodeResponse>(apiRequest);
        }

        public GetDiscoveredProjectResponse GetDiscoveredProject(string orgName, string projectName, string continuationToken) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GetDiscoveredProject");
            }
            if (projectName == null) {
                throw new ArgumentNullException(nameof(projectName), "Missing required parameter 'projectName' when calling GetDiscoveredProject");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/discovered-stacks/{projectName}");
            request.PathParam("orgName", orgName);
            request.PathParam("projectName", projectName);
            request.QueryParam("continuationToken", continuationToken);
            request.Produces("application/json");
            return this.client.Call<GetDiscoveredProjectResponse>(request);
        }

        public GetDiscoveredStackResponse GetDiscoveredStack(string orgName, string projectName, string stackName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GetDiscoveredStack");
            }
            if (projectName == null) {
                throw new ArgumentNullException(nameof(projectName), "Missing required parameter 'projectName' when calling GetDiscoveredStack");
            }
            if (stackName == null) {
                throw new ArgumentNullException(nameof(stackName), "Missing required parameter 'stackName' when calling GetDiscoveredStack");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/discovered-stacks/{projectName}/{stackName}");
            request.PathParam("orgName", orgName);
            request.PathParam("projectName", projectName);
            request.PathParam("stackName", stackName);
            request.Produces("application/json");
            return this.client.Call<GetDiscoveredStackResponse>(request);
        }

        public GraphSchemaResponse GetGraphQuerySchema() {
            var request = new ApiRequest("GET", "/api/insights/graph/schema");
            request.Produces("application/json");
            request.Produces("text/markdown");
            return this.client.Call<GraphSchemaResponse>(request);
        }

        public GraphSchemaResponse GetGraphSchema(string orgName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GetGraphSchema");
            }
            var request = new ApiRequest("GET", "/api/insights/{orgName}/graph/schema");
            request.PathParam("orgName", orgName);
            request.Produces("application/json");
            request.Produces("text/markdown");
            return this.client.Call<GraphSchemaResponse>(request);
        }

        public GetInsightAccountTagsResponse GetInsightAccountTags(string orgName, string accountName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GetInsightAccountTags");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling GetInsightAccountTags");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/tags");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.Produces("application/json");
            return this.client.Call<GetInsightAccountTagsResponse>(request);
        }

        public TrialUsageSummary GetInsightsTrialSummary(string orgName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GetInsightsTrialSummary");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/insightstrial/summary");
            request.PathParam("orgName", orgName);
            request.Produces("application/json");
            return this.client.Call<TrialUsageSummary>(request);
        }

        public ScanStatus GetScan(string orgName, string accountName, string scanId) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GetScan");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling GetScan");
            }
            if (scanId == null) {
                throw new ArgumentNullException(nameof(scanId), "Missing required parameter 'scanId' when calling GetScan");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/scans/{scanId}");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.PathParam("scanId", scanId);
            request.Produces("application/json");
            return this.client.Call<ScanStatus>(request);
        }

        public DeploymentLogsBase GetScanLogs(string orgName, string accountName, string scanId, string continuationToken, long? count, long? job, long? offset, long? step) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GetScanLogs");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling GetScanLogs");
            }
            if (scanId == null) {
                throw new ArgumentNullException(nameof(scanId), "Missing required parameter 'scanId' when calling GetScanLogs");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/scans/{scanId}/logs");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.PathParam("scanId", scanId);
            request.QueryParam("continuationToken", continuationToken);
            request.QueryParam("count", count);
            request.QueryParam("job", job);
            request.QueryParam("offset", offset);
            request.QueryParam("step", step);
            request.Produces("application/json");
            return this.client.Call<DeploymentLogsBase>(request);
        }

        public ListDiscoveredStackResourcesResponse GetStackMigration(string orgName, string projectName, string stackName, string compareTo) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GetStackMigration");
            }
            if (projectName == null) {
                throw new ArgumentNullException(nameof(projectName), "Missing required parameter 'projectName' when calling GetStackMigration");
            }
            if (stackName == null) {
                throw new ArgumentNullException(nameof(stackName), "Missing required parameter 'stackName' when calling GetStackMigration");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/stacks/{projectName}/{stackName}/migration");
            request.PathParam("orgName", orgName);
            request.PathParam("projectName", projectName);
            request.PathParam("stackName", stackName);
            request.QueryParam("compareTo", compareTo);
            request.Produces("application/json");
            return this.client.Call<ListDiscoveredStackResourcesResponse>(request);
        }

        public GetResourceCountSummaryResponse GetUsageSummaryInsightsScans(string orgName, UsageSummaryTimeUnit granularity, long? lookbackDays, long? lookbackStart) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GetUsageSummaryInsightsScans");
            }
            var request = new ApiRequest("GET", "/api/orgs/{orgName}/insights-scans/summary");
            request.PathParam("orgName", orgName);
            request.QueryParam("granularity", granularity);
            request.QueryParam("lookbackDays", lookbackDays);
            request.QueryParam("lookbackStart", lookbackStart);
            request.Produces("application/json");
            return this.client.Call<GetResourceCountSummaryResponse>(request);
        }

        public GraphQueryResponse GraphQuery(string orgName, GraphQueryRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling GraphQuery");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling GraphQuery");
            }
            var apiRequest = new ApiRequest("POST", "/api/insights/{orgName}/graph/query");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            apiRequest.Produces("application/json");
            return this.client.Call<GraphQueryResponse>(apiRequest);
        }

        public void HeadAccount(string orgName, string accountName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling HeadAccount");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling HeadAccount");
            }
            var request = new ApiRequest("HEAD", "/api/preview/insights/{orgName}/accounts/{accountName}");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            this.client.Call(request);
        }

        public ListInsightsAccountsResponse ListAccounts(string orgName, string continuationToken, long? count, string parent, string roleID) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ListAccounts");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts");
            request.PathParam("orgName", orgName);
            request.QueryParam("continuationToken", continuationToken);
            request.QueryParam("count", count);
            request.QueryParam("parent", parent);
            request.QueryParam("roleID", roleID);
            request.Produces("application/json");
            return this.client.Call<ListInsightsAccountsResponse>(request);
        }

        public ListDiscoveredStackResourcesResponse ListDiscoveredStackResources(string orgName, string projectName, string stackName, string compareTo) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ListDiscoveredStackResources");
            }
            if (projectName == null) {
                throw new ArgumentNullException(nameof(projectName), "Missing required parameter 'projectName' when calling ListDiscoveredStackResources");
            }
            if (stackName == null) {
                throw new ArgumentNullException(nameof(stackName), "Missing required parameter 'stackName' when calling ListDiscoveredStackResources");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/discovered-stacks/{projectName}/{stackName}/resources");
            request.PathParam("orgName", orgName);
            request.PathParam("projectName", projectName);
            request.PathParam("stackName", stackName);
            request.QueryParam("compareTo", compareTo);
            request.Produces("application/json");
            return this.client.Call<ListDiscoveredStackResourcesResponse>(request);
        }

        public ListTeamsByInsightsAccountResponse ListInsightsAccountTeams(string orgName, string accountName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ListInsightsAccountTeams");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ListInsightsAccountTeams");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/teams");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.Produces("application/json");
            return this.client.Call<ListTeamsByInsightsAccountResponse>(request);
        }

        public ListPolicyPacksForInsightsAccountResponse ListPolicyPacksForAccount(string orgName, string accountName, string continuationToken) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ListPolicyPacksForAccount");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ListPolicyPacksForAccount");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/policy/packs");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.QueryParam("continuationToken", continuationToken);
            request.Produces("application/json");
            return this.client.Call<ListPolicyPacksForInsightsAccountResponse>(request);
        }

        public ListInsightsResourceStackEdgesResponse ListResourceStackEdges(string orgName, string accountName, string resourceTypeAndId) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ListResourceStackEdges");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ListResourceStackEdges");
            }
            if (resourceTypeAndId == null) {
                throw new ArgumentNullException(nameof(resourceTypeAndId), "Missing required parameter 'resourceTypeAndId' when calling ListResourceStackEdges");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/stack_edges");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.PathParam("resourceTypeAndId", resourceTypeAndId);
            request.Produces("application/json");
            return this.client.Call<ListInsightsResourceStackEdgesResponse>(request);
        }

        public ListInsightsResourceVersionEdgesResponse ListResourceVersionEdges(string orgName, string accountName, string resourceTypeAndId, string continuationToken, long? count) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ListResourceVersionEdges");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ListResourceVersionEdges");
            }
            if (resourceTypeAndId == null) {
                throw new ArgumentNullException(nameof(resourceTypeAndId), "Missing required parameter 'resourceTypeAndId' when calling ListResourceVersionEdges");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/edges");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.PathParam("resourceTypeAndId", resourceTypeAndId);
            request.QueryParam("continuationToken", continuationToken);
            request.QueryParam("count", count);
            request.Produces("application/json");
            return this.client.Call<ListInsightsResourceVersionEdgesResponse>(request);
        }

        public ListInsightsResourceVersionEdgesResponse ListResourceVersionEdges_versions(string orgName, string accountName, string resourceTypeAndId, long resourceVersion, string continuationToken, long? count) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ListResourceVersionEdges_versions");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ListResourceVersionEdges_versions");
            }
            if (resourceTypeAndId == null) {
                throw new ArgumentNullException(nameof(resourceTypeAndId), "Missing required parameter 'resourceTypeAndId' when calling ListResourceVersionEdges_versions");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/versions/{resourceVersion}/edges");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.PathParam("resourceTypeAndId", resourceTypeAndId);
            request.PathParam("resourceVersion", resourceVersion);
            request.QueryParam("continuationToken", continuationToken);
            request.QueryParam("count", count);
            request.Produces("application/json");
            return this.client.Call<ListInsightsResourceVersionEdgesResponse>(request);
        }

        public ListInsightsResourceVersionsResponse ListResourceVersions(string orgName, string accountName, string resourceTypeAndId, string continuationToken, long? count) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ListResourceVersions");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ListResourceVersions");
            }
            if (resourceTypeAndId == null) {
                throw new ArgumentNullException(nameof(resourceTypeAndId), "Missing required parameter 'resourceTypeAndId' when calling ListResourceVersions");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/versions");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.PathParam("resourceTypeAndId", resourceTypeAndId);
            request.QueryParam("continuationToken", continuationToken);
            request.QueryParam("count", count);
            request.Produces("application/json");
            return this.client.Call<ListInsightsResourceVersionsResponse>(request);
        }

        public System.Collections.Generic.List<InsightsResourceWithReferences> ListResourcesWithReferences(string orgName, string accountName, ListResourcesWithReferencesRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ListResourcesWithReferences");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ListResourcesWithReferences");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling ListResourcesWithReferences");
            }
            var apiRequest = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/references");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("accountName", accountName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            apiRequest.Produces("application/json");
            return this.client.Call<System.Collections.Generic.List<InsightsResourceWithReferences>>(apiRequest);
        }

        public ListScanStatusResponse ListScanStatus(string orgName, string accountName, string continuationToken, long? pageSize) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ListScanStatus");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ListScanStatus");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/scans");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.QueryParam("continuationToken", continuationToken);
            request.QueryParam("pageSize", pageSize);
            request.Produces("application/json");
            return this.client.Call<ListScanStatusResponse>(request);
        }

        public void PauseScheduledScans(string orgName, string accountName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling PauseScheduledScans");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling PauseScheduledScans");
            }
            var request = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/scan/pause");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            this.client.Call(request);
        }

        public ReadInsightsAccountResponse ReadAccount(string orgName, string accountName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ReadAccount");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ReadAccount");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.Produces("application/json");
            return this.client.Call<ReadInsightsAccountResponse>(request);
        }

        public InsightsResourceWithVersion ReadResource(string orgName, string accountName, string resourceTypeAndId) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ReadResource");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ReadResource");
            }
            if (resourceTypeAndId == null) {
                throw new ArgumentNullException(nameof(resourceTypeAndId), "Missing required parameter 'resourceTypeAndId' when calling ReadResource");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.PathParam("resourceTypeAndId", resourceTypeAndId);
            request.Produces("application/json");
            return this.client.Call<InsightsResourceWithVersion>(request);
        }

        public InsightsResourceWithReferences ReadResourceWithReferences(string orgName, string accountName, string resourceTypeAndId) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ReadResourceWithReferences");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ReadResourceWithReferences");
            }
            if (resourceTypeAndId == null) {
                throw new ArgumentNullException(nameof(resourceTypeAndId), "Missing required parameter 'resourceTypeAndId' when calling ReadResourceWithReferences");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/references");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.PathParam("resourceTypeAndId", resourceTypeAndId);
            request.Produces("application/json");
            return this.client.Call<InsightsResourceWithReferences>(request);
        }

        public InsightsResourceWithVersion ReadResource_versions(string orgName, string accountName, string resourceTypeAndId, string resourceVersion) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ReadResource_versions");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ReadResource_versions");
            }
            if (resourceTypeAndId == null) {
                throw new ArgumentNullException(nameof(resourceTypeAndId), "Missing required parameter 'resourceTypeAndId' when calling ReadResource_versions");
            }
            if (resourceVersion == null) {
                throw new ArgumentNullException(nameof(resourceVersion), "Missing required parameter 'resourceVersion' when calling ReadResource_versions");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/versions/{resourceVersion}");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.PathParam("resourceTypeAndId", resourceTypeAndId);
            request.PathParam("resourceVersion", resourceVersion);
            request.Produces("application/json");
            return this.client.Call<InsightsResourceWithVersion>(request);
        }

        public ScanStatusResponse ReadScanStatus(string orgName, string accountName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ReadScanStatus");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ReadScanStatus");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/scan");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.Produces("application/json");
            return this.client.Call<ScanStatusResponse>(request);
        }

        public ScheduledInsightsScanSettingsResponse ReadScheduledScanSettings(string orgName, string accountName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ReadScheduledScanSettings");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ReadScheduledScanSettings");
            }
            var request = new ApiRequest("GET", "/api/preview/insights/{orgName}/accounts/{accountName}/scan/settings");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            request.Produces("application/json");
            return this.client.Call<ScheduledInsightsScanSettingsResponse>(request);
        }

        public UserInfo ReassignAccountOwnership(string orgName, string accountName, UserInfo request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ReassignAccountOwnership");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ReassignAccountOwnership");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling ReassignAccountOwnership");
            }
            var apiRequest = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/ownership");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("accountName", accountName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            apiRequest.Produces("application/json");
            return this.client.Call<UserInfo>(apiRequest);
        }

        public void ResumeScheduledScans(string orgName, string accountName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ResumeScheduledScans");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ResumeScheduledScans");
            }
            var request = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/scan/resume");
            request.PathParam("orgName", orgName);
            request.PathParam("accountName", accountName);
            this.client.Call(request);
        }

        public WorkflowRun ScanAccount(string orgName, string accountName, ScanInsightsAccountRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling ScanAccount");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling ScanAccount");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling ScanAccount");
            }
            var apiRequest = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/scan");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("accountName", accountName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            apiRequest.Produces("application/json");
            return this.client.Call<WorkflowRun>(apiRequest);
        }

        public ListOrganizationProjectsResponsev3 SearchStacks(string orgName, AngularGridGetRowsRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling SearchStacks");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling SearchStacks");
            }
            var apiRequest = new ApiRequest("POST", "/api/console/orgs/{orgName}/stacks/search");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            apiRequest.Produces("application/json");
            return this.client.Call<ListOrganizationProjectsResponsev3>(apiRequest);
        }

        public void SetInsightAccountTags(string orgName, string accountName, SetInsightAccountTagsRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling SetInsightAccountTags");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling SetInsightAccountTags");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling SetInsightAccountTags");
            }
            var apiRequest = new ApiRequest("PUT", "/api/preview/insights/{orgName}/accounts/{accountName}/tags");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("accountName", accountName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            this.client.Call(apiRequest);
        }

        public void TerminateInsightsTrial(string orgName) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling TerminateInsightsTrial");
            }
            var request = new ApiRequest("PUT", "/api/preview/insights/{orgName}/insightstrial/deny");
            request.PathParam("orgName", orgName);
            this.client.Call(request);
        }

        public void UpdateAccount(string orgName, string accountName, UpdateInsightsAccountRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling UpdateAccount");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling UpdateAccount");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling UpdateAccount");
            }
            var apiRequest = new ApiRequest("PATCH", "/api/preview/insights/{orgName}/accounts/{accountName}");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("accountName", accountName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            this.client.Call(apiRequest);
        }

        public void UpdateResourceVersionPolicyResults(string orgName, string accountName, string resourceTypeAndId, string resourceVersion, UpdateInsightsResourceVersionPolicyResultsRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling UpdateResourceVersionPolicyResults");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling UpdateResourceVersionPolicyResults");
            }
            if (resourceTypeAndId == null) {
                throw new ArgumentNullException(nameof(resourceTypeAndId), "Missing required parameter 'resourceTypeAndId' when calling UpdateResourceVersionPolicyResults");
            }
            if (resourceVersion == null) {
                throw new ArgumentNullException(nameof(resourceVersion), "Missing required parameter 'resourceVersion' when calling UpdateResourceVersionPolicyResults");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling UpdateResourceVersionPolicyResults");
            }
            var apiRequest = new ApiRequest("PUT", "/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/versions/{resourceVersion}/policy/results");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("accountName", accountName);
            apiRequest.PathParam("resourceTypeAndId", resourceTypeAndId);
            apiRequest.PathParam("resourceVersion", resourceVersion);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            this.client.Call(apiRequest);
        }

        public void UpdateScheduledScanSettings(string orgName, string accountName, ScheduledInsightsScanSettingsRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling UpdateScheduledScanSettings");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling UpdateScheduledScanSettings");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling UpdateScheduledScanSettings");
            }
            var apiRequest = new ApiRequest("PUT", "/api/preview/insights/{orgName}/accounts/{accountName}/scan/settings");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("accountName", accountName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            this.client.Call(apiRequest);
        }

        public void UpdateStackPolicyResults(string orgName, string projectName, string stackName, long version, UpdateStackPolicyResultsRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling UpdateStackPolicyResults");
            }
            if (projectName == null) {
                throw new ArgumentNullException(nameof(projectName), "Missing required parameter 'projectName' when calling UpdateStackPolicyResults");
            }
            if (stackName == null) {
                throw new ArgumentNullException(nameof(stackName), "Missing required parameter 'stackName' when calling UpdateStackPolicyResults");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling UpdateStackPolicyResults");
            }
            var apiRequest = new ApiRequest("PUT", "/api/preview/insights/{orgName}/policy/stacks/{projectName}/{stackName}/updates/{version}/results");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("projectName", projectName);
            apiRequest.PathParam("stackName", stackName);
            apiRequest.PathParam("version", version);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            this.client.Call(apiRequest);
        }

        public void UpdateTeamInsightsAccountPermissions(string orgName, string accountName, string teamName, UpdateTeamInsightsAccountPermissionsRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling UpdateTeamInsightsAccountPermissions");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling UpdateTeamInsightsAccountPermissions");
            }
            if (teamName == null) {
                throw new ArgumentNullException(nameof(teamName), "Missing required parameter 'teamName' when calling UpdateTeamInsightsAccountPermissions");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling UpdateTeamInsightsAccountPermissions");
            }
            var apiRequest = new ApiRequest("PATCH", "/api/preview/insights/{orgName}/accounts/{accountName}/teams/{teamName}");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("accountName", accountName);
            apiRequest.PathParam("teamName", teamName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            this.client.Call(apiRequest);
        }

        public void UpsertResourceMigrationAnnotation(string orgName, string projectName, string stackName, UpsertResourceMigrationAnnotationRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling UpsertResourceMigrationAnnotation");
            }
            if (projectName == null) {
                throw new ArgumentNullException(nameof(projectName), "Missing required parameter 'projectName' when calling UpsertResourceMigrationAnnotation");
            }
            if (stackName == null) {
                throw new ArgumentNullException(nameof(stackName), "Missing required parameter 'stackName' when calling UpsertResourceMigrationAnnotation");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling UpsertResourceMigrationAnnotation");
            }
            var apiRequest = new ApiRequest("PUT", "/api/preview/insights/{orgName}/discovered-stacks/{projectName}/{stackName}/migration");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("projectName", projectName);
            apiRequest.PathParam("stackName", stackName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            this.client.Call(apiRequest);
        }

        public void UpsertResources(string orgName, string accountName, UpsertInsightsResourcesRequest request) {
            if (orgName == null) {
                throw new ArgumentNullException(nameof(orgName), "Missing required parameter 'orgName' when calling UpsertResources");
            }
            if (accountName == null) {
                throw new ArgumentNullException(nameof(accountName), "Missing required parameter 'accountName' when calling UpsertResources");
            }
            if (request == null) {
                throw new ArgumentNullException(nameof(request), "Missing required parameter 'request' when calling UpsertResources");
            }
            var apiRequest = new ApiRequest("POST", "/api/preview/insights/{orgName}/accounts/{accountName}/resources");
            apiRequest.PathParam("orgName", orgName);
            apiRequest.PathParam("accountName", accountName);
            apiRequest.Body(request);
            apiRequest.Consumes("application/json");
            this.client.Call(apiRequest);
        }
    }
}
