// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class AgentSignupRequest {
    // An ID identifying the challenge issued by GET /api/agents/signup/challenge.
    public String challengeID;

    // Output of the proof-of-work computation over the challengeData returned by GET /api/agents/signup/challenge.
    public String challengeResult;
}
