// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class AgentAccountSummary {
    // The agent user's Pulumi login (e.g. "agent-abc123"). This is what pulumi whoami returns while the agent's access token is in use.
    public String login;

    // Slug of the agent's individual organization. This appears in the <org>/<project>/<stack> identity of any stack the agent created.
    public String orgName;

    // When the agent account was created (i.e. when /api/agents/signup ran).
    public ZonedDateTime createdAt;
}
