// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class AgentTask {
    // Unique identifier for the task.
    public String id;

    // Display name for the task, typically auto-generated from the initial user message.
    public String name;

    // Whether the task was started synchronously by a user or asynchronously by background automation.
    public AgentTaskType taskType;

    // The async trigger source for this task. Null for sync tasks.
    public AgentAsyncTriggerType asyncTriggerType;

    // Current execution status of the task.
    public AgentTaskStatus status;

    // When the task was created, in ISO 8601 format.
    public ZonedDateTime createdAt;

    // Approval mode for this task. Valid values: 'manual', 'auto', 'balanced'.
    public NeoApprovalMode approvalMode;

    // Pulumi entities (stacks, projects, etc.) that provide context for the agent.
    public List<AgentEntity> entities;

    // Whether the task is in plan mode. Set based on the first user message.
    public boolean planMode;

    // Whether this task is shared with other org members.
    public boolean isShared;

    // When the task was first shared. Null if never shared.
    public ZonedDateTime sharedAt;

    // Information about the user who created this task.
    public UserInfo createdBy;

    // The permission scope for the task.
    public NeoPermissionMode permissionMode;

    // The id of the RBAC role this task assumes. Null when the task runs with the creating user's own permissions (no assumed role).
    public String role;

    // The display name of the RBAC role this task assumes. Null when the task has no assumed role or the role no longer exists.
    public String roleName;

    // The current runtime phase for this task. Null until the runtime checks in.
    public AgentTaskRuntimePhase runtimePhase;

    // When the task runtime last reported a heartbeat. Null if the runtime has never checked in.
    public ZonedDateTime lastHeartbeat;

    // Total input tokens consumed across all model invocations for this task. Approximate context window usage.
    public int contextUsedTokens;

    // Maximum context window size in tokens for the primary model used by this task.
    public int contextWindowTokens;

    // Percentage of the context window (1-100) at which the agent triggers conversation compaction. Populated alongside contextWindowTokens when token usage data is available; omitted otherwise.
    public int contextCompactionThresholdPercent;

    // Total Neo tokens consumed across all model invocations for this task. Neo tokens are the priced unit used for billing — distinct from the raw model input tokens surfaced in contextUsedTokens / contextWindowTokens.
    public long tokensUsed;

    // Where tools are executed for this task. Valid values: 'cloud', 'cli'.
    public ToolExecutionMode toolExecutionMode;

    // The automation that spawned this task, if the task was created by an automation run.
    public String sourceAutomationID;

    // The Custom Agent definition this task was run as, if any. Null for tasks run by a user directly rather than as a saved agent.
    public String agentDefinitionId;

    // The origin that triggered this task. Valid values: 'console', 'cli', 'slack', 'schedule', 'api', 'github', 'code-review'.
    public AgentTaskSource source;

    // The version control system this task operates against. Set for tasks that target a specific VCS platform (e.g. code reviews). Null for tasks with no VCS context.
    public VCSProvider vcsProvider;
}
