// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.util.Arrays;
import com.fasterxml.jackson.annotation.*;

public enum AppOperationResult {
    // OperationResultSucceeded indicates the operation completed without error.
    Succeeded("succeeded"),
    // OperationResultFailed indicates the operation returned an error.
    Failed("failed"),
    // OperationResultCanceled indicates the operation was canceled by the user.
    Canceled("canceled");

    private final String value;

    AppOperationResult(String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static AppOperationResult fromValue(String v) {
        for (var b : AppOperationResult.values()) {
            if (String.valueOf(b.value).equals(v)) {
                return b;
            }
        }

        throw new IllegalArgumentException(String.format("'%s' is not one of the values accepted for %s class: %s", v, AppOperationResult.class.getSimpleName(), Arrays.toString(AppOperationResult.values())));
    }
}
