// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

import java.util.Arrays;
import com.fasterxml.jackson.annotation.*;

@javax.annotation.processing.Generated("pulumi-codegen")
public enum AppOperationType {
    // OperationTypeCreating is the state of resources that are being created.
    Creating("creating"),
    // OperationTypeUpdating is the state of resources that are being updated.
    Updating("updating"),
    // OperationTypeDeleting is the state of resources that are being deleted.
    Deleting("deleting"),
    // OperationTypeReading is the state of resources that are being read.
    Reading("reading");

    private final String value;

    AppOperationType(String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static AppOperationType fromValue(String v) {
        for (var b : AppOperationType.values()) {
            if (String.valueOf(b.value).equals(v)) {
                return b;
            }
        }

        throw new IllegalArgumentException(String.format("'%s' is not one of the values accepted for %s class: %s", v, AppOperationType.class.getSimpleName(), Arrays.toString(AppOperationType.values())));
    }
}
