// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.util.Arrays;
import com.fasterxml.jackson.annotation.*;

public enum AppOpType {
    // OpSame indicates no change was made.
    OpSame("same"),
    // OpCreate indicates a new resource was created.
    OpCreate("create"),
    // OpUpdate indicates an existing resource was updated.
    OpUpdate("update"),
    // OpDelete indicates an existing resource was deleted.
    OpDelete("delete"),
    // OpReplace indicates an existing resource was replaced with a new one.
    OpReplace("replace"),
    // OpCreateReplacement indicates a new resource was created for a replacement.
    OpCreateReplacement("create-replacement"),
    // OpDeleteReplaced indicates an existing resource was deleted after replacement.
    OpDeleteReplaced("delete-replaced"),
    // OpRead indicates reading an existing resource.
    OpRead("read"),
    // OpReadReplacement indicates reading an existing resource for a replacement.
    OpReadReplacement("read-replacement"),
    // OpRefresh indicates refreshing an existing resource.
    OpRefresh("refresh"),
    // OpReadDiscard indicates removing a resource that was read.
    OpReadDiscard("discard"),
    // OpDiscardReplaced indicates discarding a read resource that was replaced.
    OpDiscardReplaced("discard-replaced"),
    // OpRemovePendingReplace indicates removing a pending replace resource.
    OpRemovePendingReplace("remove-pending-replace"),
    // OpImport indicates importing an existing resource.
    OpImport("import"),
    // OpImportReplacement indicates replacement of an existing resource with an imported resource.
    OpImportReplacement("import-replacement");

    private final String value;

    AppOpType(String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static AppOpType fromValue(String v) {
        for (var b : AppOpType.values()) {
            if (String.valueOf(b.value).equals(v)) {
                return b;
            }
        }

        throw new IllegalArgumentException(String.format("'%s' is not one of the values accepted for %s class: %s", v, AppOpType.class.getSimpleName(), Arrays.toString(AppOpType.values())));
    }
}
