// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@javax.annotation.processing.Generated("pulumi-codegen")
public class AppRenewUpdateLeaseRequest {
    // The current, valid lease token. DEPRECATED as of Pulumi API version 5+. Pulumi API will expect the update token in the Authorization header instead of this property. This property will be removed when the minimum supported API version on the service is raised to 5.
    public String token;

    // The duration for which to renew the lease in seconds (maximum 300).
    public Long duration;
}
