// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@javax.annotation.processing.Generated("pulumi-codegen")
public class AppResCustomTimeouts {
    // Timeout in seconds for resource creation operations.
    public double create;

    // Timeout in seconds for resource update operations.
    public double update;

    // Timeout in seconds for resource deletion operations.
    public double delete;

    // Timeout in seconds for resource read operations.
    public double read;
}
