// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@JsonTypeName("status_changed")
public class ChangeRequestStatusChangedEvent extends ChangeRequestEvent {
    // The status the change request transitioned to
    public String newStatus;

    // The status the change request transitioned from
    public String previousStatus;

    // Why the status changed
    public String reason;
}
