// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.util.Arrays;
import com.fasterxml.jackson.annotation.*;

public enum DefaultIdentifier {
    Member("member"),
    Admin("admin"),
    BillingManager("billing-manager"),
    StackRead("stack-read"),
    StackWrite("stack-write"),
    StackAdmin("stack-admin"),
    EnvironmentRead("environment-read"),
    EnvironmentWrite("environment-write"),
    EnvironmentAdmin("environment-admin"),
    EnvironmentOpen("environment-open"),
    InsightsAccountRead("insights-account-read"),
    InsightsAccountWrite("insights-account-write"),
    InsightsAccountAdmin("insights-account-admin");

    private final String value;

    DefaultIdentifier(String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static DefaultIdentifier fromValue(String v) {
        for (var b : DefaultIdentifier.values()) {
            if (String.valueOf(b.value).equals(v)) {
                return b;
            }
        }

        throw new IllegalArgumentException(String.format("'%s' is not one of the values accepted for %s class: %s", v, DefaultIdentifier.class.getSimpleName(), Arrays.toString(DefaultIdentifier.values())));
    }
}
