// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@javax.annotation.processing.Generated("pulumi-codegen")
@JsonTypeName("DeploymentLogsStep")
public class DeploymentLogsStep extends DeploymentLogsBase {
    // The name of the step.
    public String name;

    // The step's log lines.
    public List<DeploymentStepLogLine> lines;

    // The next offset at which to fetch lines. When this field is nil, there are no more lines to fetch.
    public Long nextOffset;
}
