// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@javax.annotation.processing.Generated("pulumi-codegen")
public class DeploymentJob {
    // The current execution status of this job. A deployment reports the status of its job, so this is normally the same value as the deployment's own `status`.
    public JobStatus status;

    // The timestamp when the job started.
    public ZonedDateTime started;

    // The timestamp when the job was last updated.
    public ZonedDateTime lastUpdated;

    // The list of steps in the deployment job.
    public List<StepRun> steps;
}
