// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class EnvironmentRevisionRetracted {
    // The revision number that replaced this retracted revision.
    public Long replacement;

    // The timestamp when the revision was retracted.
    public ZonedDateTime at;

    // The login name of the user who retracted the revision.
    public String byLogin;

    // The display name of the user who retracted the revision.
    public String byName;

    // The reason the revision was retracted.
    public String reason;
}
