// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@javax.annotation.processing.Generated("pulumi-codegen")
public class GetTemplateReadmeResponse {
    // The resolved semantic version of the template.
    public String version;

    // The language the content was filtered for, if a language filter was applied.
    public String language;

    // The operating system the content was filtered for, if an OS filter was applied.
    public String os;

    // Ordered list of content nodes composing the README document.
    public List<RegistryContentNode> content;
}
