// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@javax.annotation.processing.Generated("pulumi-codegen")
public class GitHubAppURLs {
    // URL to install the GitHub App
    public String installationUrl;

    // URL to configure the GitHub App installation
    public String configurationUrl;

    // URL to manage the GitHub App permissions
    public String permissionsUrl;

    // OAuth state parameter for CSRF protection
    public String stateParam;
}
