// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@javax.annotation.processing.Generated("pulumi-codegen")
public class GitHubEnterpriseAuthorizeURLResponse {
    // The fully-formed GitHub Enterprise OAuth authorization URL, including client_id, redirect_uri, and a signed state parameter.
    public String authorizeUrl;
}
