// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "op")
@JsonSubTypes({
    @JsonSubTypes.Type(value = GraphFieldPredicate.Absent.class),
    @JsonSubTypes.Type(value = GraphFieldPredicate.Eq.class),
    @JsonSubTypes.Type(value = GraphFieldPredicate.Gt.class),
    @JsonSubTypes.Type(value = GraphFieldPredicate.Gte.class),
    @JsonSubTypes.Type(value = GraphFieldPredicate.In.class),
    @JsonSubTypes.Type(value = GraphFieldPredicate.Lt.class),
    @JsonSubTypes.Type(value = GraphFieldPredicate.Lte.class),
    @JsonSubTypes.Type(value = GraphFieldPredicate.Present.class)
})
public abstract class GraphFieldPredicate {

    @JsonTypeName("absent")
    public static class Absent extends GraphFieldPredicate {
    }

    @JsonTypeName("eq")
    public static class Eq extends GraphFieldPredicate {
        // The value to compare against. The empty string is rejected with a 400. On 'provider_version' the value is compared as a semantic version.
        public String value;
    }

    @JsonTypeName("gt")
    public static class Gt extends GraphFieldPredicate {
        // The exclusive lower bound. The empty string is rejected with a 400.
        public String value;
    }

    @JsonTypeName("gte")
    public static class Gte extends GraphFieldPredicate {
        // The inclusive lower bound. The empty string is rejected with a 400.
        public String value;
    }

    @JsonTypeName("in")
    public static class In extends GraphFieldPredicate {
        // The values to compare against; matching any one of them matches the predicate. Must be non-empty. On 'provider_version' each value is compared as a semantic version.
        public List<String> values;
    }

    @JsonTypeName("lt")
    public static class Lt extends GraphFieldPredicate {
        // The exclusive upper bound. The empty string is rejected with a 400.
        public String value;
    }

    @JsonTypeName("lte")
    public static class Lte extends GraphFieldPredicate {
        // The inclusive upper bound. The empty string is rejected with a 400.
        public String value;
    }

    @JsonTypeName("present")
    public static class Present extends GraphFieldPredicate {
    }
}
