// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class GraphQueryAnchor {
    // The node type to select.
    public GraphNodeType nodeType;

    // Structured predicate over node attributes. Omit it, and 'query' with it, to select every node of the given type.
    public GraphNodeMatch match;

    // A resource search query string in the Pulumi resource search syntax, as an alternative to 'match'. Only valid for the 'resource' node type.
    public String query;

    // Maximum number of anchor nodes to resolve, up to the engine's anchor cap. When more match, the result is reported as meta.resultMode 'truncated'. Omitting this, or naming a value above the cap, leaves the bound to the engine — and a query that also traverses is then rejected rather than truncated.
    public Long limit;
}
