// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

import java.util.Arrays;
import com.fasterxml.jackson.annotation.*;

@javax.annotation.processing.Generated("pulumi-codegen")
public enum GraphTraverseDirection {
    // Walk edges against their orientation: the current frontier is the edge destination, and the walk reaches edge sources.
    In("in"),
    // Walk edges along their orientation: the current frontier is the edge source, and the walk reaches edge destinations.
    Out("out"),
    // Walk edges in both directions.
    Both("both");

    private final String value;

    GraphTraverseDirection(String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static GraphTraverseDirection fromValue(String v) {
        for (var b : GraphTraverseDirection.values()) {
            if (String.valueOf(b.value).equals(v)) {
                return b;
            }
        }

        throw new IllegalArgumentException(String.format("'%s' is not one of the values accepted for %s class: %s", v, GraphTraverseDirection.class.getSimpleName(), Arrays.toString(GraphTraverseDirection.values())));
    }
}
