// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

@javax.annotation.processing.Generated("pulumi-codegen")
public class HeadersForEnvironmentOp {
    // Opaque revision tag for the environment definition. Include this value in the If-Match header of a later update or decrypt request to enforce optimistic concurrency control.
    public final String eTag;
    // The numeric revision number of the environment definition returned in this response.
    public final long pulumiESCRevision;

    public HeadersForEnvironmentOp(String eTag, long pulumiESCRevision) {
        this.eTag = eTag;
        this.pulumiESCRevision = pulumiESCRevision;
    }
}
