// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class InsightsResourceVersionEdge {
    // The source resource URN
    public String sourceUrn;

    // The source resource version
    public Long sourceVersion;

    // The destination resource URN
    public String destUrn;

    // The type of edge relationship
    public String edgeType;
}
