// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class ListScanStatusResponse {
    // The list of scan statuses
    public List<ScanStatus> scanStatuses;

    // ContinuationToken is an opaque value the client can send to fetch additional scans. Will be nil once all scans have been returned.
    public String continuationToken;
}
