// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class ListStackCollaboratorsResponse {
    // Other users explicitly added as collaborators on this stack. (Those inheriting permissions from the org aren't included.)
    public List<UserPermission> users;

    // StackCreatorUserName is the user name of the stack creator. If stack creator's permissions have been removed then this will be null and will be omitted from the json response.
    public String stackCreatorUserName;
}
