// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class OidcIssuerRegistrationRequest {
    // The display name of the OIDC issuer.
    public String name;

    // The URL of the OIDC issuer.
    public String url;

    // SHA-1 certificate thumbprints used to verify the OIDC issuer's TLS certificate.
    public List<String> thumbprints;

    // The maximum token expiration time in seconds.
    public Long maxExpiration;

    // The JSON Web Key Set for the OIDC issuer.
    public JSONWebKeySet jwks;
}
