// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.util.Arrays;
import com.fasterxml.jackson.annotation.*;

public enum OrganizationRole {
    // OrganizationRoleNone describes the role of non-members.
    None("none"),
    // OrganizationRoleMember is the role for regular members.
    Member("member"),
    // OrganizationRoleAdmin is the role for admins.
    Admin("admin"),
    // OrganizationRolePotentialMember is the role for users who are explicitly not a member of the organization, but are a member of the backing org on the 3rd party identity provider. (i.e. they could join the org.)
    PotentialMember("potential-member"),
    // OrganizationRoleStackCollaborator is the role for users who are not a member of an organization, but have been explicitly granted access to some of the organization's stacks. So they have limited permissions to access the org's data.
    StackCollaborator("stack-collaborator"),
    // OrganizationRoleBillingManager is the role for billing admins.
    BillingManager("billing-manager");

    private final String value;

    OrganizationRole(String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static OrganizationRole fromValue(String v) {
        for (var b : OrganizationRole.values()) {
            if (String.valueOf(b.value).equals(v)) {
                return b;
            }
        }

        throw new IllegalArgumentException(String.format("'%s' is not one of the values accepted for %s class: %s", v, OrganizationRole.class.getSimpleName(), Arrays.toString(OrganizationRole.values())));
    }
}
