// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@javax.annotation.processing.Generated("pulumi-codegen")
public class PulumiProject {
    // The name of the organization that owns this project.
    public String orgName;

    // The repository name this project belongs to.
    public String repoName;

    // The name of the project.
    public String name;

    // Optional project-level settings.
    public PulumiProjectSettings settings;

    // Optional tags from Pulumi.yaml.
    public String runtime;

    // The project description from Pulumi.yaml.
    public String description;

    // The stacks belonging to this project.
    public List<PulumiStack> stacks;
}
