// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class RegistryExample {
    // Stable identifier within the package version. Format: '<typeToken>#<slug>', where slug is the kebab-case title (e.g. 'aws:ec2/instance:Instance#account-analyzer'), falling back to 'example-<short-hash>' when there is no heading. Duplicates within the same type token are suffixed '-2', '-3', etc.
    public String id;

    // Title derived from the surrounding heading or caption. Capped at 120 chars. Empty when none was available; rely on 'id' for addressability.
    public String title;

    // Example source code in the resolved language.
    public String code;

    // Pulumi type token this example belongs to.
    public String typeToken;

    // Whether 'typeToken' is a 'resource' or 'function'.
    public String kind;
}
