// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class RegistryDocsSupportingType {
    // Pulumi type token of this type.
    public String typeToken;

    // Display name keyed by language.
    public Map<String, String> name;

    // 'object' or 'enum'.
    public String kind;

    // Properties (when kind is 'object').
    public List<RegistryDocsProperty> properties;

    // Enum values (when kind is 'enum').
    public List<RegistryDocsEnumValue> values;
}
