// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class SecretRotationEvent {
    // The unique identifier for this rotation event.
    public String id;

    // The ID of the environment being rotated.
    public String environmentId;

    // The timestamp when this rotation event was created.
    public ZonedDateTime created;

    // The environment revision before the rotation.
    public Long preRotationRevision;

    // The environment revision after the rotation, if completed.
    public Long postRotationRevision;

    // The ID of the user who initiated the rotation.
    public String userID;

    // The timestamp when the rotation completed.
    public ZonedDateTime completed;

    // The current status of the rotation event.
    public String status;

    // The ID of the scheduled action that triggered this rotation, if any.
    public String scheduledActionID;

    // An error message if the rotation failed.
    public String errorMessage;

    // The individual secret rotations within this event.
    public List<SecretRotation> rotations;
}
