// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class StackOverviewResponse {
    // The tags associated with this stack.
    public Map<String, String> tags;

    // The list of stacks referenced by this stack.
    public List<StackReference> referencedStacks;

    // The resources belonging to this stack.
    public GetStackResourcesResponse resources;
}
