// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class Team {
    // The kind of team (e.g., pulumi or GitHub-backed).
    public TeamKind kind;

    // The unique identifier name of the team within the organization.
    public String name;

    // The human-readable display name shown in the UI.
    public String displayName;

    // A free-form text description of the team's purpose.
    public String description;

    // The list of team members.
    public List<TeamMemberInfo> members;

    // The list of stack permissions granted to the team.
    public List<TeamStackPermission> stacks;

    // The list of environment settings for the team.
    public List<TeamEnvironmentSettings> environments;

    // The list of account permissions granted to the team.
    public List<TeamAccountPermission> accounts;

    // ListMembersError is the error message if an error was encountered whilst trying to contact the team's backend (eg. GitHub). The UI will only show this error if it is non-nil and if Members itself is an empty slice.
    public String listMembersError;

    // UserRole is the calling user's role on the given team.
    public TeamRole userRole;

    // RoleIDs are the IDs of the FGA roles assigned to the team, if any. Currently only one role per team is supported.
    public List<String> roleIds;
}
