// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@JsonSubTypes({
    @JsonSubTypes.Type(value = GetTerraformModuleResponse.class)
})
public class TerraformModuleVersion extends TerraformModule {
    // The semantic version of this module version.
    public String version;

    // The SHA-256 checksum of the module tarball.
    public String sha256;

    // The size of the module tarball in bytes.
    public long sizeBytes;

    // The module README, rendered client-side. Absent when the module ships no README.
    public String readme;

    // The input variables declared by the root module.
    public List<TerraformModuleInput> inputs;

    // The outputs declared by the root module.
    public List<TerraformModuleOutput> outputs;

    // The provider requirements declared by the root module.
    public List<TerraformModuleProviderRequirement> providerRequirements;

    // The submodules (modules/<name>/) shipped alongside the root module.
    public List<TerraformModuleSubmodule> submodules;

    // The examples (examples/<name>/) shipped alongside the root module.
    public List<TerraformModuleExample> examples;

    // The package conversion status for this version. Absent for versions published before conversion was enabled (not backfilled).
    public TerraformModulePackageConversion packageConversion;
}
