// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@javax.annotation.processing.Generated("pulumi-codegen")
public class TransferAllStacksRequest {
    // The source organization to transfer stacks from. Must match the organization in the URL route.
    public String fromOrg;

    // The destination organization to transfer stacks to.
    public String toOrg;
}
