// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class UpdateInsightsAccountRequest {
    // Reference to an ESC environment containing provider credentials, in the format 'project/environment' with an optional @version suffix.
    public String environment;

    // Schedule for automated discovery scans (e.g., 'none', 'daily').
    public ScanSchedule scanSchedule;

    // Provider-specific configuration for the account.
    public JsonNode providerConfig;

    // The ID of the agent pool to run account discovery workflows. If not specified, discovery will use the default agent pool.
    public String agentPoolID;
}
