// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_java' TO REFRESH.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

public class User {
    // The unique identifier of the user.
    public String id;

    // The user's login name (originally from GitHub).
    public String githubLogin;

    // The user's display name.
    public String name;

    // The user's email address.
    public String email;

    // The URL of the user's avatar image.
    public String avatarUrl;

    // Organizations is the list of Pulumi organizations the user is a member of.
    public List<OrganizationSummaryWithRole> organizations;

    // PotentialOrganizations is the list of Pulumi organizations the user is a potential member of.
    public List<OrganizationSummaryWithRole> potentialOrganizations;

    // Identities is the array of identities a Pulumi user's account is tied to.
    public List<IdentityProvider> identities;

    // SiteAdministrator is whether or not the user is a site administrator.
    public Boolean siteAdmin;

    // RegistryAdmin is whether or not the user is a registry administrator.
    public Boolean registryAdmin;

    // TokenInfo is contains metadata, set only for machine tokens & to be used only in the CLI
    public TokenInfo tokenInfo;

    // Whether the user has multi-factor authentication enabled.
    public boolean hasMFA;

    // Whether the user's account is managed by an organization.
    public boolean isOrgManaged;

    // Whether the user's account is managed by multiple organizations.
    public boolean isManagedByMultiOrg;

    // Whether the user is a synthetic agent account. Agent accounts cannot be authenticated except via their issued access token until a human claims the account via the claim URL.
    public boolean isAgent;
}
