// Copyright 2016-2026, Pulumi Corporation.  All rights reserved.
// Code generated by pulumi-codegen. DO NOT EDIT.

package com.pulumi.cloud.sdk.model;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.JsonNode;

@javax.annotation.processing.Generated("pulumi-codegen")
@JsonSubTypes({
    @JsonSubTypes.Type(value = TeamMemberInfo.class)
})
public class UserInfo {
    // The user's display name.
    public String name;

    // The user's login name.
    public String githubLogin;

    // The URL of the user's avatar image.
    public String avatarUrl;

    // The user's email address. It is only populated on selected endpoints and is omitted from most responses. Treat it as sensitive information.
    public String email;
}
