// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export class AgentWorkflowDefinition {
    jobToken: string;
    oidcToken: string;
    typeSpecificID: string;
    deploymentID?: string;
    jobID: string;
    runID: string;

    getFixupPrototypeFunction() {
        return AgentWorkflowDefinition.fixupPrototype;
    }

    static newInstance(model: Partial<AgentWorkflowDefinition>): AgentWorkflowDefinition {
        let obj = Object.assign(new AgentWorkflowDefinition(), model);
        AgentWorkflowDefinition.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<AgentWorkflowDefinition>): AgentWorkflowDefinition | null {
        if (!model) return null;
        return AgentWorkflowDefinition.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: AgentWorkflowDefinition) {
        if (!obj) return;

        AgentWorkflowDefinition.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: AgentWorkflowDefinition): boolean {
        Object.setPrototypeOf(obj, AgentWorkflowDefinition.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        // Nothing to do.
    }
}
