// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import { AgentBackendEvent } from "./AgentBackendEvent";


export class AgentBackendEventExecToolCall extends AgentBackendEvent {
    tool_call_id: string;
    name: string;

    constructor() {
        super();
        this.setDiscriminator("exec_tool_call");
    }

    getFixupPrototypeFunction() {
        return AgentBackendEventExecToolCall.fixupPrototype;
    }

    static newInstance(model: Partial<AgentBackendEventExecToolCall>): AgentBackendEventExecToolCall {
        let obj = Object.assign(new AgentBackendEventExecToolCall(), model);
        AgentBackendEventExecToolCall.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<AgentBackendEventExecToolCall>): AgentBackendEventExecToolCall | null {
        if (!model) return null;
        return AgentBackendEventExecToolCall.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: AgentBackendEventExecToolCall) {
        if (!obj) return;

        AgentBackendEventExecToolCall.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: AgentBackendEventExecToolCall): boolean {
        if (AgentBackendEvent.setPrototype(obj)) {
            return true; // A polymorphic type, skip overwriting the prototype.
        }
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        super.fixupFields();
    }
}
