// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// Code generated by pulumi-codegen. DO NOT EDIT.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export class AppAppendUpdateLogEntryRequest {
    kind: string;
    fields: { [key: string]: any };

    getFixupPrototypeFunction() {
        return AppAppendUpdateLogEntryRequest.fixupPrototype;
    }

    static newInstance(model: Partial<AppAppendUpdateLogEntryRequest>): AppAppendUpdateLogEntryRequest {
        let obj = Object.assign(new AppAppendUpdateLogEntryRequest(), model);
        AppAppendUpdateLogEntryRequest.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<AppAppendUpdateLogEntryRequest>): AppAppendUpdateLogEntryRequest | null {
        if (!model) return null;
        return AppAppendUpdateLogEntryRequest.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: AppAppendUpdateLogEntryRequest) {
        if (!obj) return;

        AppAppendUpdateLogEntryRequest.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: AppAppendUpdateLogEntryRequest): boolean {
        Object.setPrototypeOf(obj, AppAppendUpdateLogEntryRequest.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        // Nothing to do.
    }
}
