// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export class AppRequiredPolicy {
    name: string;
    version: number;
    versionTag: string;
    displayName: string;
    packLocation?: string;
    config?: { [key: string]: any };
    environments?: string[];

    getFixupPrototypeFunction() {
        return AppRequiredPolicy.fixupPrototype;
    }

    static newInstance(model: Partial<AppRequiredPolicy>): AppRequiredPolicy {
        let obj = Object.assign(new AppRequiredPolicy(), model);
        AppRequiredPolicy.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<AppRequiredPolicy>): AppRequiredPolicy | null {
        if (!model) return null;
        return AppRequiredPolicy.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: AppRequiredPolicy) {
        if (!obj) return;

        AppRequiredPolicy.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: AppRequiredPolicy): boolean {
        Object.setPrototypeOf(obj, AppRequiredPolicy.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.version === undefined) {
            this.version = 0;
        }
    }
}
