// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export class AppUpdateMetadata {
    message: string;
    environment: { [key: string]: string };

    getFixupPrototypeFunction() {
        return AppUpdateMetadata.fixupPrototype;
    }

    static newInstance(model: Partial<AppUpdateMetadata>): AppUpdateMetadata {
        let obj = Object.assign(new AppUpdateMetadata(), model);
        AppUpdateMetadata.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<AppUpdateMetadata>): AppUpdateMetadata | null {
        if (!model) return null;
        return AppUpdateMetadata.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: AppUpdateMetadata) {
        if (!obj) return;

        AppUpdateMetadata.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: AppUpdateMetadata): boolean {
        Object.setPrototypeOf(obj, AppUpdateMetadata.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        // Nothing to do.
    }
}
