// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export class AWSSSOSetupRequest {
    sessionId: string;
    region: string;
    accountId: string;
    accountRoleName: string;
    policyArn: string;
    oidcRoleName: string;
    projectName?: string;
    environmentName?: string;

    getFixupPrototypeFunction() {
        return AWSSSOSetupRequest.fixupPrototype;
    }

    static newInstance(model: Partial<AWSSSOSetupRequest>): AWSSSOSetupRequest {
        let obj = Object.assign(new AWSSSOSetupRequest(), model);
        AWSSSOSetupRequest.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<AWSSSOSetupRequest>): AWSSSOSetupRequest | null {
        if (!model) return null;
        return AWSSSOSetupRequest.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: AWSSSOSetupRequest) {
        if (!obj) return;

        AWSSSOSetupRequest.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: AWSSSOSetupRequest): boolean {
        Object.setPrototypeOf(obj, AWSSSOSetupRequest.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        // Nothing to do.
    }
}
