// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { AzureOptions } from "./AzureOptions";


export class CloudSetupProvider {
    name: string;
    azure?: AzureOptions;

    getFixupPrototypeFunction() {
        return CloudSetupProvider.fixupPrototype;
    }

    static newInstance(model: Partial<CloudSetupProvider>): CloudSetupProvider {
        let obj = Object.assign(new CloudSetupProvider(), model);
        CloudSetupProvider.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<CloudSetupProvider>): CloudSetupProvider | null {
        if (!model) return null;
        return CloudSetupProvider.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: CloudSetupProvider) {
        if (!obj) return;

        CloudSetupProvider.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: CloudSetupProvider): boolean {
        Object.setPrototypeOf(obj, CloudSetupProvider.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.azure) {
            // Lazy import - only evaluated when called
            const { AzureOptions } = require("./AzureOptions");
            AzureOptions.fixupPrototype(this.azure);
        }
    }
}
