// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export class CreateEnvironmentOpenRequest {
    grantExpirationSeconds: number;
    accessDurationSeconds: number;

    getFixupPrototypeFunction() {
        return CreateEnvironmentOpenRequest.fixupPrototype;
    }

    static newInstance(model: Partial<CreateEnvironmentOpenRequest>): CreateEnvironmentOpenRequest {
        let obj = Object.assign(new CreateEnvironmentOpenRequest(), model);
        CreateEnvironmentOpenRequest.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<CreateEnvironmentOpenRequest>): CreateEnvironmentOpenRequest | null {
        if (!model) return null;
        return CreateEnvironmentOpenRequest.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: CreateEnvironmentOpenRequest) {
        if (!obj) return;

        CreateEnvironmentOpenRequest.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: CreateEnvironmentOpenRequest): boolean {
        Object.setPrototypeOf(obj, CreateEnvironmentOpenRequest.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.grantExpirationSeconds === undefined) {
            this.grantExpirationSeconds = 0;
        }
        if (this.accessDurationSeconds === undefined) {
            this.accessDurationSeconds = 0;
        }
    }
}
