// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import { BaseCreateAccessTokenRequest } from "./BaseCreateAccessTokenRequest";


export class CreatePersonalAccessTokenRequest extends BaseCreateAccessTokenRequest {
    getFixupPrototypeFunction() {
        return CreatePersonalAccessTokenRequest.fixupPrototype;
    }

    static newInstance(model: Partial<CreatePersonalAccessTokenRequest>): CreatePersonalAccessTokenRequest {
        let obj = Object.assign(new CreatePersonalAccessTokenRequest(), model);
        CreatePersonalAccessTokenRequest.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<CreatePersonalAccessTokenRequest>): CreatePersonalAccessTokenRequest | null {
        if (!model) return null;
        return CreatePersonalAccessTokenRequest.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: CreatePersonalAccessTokenRequest) {
        if (!obj) return;

        CreatePersonalAccessTokenRequest.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: CreatePersonalAccessTokenRequest): boolean {
        if (BaseCreateAccessTokenRequest.setPrototype(obj)) {
            return true; // A polymorphic type, skip overwriting the prototype.
        }
        Object.setPrototypeOf(obj, CreatePersonalAccessTokenRequest.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        super.fixupFields();
    }
}
