// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export enum DefaultIdentifier {
    Member = "member",
    Admin = "admin",
    BillingManager = "billing-manager",
    StackRead = "stack-read",
    StackWrite = "stack-write",
    StackAdmin = "stack-admin",
    EnvironmentRead = "environment-read",
    EnvironmentWrite = "environment-write",
    EnvironmentAdmin = "environment-admin",
    EnvironmentOpen = "environment-open",
    InsightsAccountRead = "insights-account-read",
    InsightsAccountWrite = "insights-account-write",
    InsightsAccountAdmin = "insights-account-admin",
}
