// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// Code generated by pulumi-codegen. DO NOT EDIT.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export class DeploymentStepLogLine {
    timestamp: Date;
    line: string;

    getFixupPrototypeFunction() {
        return DeploymentStepLogLine.fixupPrototype;
    }

    static newInstance(model: Partial<DeploymentStepLogLine>): DeploymentStepLogLine {
        let obj = Object.assign(new DeploymentStepLogLine(), model);
        DeploymentStepLogLine.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<DeploymentStepLogLine>): DeploymentStepLogLine | null {
        if (!model) return null;
        return DeploymentStepLogLine.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: DeploymentStepLogLine) {
        if (!obj) return;

        DeploymentStepLogLine.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: DeploymentStepLogLine): boolean {
        Object.setPrototypeOf(obj, DeploymentStepLogLine.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (typeof this.timestamp === "string") {
            this.timestamp = new Date(this.timestamp);
        }
    }
}
