// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export class DeploymentSourceTemplate {
    sourceUrl: string;

    getFixupPrototypeFunction() {
        return DeploymentSourceTemplate.fixupPrototype;
    }

    static newInstance(model: Partial<DeploymentSourceTemplate>): DeploymentSourceTemplate {
        let obj = Object.assign(new DeploymentSourceTemplate(), model);
        DeploymentSourceTemplate.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<DeploymentSourceTemplate>): DeploymentSourceTemplate | null {
        if (!model) return null;
        return DeploymentSourceTemplate.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: DeploymentSourceTemplate) {
        if (!obj) return;

        DeploymentSourceTemplate.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: DeploymentSourceTemplate): boolean {
        Object.setPrototypeOf(obj, DeploymentSourceTemplate.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        // Nothing to do.
    }
}
