// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { DeploymentSource } from "./DeploymentSource";
import type { EnvironmentVariable } from "./EnvironmentVariable";


export class DeploymentConfiguration {
    environmentVariables: EnvironmentVariable[];
    source?: DeploymentSource;

    getFixupPrototypeFunction() {
        return DeploymentConfiguration.fixupPrototype;
    }

    static newInstance(model: Partial<DeploymentConfiguration>): DeploymentConfiguration {
        let obj = Object.assign(new DeploymentConfiguration(), model);
        DeploymentConfiguration.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<DeploymentConfiguration>): DeploymentConfiguration | null {
        if (!model) return null;
        return DeploymentConfiguration.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: DeploymentConfiguration) {
        if (!obj) return;

        DeploymentConfiguration.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: DeploymentConfiguration): boolean {
        Object.setPrototypeOf(obj, DeploymentConfiguration.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.environmentVariables) {
            for (let i0 = 0; i0 < this.environmentVariables.length; i0++) {
                let val0 = this.environmentVariables[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { EnvironmentVariable } = require("./EnvironmentVariable");
                    EnvironmentVariable.fixupPrototype(val0);
                }
            }
        }
        if (this.source) {
            // Lazy import - only evaluated when called
            const { DeploymentSource } = require("./DeploymentSource");
            DeploymentSource.fixupPrototype(this.source);
        }
    }
}
