// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { EnvironmentRevisionChangeRequest } from "./EnvironmentRevisionChangeRequest";
import type { EnvironmentRevisionRetracted } from "./EnvironmentRevisionRetracted";


export class EnvironmentRevision {
    number: number;
    created: Date;
    creatorLogin?: string;
    creatorName?: string;
    tags?: string[];
    retracted?: EnvironmentRevisionRetracted;
    sourceChangeRequest?: EnvironmentRevisionChangeRequest;

    getFixupPrototypeFunction() {
        return EnvironmentRevision.fixupPrototype;
    }

    static newInstance(model: Partial<EnvironmentRevision>): EnvironmentRevision {
        let obj = Object.assign(new EnvironmentRevision(), model);
        EnvironmentRevision.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<EnvironmentRevision>): EnvironmentRevision | null {
        if (!model) return null;
        return EnvironmentRevision.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: EnvironmentRevision) {
        if (!obj) return;

        EnvironmentRevision.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: EnvironmentRevision): boolean {
        Object.setPrototypeOf(obj, EnvironmentRevision.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.number === undefined) {
            this.number = 0;
        }
        if (typeof this.created === "string") {
            this.created = new Date(this.created);
        }
        if (this.retracted) {
            // Lazy import - only evaluated when called
            const { EnvironmentRevisionRetracted } = require("./EnvironmentRevisionRetracted");
            EnvironmentRevisionRetracted.fixupPrototype(this.retracted);
        }
        if (this.sourceChangeRequest) {
            // Lazy import - only evaluated when called
            const { EnvironmentRevisionChangeRequest } = require("./EnvironmentRevisionChangeRequest");
            EnvironmentRevisionChangeRequest.fixupPrototype(this.sourceChangeRequest);
        }
    }
}
