// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { ChangeRequestRef } from "./ChangeRequestRef";
import type { UserInfo } from "./UserInfo";


export class EnvironmentMetadata {
    id: string;
    ownedBy: UserInfo;
    activeChangeRequest?: ChangeRequestRef;
    gatedActions?: string[];
    openRequestNeeded?: boolean;

    getFixupPrototypeFunction() {
        return EnvironmentMetadata.fixupPrototype;
    }

    static newInstance(model: Partial<EnvironmentMetadata>): EnvironmentMetadata {
        let obj = Object.assign(new EnvironmentMetadata(), model);
        EnvironmentMetadata.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<EnvironmentMetadata>): EnvironmentMetadata | null {
        if (!model) return null;
        return EnvironmentMetadata.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: EnvironmentMetadata) {
        if (!obj) return;

        EnvironmentMetadata.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: EnvironmentMetadata): boolean {
        Object.setPrototypeOf(obj, EnvironmentMetadata.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.ownedBy) {
            // Lazy import - only evaluated when called
            const { UserInfo } = require("./UserInfo");
            UserInfo.fixupPrototype(this.ownedBy);
        }
        if (this.activeChangeRequest) {
            // Lazy import - only evaluated when called
            const { ChangeRequestRef } = require("./ChangeRequestRef");
            ChangeRequestRef.fixupPrototype(this.activeChangeRequest);
        }
    }
}
