// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// Code generated by pulumi-codegen. DO NOT EDIT.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export class EnvironmentRevisionTag {
    name: string;
    revision: number;
    created: Date;
    modified: Date;
    editorLogin?: string;
    editorName?: string;

    getFixupPrototypeFunction() {
        return EnvironmentRevisionTag.fixupPrototype;
    }

    static newInstance(model: Partial<EnvironmentRevisionTag>): EnvironmentRevisionTag {
        let obj = Object.assign(new EnvironmentRevisionTag(), model);
        EnvironmentRevisionTag.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<EnvironmentRevisionTag>): EnvironmentRevisionTag | null {
        if (!model) return null;
        return EnvironmentRevisionTag.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: EnvironmentRevisionTag) {
        if (!obj) return;

        EnvironmentRevisionTag.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: EnvironmentRevisionTag): boolean {
        Object.setPrototypeOf(obj, EnvironmentRevisionTag.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.revision === undefined) {
            this.revision = 0;
        }
        if (typeof this.created === "string") {
            this.created = new Date(this.created);
        }
        if (typeof this.modified === "string") {
            this.modified = new Date(this.modified);
        }
    }
}
