// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// Code generated by pulumi-codegen. DO NOT EDIT.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export class EnvironmentReferrerMetadata {
    environmentReferrerCount: number;
    stackReferrerCount: number;
    insightsAccountReferrerCount: number;

    getFixupPrototypeFunction() {
        return EnvironmentReferrerMetadata.fixupPrototype;
    }

    static newInstance(model: Partial<EnvironmentReferrerMetadata>): EnvironmentReferrerMetadata {
        let obj = Object.assign(new EnvironmentReferrerMetadata(), model);
        EnvironmentReferrerMetadata.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<EnvironmentReferrerMetadata>): EnvironmentReferrerMetadata | null {
        if (!model) return null;
        return EnvironmentReferrerMetadata.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: EnvironmentReferrerMetadata) {
        if (!obj) return;

        EnvironmentReferrerMetadata.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: EnvironmentReferrerMetadata): boolean {
        Object.setPrototypeOf(obj, EnvironmentReferrerMetadata.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.environmentReferrerCount === undefined) {
            this.environmentReferrerCount = 0;
        }
        if (this.stackReferrerCount === undefined) {
            this.stackReferrerCount = 0;
        }
        if (this.insightsAccountReferrerCount === undefined) {
            this.insightsAccountReferrerCount = 0;
        }
    }
}
