// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { EscRange } from "./EscRange";
import type { EscValue } from "./EscValue";


export class EscTrace {
    def: EscRange;
    base?: EscValue;

    getFixupPrototypeFunction() {
        return EscTrace.fixupPrototype;
    }

    static newInstance(model: Partial<EscTrace>): EscTrace {
        let obj = Object.assign(new EscTrace(), model);
        EscTrace.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<EscTrace>): EscTrace | null {
        if (!model) return null;
        return EscTrace.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: EscTrace) {
        if (!obj) return;

        EscTrace.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: EscTrace): boolean {
        Object.setPrototypeOf(obj, EscTrace.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.def) {
            // Lazy import - only evaluated when called
            const { EscRange } = require("./EscRange");
            EscRange.fixupPrototype(this.def);
        }
        if (this.base) {
            // Lazy import - only evaluated when called
            const { EscValue } = require("./EscValue");
            EscValue.fixupPrototype(this.base);
        }
    }
}
