// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { TemplateSource } from "./TemplateSource";


export class GetOrgTemplateSourcesResponse {
    sources: TemplateSource[];

    getFixupPrototypeFunction() {
        return GetOrgTemplateSourcesResponse.fixupPrototype;
    }

    static newInstance(model: Partial<GetOrgTemplateSourcesResponse>): GetOrgTemplateSourcesResponse {
        let obj = Object.assign(new GetOrgTemplateSourcesResponse(), model);
        GetOrgTemplateSourcesResponse.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<GetOrgTemplateSourcesResponse>): GetOrgTemplateSourcesResponse | null {
        if (!model) return null;
        return GetOrgTemplateSourcesResponse.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: GetOrgTemplateSourcesResponse) {
        if (!obj) return;

        GetOrgTemplateSourcesResponse.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: GetOrgTemplateSourcesResponse): boolean {
        Object.setPrototypeOf(obj, GetOrgTemplateSourcesResponse.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.sources) {
            for (let i0 = 0; i0 < this.sources.length; i0++) {
                let val0 = this.sources[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { TemplateSource } = require("./TemplateSource");
                    TemplateSource.fixupPrototype(val0);
                }
            }
        }
    }
}
