// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// Code generated by pulumi-codegen. DO NOT EDIT.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export class GetPendingEmailVerificationResponse {
    email: string;

    getFixupPrototypeFunction() {
        return GetPendingEmailVerificationResponse.fixupPrototype;
    }

    static newInstance(model: Partial<GetPendingEmailVerificationResponse>): GetPendingEmailVerificationResponse {
        let obj = Object.assign(new GetPendingEmailVerificationResponse(), model);
        GetPendingEmailVerificationResponse.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<GetPendingEmailVerificationResponse>): GetPendingEmailVerificationResponse | null {
        if (!model) return null;
        return GetPendingEmailVerificationResponse.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: GetPendingEmailVerificationResponse) {
        if (!obj) return;

        GetPendingEmailVerificationResponse.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: GetPendingEmailVerificationResponse): boolean {
        Object.setPrototypeOf(obj, GetPendingEmailVerificationResponse.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        // Nothing to do.
    }
}
