// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { ResourceInfo } from "./ResourceInfo";


export class GetStackResourceResponse {
    resource: ResourceInfo;
    region: string;
    version: number;

    getFixupPrototypeFunction() {
        return GetStackResourceResponse.fixupPrototype;
    }

    static newInstance(model: Partial<GetStackResourceResponse>): GetStackResourceResponse {
        let obj = Object.assign(new GetStackResourceResponse(), model);
        GetStackResourceResponse.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<GetStackResourceResponse>): GetStackResourceResponse | null {
        if (!model) return null;
        return GetStackResourceResponse.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: GetStackResourceResponse) {
        if (!obj) return;

        GetStackResourceResponse.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: GetStackResourceResponse): boolean {
        Object.setPrototypeOf(obj, GetStackResourceResponse.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.resource) {
            // Lazy import - only evaluated when called
            const { ResourceInfo } = require("./ResourceInfo");
            ResourceInfo.fixupPrototype(this.resource);
        }
        if (this.version === undefined) {
            this.version = 0;
        }
    }
}
