// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { BasicAuthRequest } from "./BasicAuthRequest";
import type { SSHAuthRequest } from "./SSHAuthRequest";
import type { SecretValue } from "./SecretValue";


export class GitAuthConfigRequest {
    accessToken?: SecretValue;
    sshAuth?: SSHAuthRequest;
    basicAuth?: BasicAuthRequest;

    getFixupPrototypeFunction() {
        return GitAuthConfigRequest.fixupPrototype;
    }

    static newInstance(model: Partial<GitAuthConfigRequest>): GitAuthConfigRequest {
        let obj = Object.assign(new GitAuthConfigRequest(), model);
        GitAuthConfigRequest.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<GitAuthConfigRequest>): GitAuthConfigRequest | null {
        if (!model) return null;
        return GitAuthConfigRequest.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: GitAuthConfigRequest) {
        if (!obj) return;

        GitAuthConfigRequest.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: GitAuthConfigRequest): boolean {
        Object.setPrototypeOf(obj, GitAuthConfigRequest.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.accessToken !== undefined && this.accessToken !== null) {
            // Lazy import - only evaluated when called
            const { SecretValue } = require("./SecretValue");
            if (typeof this.accessToken === "string") {
                this.accessToken = SecretValue.newInstance({plaintext: this.accessToken});
            }
            SecretValue.fixupPrototype(this.accessToken);
        }
        if (this.sshAuth) {
            // Lazy import - only evaluated when called
            const { SSHAuthRequest } = require("./SSHAuthRequest");
            SSHAuthRequest.fixupPrototype(this.sshAuth);
        }
        if (this.basicAuth) {
            // Lazy import - only evaluated when called
            const { BasicAuthRequest } = require("./BasicAuthRequest");
            BasicAuthRequest.fixupPrototype(this.basicAuth);
        }
    }
}
