// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { GraphAggregations } from "./GraphAggregations";
import type { GraphEdge } from "./GraphEdge";
import type { GraphNode } from "./GraphNode";
import type { GraphPageInfo } from "./GraphPageInfo";
import type { GraphPath } from "./GraphPath";
import type { GraphQueryMeta } from "./GraphQueryMeta";


export class GraphQueryResponse {
    nodes: GraphNode[];
    edges: GraphEdge[];
    paths?: GraphPath[];
    aggregations: GraphAggregations;
    pageInfo: GraphPageInfo;
    meta: GraphQueryMeta;

    getFixupPrototypeFunction() {
        return GraphQueryResponse.fixupPrototype;
    }

    static newInstance(model: Partial<GraphQueryResponse>): GraphQueryResponse {
        let obj = Object.assign(new GraphQueryResponse(), model);
        GraphQueryResponse.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<GraphQueryResponse>): GraphQueryResponse | null {
        if (!model) return null;
        return GraphQueryResponse.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: GraphQueryResponse) {
        if (!obj) return;

        GraphQueryResponse.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: GraphQueryResponse): boolean {
        Object.setPrototypeOf(obj, GraphQueryResponse.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.nodes) {
            for (let i0 = 0; i0 < this.nodes.length; i0++) {
                let val0 = this.nodes[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { GraphNode } = require("./GraphNode");
                    GraphNode.fixupPrototype(val0);
                }
            }
        }
        if (this.edges) {
            for (let i0 = 0; i0 < this.edges.length; i0++) {
                let val0 = this.edges[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { GraphEdge } = require("./GraphEdge");
                    GraphEdge.fixupPrototype(val0);
                }
            }
        }
        if (this.paths) {
            for (let i0 = 0; i0 < this.paths.length; i0++) {
                let val0 = this.paths[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { GraphPath } = require("./GraphPath");
                    GraphPath.fixupPrototype(val0);
                }
            }
        }
        if (this.aggregations) {
            // Lazy import - only evaluated when called
            const { GraphAggregations } = require("./GraphAggregations");
            GraphAggregations.fixupPrototype(this.aggregations);
        }
        if (this.pageInfo) {
            // Lazy import - only evaluated when called
            const { GraphPageInfo } = require("./GraphPageInfo");
            GraphPageInfo.fixupPrototype(this.pageInfo);
        }
        if (this.meta) {
            // Lazy import - only evaluated when called
            const { GraphQueryMeta } = require("./GraphQueryMeta");
            GraphQueryMeta.fixupPrototype(this.meta);
        }
    }
}
