// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import { GraphFieldPredicate } from "./GraphFieldPredicate";


export class GraphFieldPredicateAbsent extends GraphFieldPredicate {
    constructor() {
        super();
        this.setDiscriminator("absent");
    }

    getFixupPrototypeFunction() {
        return GraphFieldPredicateAbsent.fixupPrototype;
    }

    static newInstance(model: Partial<GraphFieldPredicateAbsent>): GraphFieldPredicateAbsent {
        let obj = Object.assign(new GraphFieldPredicateAbsent(), model);
        GraphFieldPredicateAbsent.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<GraphFieldPredicateAbsent>): GraphFieldPredicateAbsent | null {
        if (!model) return null;
        return GraphFieldPredicateAbsent.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: GraphFieldPredicateAbsent) {
        if (!obj) return;

        GraphFieldPredicateAbsent.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: GraphFieldPredicateAbsent): boolean {
        if (GraphFieldPredicate.setPrototype(obj)) {
            return true; // A polymorphic type, skip overwriting the prototype.
        }
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        super.fixupFields();
    }
}
