// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { GraphAggregationBucket } from "./GraphAggregationBucket";


export class GraphAggregations {
    buckets: GraphAggregationBucket[];

    getFixupPrototypeFunction() {
        return GraphAggregations.fixupPrototype;
    }

    static newInstance(model: Partial<GraphAggregations>): GraphAggregations {
        let obj = Object.assign(new GraphAggregations(), model);
        GraphAggregations.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<GraphAggregations>): GraphAggregations | null {
        if (!model) return null;
        return GraphAggregations.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: GraphAggregations) {
        if (!obj) return;

        GraphAggregations.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: GraphAggregations): boolean {
        Object.setPrototypeOf(obj, GraphAggregations.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.buckets) {
            for (let i0 = 0; i0 < this.buckets.length; i0++) {
                let val0 = this.buckets[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { GraphAggregationBucket } = require("./GraphAggregationBucket");
                    GraphAggregationBucket.fixupPrototype(val0);
                }
            }
        }
    }
}
