// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { ChangeGate } from "./ChangeGate";


export class ListChangeGatesResponse {
    gates: ChangeGate[];
    continuationToken: string;

    getFixupPrototypeFunction() {
        return ListChangeGatesResponse.fixupPrototype;
    }

    static newInstance(model: Partial<ListChangeGatesResponse>): ListChangeGatesResponse {
        let obj = Object.assign(new ListChangeGatesResponse(), model);
        ListChangeGatesResponse.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<ListChangeGatesResponse>): ListChangeGatesResponse | null {
        if (!model) return null;
        return ListChangeGatesResponse.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: ListChangeGatesResponse) {
        if (!obj) return;

        ListChangeGatesResponse.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: ListChangeGatesResponse): boolean {
        Object.setPrototypeOf(obj, ListChangeGatesResponse.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.gates) {
            for (let i0 = 0; i0 < this.gates.length; i0++) {
                let val0 = this.gates[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { ChangeGate } = require("./ChangeGate");
                    ChangeGate.fixupPrototype(val0);
                }
            }
        }
    }
}
