// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { OperationContextAWSOIDCConfigurationRequest } from "./OperationContextAWSOIDCConfigurationRequest";
import type { OperationContextAzureOIDCConfigurationRequest } from "./OperationContextAzureOIDCConfigurationRequest";
import type { OperationContextGCPOIDCConfigurationRequest } from "./OperationContextGCPOIDCConfigurationRequest";


export class OperationContextOIDCConfigurationRequest {
    aws?: OperationContextAWSOIDCConfigurationRequest;
    azure?: OperationContextAzureOIDCConfigurationRequest;
    gcp?: OperationContextGCPOIDCConfigurationRequest;

    getFixupPrototypeFunction() {
        return OperationContextOIDCConfigurationRequest.fixupPrototype;
    }

    static newInstance(model: Partial<OperationContextOIDCConfigurationRequest>): OperationContextOIDCConfigurationRequest {
        let obj = Object.assign(new OperationContextOIDCConfigurationRequest(), model);
        OperationContextOIDCConfigurationRequest.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<OperationContextOIDCConfigurationRequest>): OperationContextOIDCConfigurationRequest | null {
        if (!model) return null;
        return OperationContextOIDCConfigurationRequest.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: OperationContextOIDCConfigurationRequest) {
        if (!obj) return;

        OperationContextOIDCConfigurationRequest.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: OperationContextOIDCConfigurationRequest): boolean {
        Object.setPrototypeOf(obj, OperationContextOIDCConfigurationRequest.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.aws) {
            // Lazy import - only evaluated when called
            const { OperationContextAWSOIDCConfigurationRequest } = require("./OperationContextAWSOIDCConfigurationRequest");
            OperationContextAWSOIDCConfigurationRequest.fixupPrototype(this.aws);
        }
        if (this.azure) {
            // Lazy import - only evaluated when called
            const { OperationContextAzureOIDCConfigurationRequest } = require("./OperationContextAzureOIDCConfigurationRequest");
            OperationContextAzureOIDCConfigurationRequest.fixupPrototype(this.azure);
        }
        if (this.gcp) {
            // Lazy import - only evaluated when called
            const { OperationContextGCPOIDCConfigurationRequest } = require("./OperationContextGCPOIDCConfigurationRequest");
            OperationContextGCPOIDCConfigurationRequest.fixupPrototype(this.gcp);
        }
    }
}
