// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { OrganizationRole } from "./OrganizationRole";
import { OrganizationSummary } from "./OrganizationSummary";


export class OrganizationSummaryWithRole extends OrganizationSummary {
    role: OrganizationRole;

    getFixupPrototypeFunction() {
        return OrganizationSummaryWithRole.fixupPrototype;
    }

    static newInstance(model: Partial<OrganizationSummaryWithRole>): OrganizationSummaryWithRole {
        let obj = Object.assign(new OrganizationSummaryWithRole(), model);
        OrganizationSummaryWithRole.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<OrganizationSummaryWithRole>): OrganizationSummaryWithRole | null {
        if (!model) return null;
        return OrganizationSummaryWithRole.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: OrganizationSummaryWithRole) {
        if (!obj) return;

        OrganizationSummaryWithRole.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: OrganizationSummaryWithRole): boolean {
        if (OrganizationSummary.setPrototype(obj)) {
            return true; // A polymorphic type, skip overwriting the prototype.
        }
        Object.setPrototypeOf(obj, OrganizationSummaryWithRole.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        super.fixupFields();
    }
}
