// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { PermissionBooleanExpression } from "./PermissionBooleanExpression";
import { PermissionDescriptor } from "./PermissionDescriptor";


export class PermissionDescriptorCondition extends PermissionDescriptor {
    condition?: PermissionBooleanExpression;
    subNode?: PermissionDescriptor;

    constructor() {
        super();
        this.setDiscriminator("PermissionDescriptorCondition");
    }

    getFixupPrototypeFunction() {
        return PermissionDescriptorCondition.fixupPrototype;
    }

    static newInstance(model: Partial<PermissionDescriptorCondition>): PermissionDescriptorCondition {
        let obj = Object.assign(new PermissionDescriptorCondition(), model);
        PermissionDescriptorCondition.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<PermissionDescriptorCondition>): PermissionDescriptorCondition | null {
        if (!model) return null;
        return PermissionDescriptorCondition.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: PermissionDescriptorCondition) {
        if (!obj) return;

        PermissionDescriptorCondition.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: PermissionDescriptorCondition): boolean {
        if (PermissionDescriptor.setPrototype(obj)) {
            return true; // A polymorphic type, skip overwriting the prototype.
        }
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        super.fixupFields();
        if (this.condition) {
            // Lazy import - only evaluated when called
            const { PermissionBooleanExpression } = require("./PermissionBooleanExpression");
            PermissionBooleanExpression.fixupPrototype(this.condition);
        }
        if (this.subNode) {
            PermissionDescriptor.fixupPrototype(this.subNode);
        }
    }
}
