// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { UpdateSummary } from "./UpdateSummary";


export class PulumiStack {
    programId: string;
    name: string;
    lastUpdate?: UpdateSummary;
    routingRepo: string;
    routingProject: string;
    tags?: { [key: string]: string };
    protectedByPolicy: boolean;
    hasDeploymentSettings: boolean;
    driftDetected: boolean;

    getFixupPrototypeFunction() {
        return PulumiStack.fixupPrototype;
    }

    static newInstance(model: Partial<PulumiStack>): PulumiStack {
        let obj = Object.assign(new PulumiStack(), model);
        PulumiStack.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<PulumiStack>): PulumiStack | null {
        if (!model) return null;
        return PulumiStack.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: PulumiStack) {
        if (!obj) return;

        PulumiStack.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: PulumiStack): boolean {
        Object.setPrototypeOf(obj, PulumiStack.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.lastUpdate) {
            // Lazy import - only evaluated when called
            const { UpdateSummary } = require("./UpdateSummary");
            UpdateSummary.fixupPrototype(this.lastUpdate);
        }
    }
}
