// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { GitAuthConfigRequest } from "./GitAuthConfigRequest";


export class SourceContextGitRequest {
    repoUrl?: string;
    branch?: string;
    repoDir?: string;
    commit?: string;
    tag?: string;
    gitAuth?: GitAuthConfigRequest;

    getFixupPrototypeFunction() {
        return SourceContextGitRequest.fixupPrototype;
    }

    static newInstance(model: Partial<SourceContextGitRequest>): SourceContextGitRequest {
        let obj = Object.assign(new SourceContextGitRequest(), model);
        SourceContextGitRequest.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<SourceContextGitRequest>): SourceContextGitRequest | null {
        if (!model) return null;
        return SourceContextGitRequest.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: SourceContextGitRequest) {
        if (!obj) return;

        SourceContextGitRequest.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: SourceContextGitRequest): boolean {
        Object.setPrototypeOf(obj, SourceContextGitRequest.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.gitAuth) {
            // Lazy import - only evaluated when called
            const { GitAuthConfigRequest } = require("./GitAuthConfigRequest");
            GitAuthConfigRequest.fixupPrototype(this.gitAuth);
        }
    }
}
