// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { InsightsAccountPermission } from "./InsightsAccountPermission";


export class TeamAccountPermission {
    accountName: string;
    permission: InsightsAccountPermission;
    permissionSetName?: string;

    getFixupPrototypeFunction() {
        return TeamAccountPermission.fixupPrototype;
    }

    static newInstance(model: Partial<TeamAccountPermission>): TeamAccountPermission {
        let obj = Object.assign(new TeamAccountPermission(), model);
        TeamAccountPermission.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<TeamAccountPermission>): TeamAccountPermission | null {
        if (!model) return null;
        return TeamAccountPermission.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: TeamAccountPermission) {
        if (!obj) return;

        TeamAccountPermission.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: TeamAccountPermission): boolean {
        Object.setPrototypeOf(obj, TeamAccountPermission.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        // Nothing to do.
    }
}
