// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import { TerraformModule } from "./TerraformModule";
import type { TerraformModuleExample } from "./TerraformModuleExample";
import type { TerraformModuleInput } from "./TerraformModuleInput";
import type { TerraformModuleOutput } from "./TerraformModuleOutput";
import type { TerraformModulePackageConversion } from "./TerraformModulePackageConversion";
import type { TerraformModuleProviderRequirement } from "./TerraformModuleProviderRequirement";
import type { TerraformModuleSubmodule } from "./TerraformModuleSubmodule";


export class TerraformModuleVersion extends TerraformModule {
    version: string;
    sha256: string;
    sizeBytes: number;
    readme?: string;
    inputs: TerraformModuleInput[];
    outputs: TerraformModuleOutput[];
    providerRequirements: TerraformModuleProviderRequirement[];
    submodules?: TerraformModuleSubmodule[];
    examples?: TerraformModuleExample[];
    packageConversion?: TerraformModulePackageConversion;

    getFixupPrototypeFunction() {
        return TerraformModuleVersion.fixupPrototype;
    }

    static newInstance(model: Partial<TerraformModuleVersion>): TerraformModuleVersion {
        let obj = Object.assign(new TerraformModuleVersion(), model);
        TerraformModuleVersion.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<TerraformModuleVersion>): TerraformModuleVersion | null {
        if (!model) return null;
        return TerraformModuleVersion.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: TerraformModuleVersion) {
        if (!obj) return;

        TerraformModuleVersion.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: TerraformModuleVersion): boolean {
        if (TerraformModule.setPrototype(obj)) {
            return true; // A polymorphic type, skip overwriting the prototype.
        }
        Object.setPrototypeOf(obj, TerraformModuleVersion.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    static getTypeHierarchy(): (typeof TerraformModuleVersion)[] {
        // Lazy import - only evaluated when called
        const { GetTerraformModuleResponse } = require("./GetTerraformModuleResponse");

        return [
            GetTerraformModuleResponse,
        ];
    }

    fixupFields() {
        super.fixupFields();
        if (this.sizeBytes === undefined) {
            this.sizeBytes = 0;
        }
        if (this.inputs) {
            for (let i0 = 0; i0 < this.inputs.length; i0++) {
                let val0 = this.inputs[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { TerraformModuleInput } = require("./TerraformModuleInput");
                    TerraformModuleInput.fixupPrototype(val0);
                }
            }
        }
        if (this.outputs) {
            for (let i0 = 0; i0 < this.outputs.length; i0++) {
                let val0 = this.outputs[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { TerraformModuleOutput } = require("./TerraformModuleOutput");
                    TerraformModuleOutput.fixupPrototype(val0);
                }
            }
        }
        if (this.providerRequirements) {
            for (let i0 = 0; i0 < this.providerRequirements.length; i0++) {
                let val0 = this.providerRequirements[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { TerraformModuleProviderRequirement } = require("./TerraformModuleProviderRequirement");
                    TerraformModuleProviderRequirement.fixupPrototype(val0);
                }
            }
        }
        if (this.submodules) {
            for (let i0 = 0; i0 < this.submodules.length; i0++) {
                let val0 = this.submodules[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { TerraformModuleSubmodule } = require("./TerraformModuleSubmodule");
                    TerraformModuleSubmodule.fixupPrototype(val0);
                }
            }
        }
        if (this.examples) {
            for (let i0 = 0; i0 < this.examples.length; i0++) {
                let val0 = this.examples[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { TerraformModuleExample } = require("./TerraformModuleExample");
                    TerraformModuleExample.fixupPrototype(val0);
                }
            }
        }
        if (this.packageConversion) {
            // Lazy import - only evaluated when called
            const { TerraformModulePackageConversion } = require("./TerraformModulePackageConversion");
            TerraformModulePackageConversion.fixupPrototype(this.packageConversion);
        }
    }
}
