// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { AppPolicyPackMetadata } from "./AppPolicyPackMetadata";
import type { AppUpdateInfo } from "./AppUpdateInfo";
import type { GitHubCommitInfo } from "./GitHubCommitInfo";
import type { UserInfo } from "./UserInfo";


export class UpdateInfo {
    info: AppUpdateInfo;
    updateID: string;
    githubCommitInfo?: GitHubCommitInfo;
    version: number;
    latestVersion: number;
    requestedBy: UserInfo;
    policyPacks?: AppPolicyPackMetadata[];
    requestedByToken?: string;

    getFixupPrototypeFunction() {
        return UpdateInfo.fixupPrototype;
    }

    static newInstance(model: Partial<UpdateInfo>): UpdateInfo {
        let obj = Object.assign(new UpdateInfo(), model);
        UpdateInfo.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<UpdateInfo>): UpdateInfo | null {
        if (!model) return null;
        return UpdateInfo.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: UpdateInfo) {
        if (!obj) return;

        UpdateInfo.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: UpdateInfo): boolean {
        Object.setPrototypeOf(obj, UpdateInfo.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        if (this.info) {
            // Lazy import - only evaluated when called
            const { AppUpdateInfo } = require("./AppUpdateInfo");
            AppUpdateInfo.fixupPrototype(this.info);
        }
        if (this.githubCommitInfo) {
            // Lazy import - only evaluated when called
            const { GitHubCommitInfo } = require("./GitHubCommitInfo");
            GitHubCommitInfo.fixupPrototype(this.githubCommitInfo);
        }
        if (this.version === undefined) {
            this.version = 0;
        }
        if (this.latestVersion === undefined) {
            this.latestVersion = 0;
        }
        if (this.requestedBy) {
            // Lazy import - only evaluated when called
            const { UserInfo } = require("./UserInfo");
            UserInfo.fixupPrototype(this.requestedBy);
        }
        if (this.policyPacks) {
            for (let i0 = 0; i0 < this.policyPacks.length; i0++) {
                let val0 = this.policyPacks[i0];
                if (val0) {
                    // Lazy import - only evaluated when called
                    const { AppPolicyPackMetadata } = require("./AppPolicyPackMetadata");
                    AppPolicyPackMetadata.fixupPrototype(val0);
                }
            }
        }
    }
}
