// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

export class UpdateCustomVCSIntegrationRequest {
    name?: string;
    baseUrl?: string;
    environment?: string;
    regenerateWebhookSecret?: boolean;

    getFixupPrototypeFunction() {
        return UpdateCustomVCSIntegrationRequest.fixupPrototype;
    }

    static newInstance(model: Partial<UpdateCustomVCSIntegrationRequest>): UpdateCustomVCSIntegrationRequest {
        let obj = Object.assign(new UpdateCustomVCSIntegrationRequest(), model);
        UpdateCustomVCSIntegrationRequest.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<UpdateCustomVCSIntegrationRequest>): UpdateCustomVCSIntegrationRequest | null {
        if (!model) return null;
        return UpdateCustomVCSIntegrationRequest.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: UpdateCustomVCSIntegrationRequest) {
        if (!obj) return;

        UpdateCustomVCSIntegrationRequest.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: UpdateCustomVCSIntegrationRequest): boolean {
        Object.setPrototypeOf(obj, UpdateCustomVCSIntegrationRequest.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        // Nothing to do.
    }
}
