// Copyright 2016-2026, Pulumi Corporation. All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable max-len */
/* eslint-disable no-underscore-dangle */
/* eslint-disable prettier/prettier */
/* eslint-disable simple-import-sort/exports */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable sonarjs/prefer-single-boolean-return */
/* eslint-disable unused-imports/no-unused-imports */

import type { VCSProvider } from "./VCSProvider";


export class VCSIntegrationSummary {
    name?: string;
    avatarUrl?: string;
    id: string;
    vcsProvider: VCSProvider;
    hasIndividualAccess: boolean;
    host?: string;
    baseUrl?: string;

    getFixupPrototypeFunction() {
        return VCSIntegrationSummary.fixupPrototype;
    }

    static newInstance(model: Partial<VCSIntegrationSummary>): VCSIntegrationSummary {
        let obj = Object.assign(new VCSIntegrationSummary(), model);
        VCSIntegrationSummary.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<VCSIntegrationSummary>): VCSIntegrationSummary | null {
        if (!model) return null;
        return VCSIntegrationSummary.newInstance(JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: VCSIntegrationSummary) {
        if (!obj) return;

        VCSIntegrationSummary.setPrototype(obj);

        obj.fixupFields();
    }

    protected static setPrototype(obj: VCSIntegrationSummary): boolean {
        Object.setPrototypeOf(obj, VCSIntegrationSummary.prototype);
        return false; // Not a polymorphic type, okay to overwrite the prototype.
    }

    fixupFields() {
        // Nothing to do.
    }
}
