// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

package apitype

// AuditLogEventTypeCatalogEntry describes one audit log event type.
type AuditLogEventTypeCatalogEntry struct {
	// The event type identifier, as it appears in the 'event' field of an audit log entry and as accepted by the 'eventFilter' query
	// parameter.
	Event string `json:"event" yaml:"event"`
	// The event type's name, for display in a user interface or a report.
	DisplayName string `json:"displayName" yaml:"displayName"`
	// What the event records, written for someone auditing an organization.
	Description string `json:"description" yaml:"description"`
	// Whether the action that records this event requires the organization ADMIN role.
	RequiresOrgAdmin bool `json:"requiresOrgAdmin" yaml:"requiresOrgAdmin"`
	// Whether the action that records this event requires the stack ADMIN role.
	RequiresStackAdmin bool `json:"requiresStackAdmin" yaml:"requiresStackAdmin"`
	// Whether this event records a failed authorization check rather than a completed action.
	AuthenticationFailure bool `json:"authenticationFailure" yaml:"authenticationFailure"`
}
