// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

package apitype

// Response from Copilot skill invocation
type CopilotResponse struct {
	// Messages in the conversation (typically from the assistant)
	Messages []CopilotMessage `json:"messages,omitempty" yaml:"messages,omitempty"`
	// Error message if the request failed
	Error string `json:"error,omitempty" yaml:"error,omitempty"`
	// Additional error context or debugging information
	Details string `json:"details,omitempty" yaml:"details,omitempty"`
}
