name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        language: [go, nodejs, python, java, dotnet]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: make build_${{ matrix.language }}
      - run: make test_${{ matrix.language }}
